### ISSUE TITLE
Default app tag has null value

### ISSUE THREAD

**Issue by nullpainter** [AppMetrics/AppMetrics#168]
After upgrading from 1.1.2.0 to version 1.2.0, my tests and application started failing with the following exception in `MetricsTags`:

> values keys cannot contains empty or whitespace strings

None of my code writes null tag values.

I traced the issue down to a null value for `app` which was being added by App.Metrics itself via a global tag. Setting `AppMetricsOptions.AddDefaultGlobalTags` to `false` solved the issue.

I'm using .NET 4.5.2. 

If a default global tag resolves to a null value, I propose either a more useful error message (possibly including the tag key - this would also be useful outside of the context of this particular issue), or skipping the tag entirely. For me, this behaviour was unexpected and resulted in having to step through decompiled source.

Note - my issue is less that it was null and more about the error reporting around this.

**Comment by alhardy** [comment]
@nullpainter Thanks for digging in and pointing this out.

This would be a result of this update: https://github.com/alhardy/AppMetrics/issues/141 in the last release.

I decided to add these tags by default as they are typically used and it cleans up the boilerplate code required.

I do need to do more testing on .NET 4.5.2 for releases, I've been a bit slack here unfortunetly thinking usage would be very low. I'll keep this mind for future releases.

In terms of a more detailed error message, the `app` tag's value is by default set as the entry assembly name which shouldn't ever be null so didn't bother, the oversite here was the difference in later versions of .NET and getting assembly info.
