### ISSUE TITLE
JSON Serialization issues

### ISSUE THREAD

**Issue by TaffarelJr** [AppMetrics/AppMetrics#180]
I'm having a little trouble with JSON serialization. It was working when i initially set my project up, but now - after updating to newer versions - it seems to have changed somewhere along the way. Specifically I see two issues:

* The `/env` endpoint complains that `No formatter has been registered. See App.Metrics.Formatters.Ascii for example.` Looking through the source, it looks like the call to `AddJsonSerialization()` has been changed to be a wrapper around several subroutines; and when calling it without passing in a `JsonSerializerSettings` object, it looks like it doesn't call `AddJsonEnvironmentInfoSerialization(...)`. Is that functionality supposed to be missing?

* The `/metrics` and `/metrics-text` endpoints appear to be returning the same data - a large JSON blob - whereas before, the `/metrics-text` endpoint was more human-readable. Is there some new configuration setting I need to include to get that back to working the way it was before?

**Comment by alhardy** [comment]
@TaffarelJr 

- Yeah that's a bug, for now just call `AddJsonEnvironmentInfoSerialization` as well - https://github.com/alhardy/AppMetrics/blob/dev/src/App.Metrics.Formatters.Json/MetricsHostExtensions.cs#L25

- If you're just calling `AddJsonSerialization`, yes both `/metrics` and `/metrics-text` will use the same formatter, try using `AddAsciiMetricsTextSerialization` for the more human-readable version of the metrics data. http://app-metrics.io/web-application-monitoring/formatters/ascii-formatter.html

**Comment by TaffarelJr** [comment]
Thanks, that's what I needed. I'll just take the approach of adding specific formatters per endpoint instead of relying on the catch-all.

**Comment by alhardy** [comment]
2.0 updates on this here https://www.app-metrics.io/web-monitoring/aspnet-core/endpoint-middleware/
