### ISSUE TITLE
Add item string to Gauge

### ISSUE THREAD

**Issue by MrSmoke** [AppMetrics/AppMetrics#188]
Meters and Counters allow you to specify a string value for item:
```cs
void Mark(MeterOptions options, string item);
void Increment(CounterOptions options, string item);
```

would be great if gauges could also support this.

**Comment by alhardy** [comment]
@MrSmoke can you provide an example of what you'd be using that for?

I've been thinking about removing the `set-item` concept has you can tag metrics at run-time now.

**Comment by alhardy** [comment]
I haven't yet come across or can think of a use case where this would be helpful, happy to revisit if one can be suggested.

**Comment by LordMike** [comment]
@alhardy I'm just beginning to use metrics in an application, and I came across wanting to count the number of users, and from that - the number of inactives, actives, etc.

So, following the [counters example with sub-emails](https://www.app-metrics.io/getting-started/metric-types/counters/#using-counters), I'd make a reporting like this:

```csharp
_metrics.Measure.Gauge.SetValue(MetricsConfigurations.Users, total, "total");
_metrics.Measure.Gauge.SetValue(MetricsConfigurations.Users, inactive, "inactive");
_metrics.Measure.Gauge.SetValue(MetricsConfigurations.Users, active, "active");
_metrics.Measure.Gauge.SetValue(MetricsConfigurations.Users, deactivated, "deactivated");
_metrics.Measure.Gauge.SetValue(MetricsConfigurations.Users, pendingReactivate, "pendingReactivate");
```

.. but maybe I've misunderstood. I couldn't find a guide on how many denominations of a number I should track in separate counters. Or if those should be other kinds of counters, or ..
