### ISSUE TITLE
how to use it in webapi

### ISSUE THREAD

**Issue by Jesn** [AppMetrics/AppMetrics#195]
.net CLR:  4.6.1
I want to use AppMetrics In my WebApi Application, metrics data write to influxdb,how I do?

**Comment by alhardy** [comment]
You can use the [App.Metrics](https://www.nuget.org/packages/App.Metrics/2.0.0-alpha) nuget package to record your own metrics and the [InfluxDB Reporting](https://www.nuget.org/packages/App.Metrics.Extensions.Reporting.InfluxDB/) nuget package to flush to influxdb. 

To configure influxdb reporting see [here](https://www.app-metrics.io/reporting/reporters/influx-data/).

For ASP.NET Core 2.0 App Metrics provides these packages: https://www.app-metrics.io/web-monitoring/aspnet-core/. At the moment I don't have only plans for OWIN equivalents for example.

**Comment by vothanhphu** [comment]
I just make a guide video here.
You can see How I do that
https://www.youtube.com/watch?v=i4u9SzfSkic
