### ISSUE TITLE
Monitoring issues

### ISSUE THREAD

**Issue by ptrstpp950** [AppMetrics/AppMetrics#196]
First of all, I'm almost sure that I configured something badly, but I don't know what should I do.

**The environment**
I have the following setup

1.  .NET Core apps which run on Azure App Service
2.  All of them have App metrics included (version 1.3)
3.  InfluxDB + Grapaha are installed on separate VM

**The problem**
All my services are blink from time to time exactly as on the screenshot below.
![issue](https://user-images.githubusercontent.com/2411329/32004080-3f7e9b44-b9a1-11e7-8686-3a1deee4d6f7.png)
We check services with dependencies and without. All of them have same problems.

**The question**
What we possibly did wrong? Or what should I check to fix such stupid errors?

**Comment by alhardy** [comment]
Health check values are only reported when '/health' is requested. My setup is using pingdom to periodically request '/health'. You could schedule a task in-process to have your app execute your health checks.

**Comment by ptrstpp950** [comment]
Maybe I don't understand something, but I created reporter like 

```
            metricsHostBuilder.AddReporting(factory =>
            {
                var influxFilter = new DefaultMetricsFilter()
                    .WithHealthChecks(true)
                    .WithEnvironmentInfo(true);

                factory.AddInfluxDb(new InfluxDBReporterSettings
                {
                    HttpPolicy = new HttpPolicy
                    {
                        FailuresBeforeBackoff = 3,
                        BackoffPeriod = TimeSpan.FromSeconds(30),
                        Timeout = TimeSpan.FromSeconds(3)
                    },
                    InfluxDbSettings = new InfluxDBSettings(dbName, new Uri(dbUrl)),
                    ReportInterval = TimeSpan.FromSeconds(10)
                }, influxFilter);
            });
```

If I understand the documentation correctly, above code should send report data to InfluxDB every 10 seconds. So I don't have to manually trigger health endpoint.

**Comment by alhardy** [comment]
Maybe reviewing [this code](https://github.com/AppMetrics/AppMetrics/blob/bd0f3c36349496cd0d0e26f50866b28ecf0768aa/src/App.Metrics/Health/Internal/DefaultHealthProvider.cs#L38) would make sense of it?

Metrics are flushed every configured interval, however the health gauges are only set when `IProvideHealth.ReadStatusAsync` is executed e.g. when `/health` is requested.

Also see [here](https://al-hardy.blog/2017/04/28/asp-net-core-monitoring-with-influxdb-grafana/#comment-21)

I think reporting metrics and periodically checking health are two different things, hence the metrics reporter you've configured is not executing health checks.

Also note that in the latest version of App Metrics, metrics and health are decoupled, functionality is provided as separate nuget packages.
