### ISSUE TITLE
Instance of IMetrics

### ISSUE THREAD

**Issue by StinaSten** [AppMetrics/AppMetrics#197]
In all descriptions it is mention that the easiest way to create an IMetrics instance is to use CreateDefaultBuilder (or MetricsBuilder).

Is it correct that this is only supported in AppMetrics 2.0  (current in an alpha release)?

All code examples initiate IMetrics instance by:
	public ValuesController(IMetrics metrics)

I have tried that and it works fine but run into problem when it come to unit testing (using MSTest).
The unit test create a controller instance but I haven't figured out how to include an IMetrics instance that is not null.
Anyone that can help out in this matter?

**Comment by alhardy** [comment]
Yes `CreateDefaultBuilder` is an AppMetrics 2.0 thing.

I'm not exactly sure what you mean by "The unit test create a controller instance but I haven't figured out how to include an IMetrics instance that is not null"?

Is your test instantiating the controller instance directly to test it's action methods or are you using `Microsoft.AspNetCore.TestHost.TestServer`? Code example would help.

**Comment by StinaSten** [comment]
The test is instantiating the controller.
controller.cs
`        public Controller2(IMetrics _metrics)`
`        {`
`            logger.Trace("Constructor called");`
`            metrics = _metrics;`
`        }`
and then I have the unit test (unittest.cs) that:
`Controller2 cntrl = new Controller2(test_metrics);`
` IEnumerable<string> actualvalue = cntrl.Get();`
then performs test on _actualvalue_.

I can use MetricsBuilder to instantiate  _test_metrics_ but I haven't figured out how to do it if using AppMetrics prior to 2.0.

**Comment by alhardy** [comment]
You could Mock `IMetrics` or you could do something like the pre 2.0 tests https://github.com/AppMetrics/AppMetrics/blob/bd0f3c36349496cd0d0e26f50866b28ecf0768aa/test/App.Metrics.Facts/Fixtures/MetricsFixture.cs#L40

**Comment by StinaSten** [comment]
okay.
Thanks for the tips.
