### ISSUE TITLE
Entity Framework and SQL profiler

### ISSUE THREAD

**Issue by michaelsogos** [AppMetrics/AppMetrics#199]
Dear,

Amazing library!!

There is possibility to measure EFCore and SQL query like miniprofiler do?

**Comment by alhardy** [comment]
Thanks, glad you like it!

Yeah I've thought about that, I think a metrics collection agent would be better for this type of job.

**Comment by michaelsogos** [comment]
I agree, the ideal could be to having a DASHBOARD about WEB RESPONSIVENESS (Apdex and around), a DASHBOARD for AUTHENTICATION (oauth and around), and a new DASHBOARD for DATA RELIABILITY (bottleneck, query N+1, worst top 10 queries, etc.)

**Comment by RagingKore** [comment]
Found this issue while trying to understand if AppMetrics provided automatic SQL profiling, just like MiniProfiler. 

AppMetrics is looking great and a couple of my colleagues and I are spiking it with Prometheus right now.

MiniProfiler implements wrappers around [IDbConnection](https://github.com/MiniProfiler/dotnet/blob/0e418c66eebbcf4ea0f2e96413d2e5932abd4a88/src/MiniProfiler.Shared/Data/SimpleProfiledConnection.cs) and it looks simple enough, so how would the metrics collection agent work compare to this?

**Comment by alhardy** [comment]
@RagingKore That approach will work, happy to have something similar in App Metrics as an option.

@michaelsogos yeah a pre-built Grafana dashboard for such SQL monitoring would be great.
