### ISSUE TITLE
UseMetricsAllEndpoints() call fails with NullReference exception

### ISSUE THREAD

**Issue by ivlevkonstantin** [AppMetrics/AppMetrics#200]
Repro steps:

1) In ConfigureServices method do:

`var metrics = AppMetrics.CreateDefaultBuilder().Build();`
`services.AddMetrics(metrics);`
`services.AddMetricsTrackingMiddleware();`

2) In Configure method do:

`app.UseMetricsAllMiddleware();`
`app.UseMetricsAllEndpoints();`

Result: in output:

> Exception thrown: 'System.ArgumentNullException' in App.Metrics.AspNetCore.Core.dll
An exception of type 'System.ArgumentNullException' occurred in App.Metrics.AspNetCore.Core.dll but was not handled in user code
Value cannot be null.

Expected result:
/metrics endpoint is available

**Comment by ivlevkonstantin** [comment]
Workaround: use BuildWebHost for registering MetricsEndpoints

`WebHost.CreateDefaultBuilder(args)`
`                ...`
`                .UseMetricsWebTracking()`
`                .UseMetricsEndpoints()`
`                .UseStartup<Startup>()`
`                ...`
`                .Build();`

**Comment by alhardy** [comment]
@ivlevkonstantin in your `ConfigureServices` method you are missing `services.AddMetricsEndpoints()` in the same way `services.AddMvc()` is required to `app.UseMvc()`.

But yes the `WebHost` extensions are there to simplify configuration and allow keeping metrics/health, being "infrastructure" concerns, out of the way from your more application specific configuration.

I've kept the `IApplicationBuilder` and `IServiceCollection` extensions there for when more control is needed, but yes this approach is more tedious as apposed to using the `WebHost` extensions.

**Comment by alhardy** [comment]
This issue was moved to AppMetrics/AspNetCore#8
