### ISSUE TITLE
Could Not Load Type IReporterProvider

### ISSUE THREAD

**Issue by Decad** [AppMetrics/AppMetrics#203]
I am attempting setup an example API that has both Health and Metrics endpoints and reporting to Elasticsearch. I have installed the following packages:

```    
<PackageReference Include="App.Metrics.AspNetCore" Version="2.0.0-alpha" />
<PackageReference Include="App.Metrics.AspNetCore.Health" Version="2.0.0-alpha" />
<PackageReference Include="App.Metrics.AspNetCore.Mvc" Version="2.0.0-alpha" />
<PackageReference Include="App.Metrics.AspNetCore.Reporting" Version="2.0.0-alpha" />
<PackageReference Include="App.Metrics.Extensions.Reporting.ElasticSearch" Version="1.1.1" />
<PackageReference Include="App.Metrics.Health" Version="2.0.0-alpha" />
<PackageReference Include="App.Metrics.Health.Checks.Http" Version="2.0.0-alpha" />
<PackageReference Include="App.Metrics.Health.Checks.Network" Version="2.0.0-alpha" />
<PackageReference Include="App.Metrics.Health.Checks.Process" Version="2.0.0-alpha" />
<PackageReference Include="App.Metrics.Reporting.Elasticsearch" Version="2.0.0-alpha" />
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
```

My Program.cs looks like this:
```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureMetricsWithDefaults(builder =>
                {
                    builder.Report.ToElasticsearch("http://localhost:9200/", "metrics");
                })
                .ConfigureAppMetricsHostingConfiguration(options =>
                {
                    options.MetricsEndpoint = "/_metrics";
                    options.MetricsTextEndpoint = "/_metricstext";
                })
                .ConfigureHealthWithDefaults(builder =>
                {
                    const int threshold = 100;
                    builder.HealthChecks.AddCheck("DatabaseConnected", () => new ValueTask<HealthCheckResult>(HealthCheckResult.Healthy("Database Connection OK")));
                    builder.HealthChecks.AddProcessPrivateMemorySizeCheck("Private Memory Size", threshold);
                    builder.HealthChecks.AddProcessVirtualMemorySizeCheck("Virtual Memory Size", threshold);
                    builder.HealthChecks.AddProcessPhysicalMemoryCheck("Working Set", threshold);
                    builder.HealthChecks.AddPingCheck("google ping", "google.com", TimeSpan.FromSeconds(10));
                    builder.HealthChecks.AddHttpGetCheck("github", new Uri("https://github.com/"), TimeSpan.FromSeconds(10));
                })
                .ConfigureAppHealthHostingConfiguration(options =>
                {
                    options.HealthEndpoint = "/_health";
                })
                .UseHealth()
                .UseStartup<Startup>()
                .Build();
    }

```
Startup.cs:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(options => options.AddMetricsResourceFilter());
            services.AddMetricsEndpoints();
            services.AddMetrics();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();
            app.UseMetricsAllEndpoints();
        }
```

It builds fine but at run time I get the following exception:

```Could not load type 'App.Metrics.Abstractions.Reporting.IReporterProvider' from assembly 'App.Metrics, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0d5193a913d1b812'```

**Comment by ivlevkonstantin** [comment]
Dear, Decad.

Please, try to use this set of dependencies:

`<PackageReference Include="App.Metrics.AspNetCore.Health" Version="2.0.0-alpha" />`
`<PackageReference Include="App.Metrics.AspNetCore.Mvc" Version="2.0.0-alpha" />`
`<PackageReference Include="App.Metrics.Health.Checks.Http" Version="2.0.0-alpha" />`
`<PackageReference Include="App.Metrics.Health.Checks.Network" Version="2.0.0-alpha" />`
`<PackageReference Include="App.Metrics.Health.Checks.Process" Version="2.0.0-alpha" />`
`<PackageReference Include="App.Metrics.Reporting.Elasticsearch" Version="2.0.0-alpha" />`
`<PackageReference Include="App.Metrics.Health.Extensions.DependencyInjection" Version="2.0.0-alpha" />`

It works for me.
Also, there could be some other similar issues. Try always to reference meta packages, which contains a set of all dependencies required by the you setup.

Hope, it helps.

--
Konstantin

**Comment by Decad** [comment]
Thanks @ivlevkonstantin thats resolved my issue.

Side note is there an obvious way to see what the 'Meta' packages are? App Metrics seems to be split across a lot of nuget packages.

**Comment by ivlevkonstantin** [comment]
> Side note is there an obvious way to see what the 'Meta' packages are?

They are sometimes mentioned in documentation. For example, please, take a look here: https://www.app-metrics.io/web-monitoring/aspnet-core/health/

> App.Metrics.AspNetCore.Health - A sort of meta package which includes App Metrics Health ASP.NET Core feature packages as well as additional
