### ISSUE TITLE
net45 support

### ISSUE THREAD

**Issue by neoned** [AppMetrics/AppMetrics#205]
@alhardy Is there a reason to not support .NET Framework lower than net452?
It would be great to have a possibility to use this library in net45 projects.

**Comment by johnduhart** [comment]
@neoned Why stopping you from upgrading to net452?

**Comment by alhardy** [comment]
@neoned no plans to support net45, @johnduhart mention upgrading, that'd be a better option considering https://github.com/Microsoft/dotnet/blob/master/releases/README.md
