### ISSUE TITLE
Counters reset each one hour

### ISSUE THREAD

**Issue by astef** [AppMetrics/AppMetrics#207]
Here's a repro for .NET Core 2.0 app with `App.Metrics 2.0.0-alpha` and `App.Metrics.AspNetCore 2.0.0-alpha` and manually connected `App.Metrics.Formatters.Prometheus` with this fix https://github.com/AppMetrics/Prometheus/issues/20

```csharp
using System.Threading.Tasks;
using App.Metrics;
using App.Metrics.Formatters.Prometheus;
using App.Metrics.ReservoirSampling.ExponentialDecay;
using App.Metrics.Timer;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;

class Startup : StartupBase
{
    public static TimerOptions TestFreakinResets { get; set; } = NewDefaultTimer(nameof(TestFreakinResets));

    public static IWebHost BuildWebHost(string[] args)
    {
        return WebHost.CreateDefaultBuilder(args)
            .ConfigureServices(sc =>
            {
                var mb = AppMetrics.CreateDefaultBuilder();
                mb.OutputMetrics.AsPrometheusPlainText();
                mb.OutputMetrics.AsPrometheusProtobuf();
                var metrics = mb.Build();
                sc.AddMetrics(metrics);
                sc.AddMetricsEndpoints(o =>
                {
                    o.MetricsTextEndpointOutputFormatter = new MetricsPrometheusTextOutputFormatter(new MetricsPrometheusOptions
                    {
                        NewLineFormat = NewLineFormat.Unix
                    });
                });
            })
            .UseStartup<Startup>()
            .Build();
    }

    public static void Main(string[] args) { BuildWebHost(args).Run(); }

    internal static TimerOptions NewDefaultTimer(string name)
    {
        return new TimerOptions
        {
            Name = name,
            MeasurementUnit = Unit.Items,
            DurationUnit = TimeUnit.Milliseconds,
            RateUnit = TimeUnit.Seconds,
            Reservoir = () => new DefaultForwardDecayingReservoir()
        };
    }

    public override void Configure(IApplicationBuilder app)
    {
        var m = app.ApplicationServices.GetRequiredService<IMetrics>();
        Task.Factory.StartNew(() =>
        {
            while (true)
                m.Measure.Timer.Time(TestFreakinResets, () => { Task.Delay(600).Wait(); });
        }, TaskCreationOptions.LongRunning);
        app.UseMetricsTextEndpoint();
        app.UseEnvInfoEndpoint();
    }
}
```

If you run it and left for an hour or so, you'll see that `application_testfreakinresets_count` metrics resets. I am able to reproduce this in different applications and environments. 

Is it an expected behaviour or a bug? Any workaround?

I see annoying data artifacts in grafana even after applying prometheus `rate` function which [handles counter resets](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate).

**Comment by astef** [comment]
I've found this place. It's `DefaultReservoirRescaleScheduler` who is calling `Rescale` on `DefaultForwardDecayingReservoir`. I don't know what's the idea behind this rescaling.

@alhardy can you confirm that there's a bug or counters reset is expected?

**Comment by astef** [comment]
I can report I found a bug. It's one liner, I'll prepare pull request in an hour

**Comment by alhardy** [comment]
@astef rescaling is done on a single background thread, it's is required to sample histogram data, see [reservoir sampling](https://www.app-metrics.io/getting-started/reservoir-sampling/) in the docs for details.

**Comment by astef** [comment]
It happens to be an issue with Prometheus reporting. It fixed in https://github.com/AppMetrics/Prometheus/pull/24 and this issue can be closed

**Comment by Spaniol** [comment]
Seems like issue is reproducible again with app metrics 3.1.0 and Prometheus reporter 3.1.0 in .NET Core 2,2 app. Histograms are reset each hour
