### ISSUE TITLE
Counter with history

### ISSUE THREAD

**Issue by kripergvg** [AppMetrics/AppMetrics#210]
I want to use counter, but he does not save history. Is there some feature where I can type 
`SomeCounter.Increment()`
and this counter would save state while app is running? I know about gauge, but he only has `SetValue()` not like increment decrement.

**Comment by kripergvg** [comment]
But he doesn't show history. Am I right?

**Comment by alhardy** [comment]
show history? The value is incremented in memory, unless you have left the default which is to reset the counter when reporting
