### ISSUE TITLE
Regarding Sharepoint monitoring with appmetrics

### ISSUE THREAD

**Issue by abhay40711cs** [AppMetrics/AppMetrics#211]
While installing package "App.metrics.AspNetCore.Tracking" for SharePoint solution, it gives error as it is not compatible.
My intent is to use grafana dashboard by the exposed /metrics on Prometheus.

I am having SharePoint solution, can you please suggest is it an enhancement or I am doing something wrong here?

Regards,
Abhay

**Comment by alhardy** [comment]
I'm assuming by "not compatible" you mean your Sharepoint solution isn't compatible with asp.net core? I have no plans to support anything Sharepoint.
