### ISSUE TITLE
Version 1.3.0 is crashing with WebAPI2

### ISSUE THREAD

**Issue by dragosboia** [AppMetrics/AppMetrics#213]
Using version 1.3.0 is crashing when trying to report to influx DB in a web api app, the same code working fine with a console app, stack trace bellow:

"

Thread ID | Exception Type | Message | Stack Trace | Remote Stack Trace
-- | -- | -- | -- | --
38 | System.InvalidOperationException | values keys cannot contains empty or whitespace strings | App.Metrics.Tagging.MetricTags..ctor(System.String[], System.String[])    App.Metrics.Tagging.MetricTags.Concat(App.Metrics.Tagging.MetricTags, System.Collections.Generic.Dictionary`2)    App.Metrics.Registry.Internal.DefaultMetricContextRegistry+<>c__DisplayClass18_0`1[[System.__Canon, mscorlib]].b__0()    App.Metrics.Registry.Internal.DefaultMetricContextRegistry+MetricMetaCatalog`3+<>c__DisplayClass4_0[[System.__Canon, mscorlib],[System.__Canon, mscorlib],[App.Metrics.Counter.CounterValue, App.Metrics]].b__0(System.String)    System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, mscorlib],[System.__Canon, mscorlib]].GetOrAdd(System.__Canon, System.Func`2)    App.Metrics.Registry.Internal.DefaultMetricContextRegistry+MetricMetaCatalog`3[[System.__Canon, mscorlib],[System.__Canon, mscorlib],[App.Metrics.Counter.CounterValue, App.Metrics]].GetOrAdd(System.String, System.Func`1>)    App.Metrics.Counter.DefaultCounterManager.Increment(App.Metrics.Core.Options.CounterOptions, System.String)    App.Metrics.Reporting.Internal.Reporter+<>c__DisplayClass12_0+<b__0>d.MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)    System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)    System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()    System.Threading.ThreadPoolWorkQueue.Dispatch()
"

And my settings code is "

 var assemblyName = Assembly.GetExecutingAssembly().GetName();
            services
                .AddMetrics(options =>
                {
                    options.DefaultContextLabel = environmentName;
                    options.GlobalTags.Add("env", environmentType);
                    options.MetricsEnabled = true;
                    options.ReportingEnabled = true;
                }, assemblyName)

                .AddReporting(factory =>
                {
                    factory.AddInfluxDb(new InfluxDBReporterSettings
                    {
                        HttpPolicy = new HttpPolicy
                        {
                            FailuresBeforeBackoff = 3,
                            BackoffPeriod = TimeSpan.FromSeconds(10),
                            Timeout = TimeSpan.FromSeconds(3)
                        },
                        InfluxDbSettings = new InfluxDBSettings(databaseName, new Uri($"http://{serverAddress}:8086")),
                        ReportInterval = TimeSpan.FromSeconds(5)
                    });
                });
"

Thanks,
Dragos

**Comment by alhardy** [comment]
What's the value of `environmentType` in your example?

**Comment by dragosboia** [comment]
environmentType= "Production"

**Comment by dragosboia** [comment]
Found the issue, it's a bug if you don't specify app and server global tags will crash( still without them are working in a console app). So the fix was 
![image](https://user-images.githubusercontent.com/11757080/34363851-745230b0-ea34-11e7-92d3-0a05de103c1d.png)
