### ISSUE TITLE
Influx SSL not working

### ISSUE THREAD

**Issue by mts57017** [AppMetrics/AppMetrics#214]
i am running a .NET Core 2 API....
here is the config....
 
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args).ConfigureMetricsWithDefaults(builder =>
                {
                    builder.Configuration.Configure(options =>
                    {
                        options.DefaultContextLabel = "Data Load API";
                        options.GlobalTags.Add("test tag", "test value");
                        options.Enabled = true;
                        options.ReportingEnabled = true;
                    }).Report.ToInfluxDb(options =>
                    {
                        options.InfluxDb.BaseUri = new Uri("https://<SERVER WITH IP>");
                        options.InfluxDb.Database = "<DB>";
                        options.InfluxDb.UserName = "<USER>";
                        options.InfluxDb.Password = "<PW>";
                        options.HttpPolicy.BackoffPeriod = TimeSpan.FromSeconds(30);
                        options.HttpPolicy.FailuresBeforeBackoff = 5;
                        options.HttpPolicy.Timeout = TimeSpan.FromSeconds(10);
                        options.MetricsOutputFormatter = new MetricsJsonOutputFormatter();
                        options.FlushInterval = TimeSpan.FromSeconds(20);
                    });
                }).UseMetrics().UseHealthEndpoints()
                .UseStartup<Startup>()
                .Build();
    }

the above returns the following....

   "context": "appmetrics.internal",
      "apdexScores": [],
      "counters": [
        {
          "name": "report_failed",
          "unit": "items",
          "count": 13,
          "items": [
            {
              "count": 13,
              "item": "App.Metrics.Reporting.InfluxDB.InfluxDbMetricsReporter",
              "percent": 100.0
            }
          ],
          "tags": {
            "server": "abb2533aac4e",
            "app": "DataCacheAPI",
            "env": "development",
            "test tag": "test value"
          }
        }
      ],

any ideas as to what is causing this?

**Comment by alhardy** [comment]
off the top of my head no, I'll have to dig in

**Comment by alhardy** [comment]
This issue was moved to AppMetrics/InfluxDB#24
