### ISSUE TITLE
Deprecated References 

### ISSUE THREAD

**Issue by andrewspiteri** [AppMetrics/AppMetrics#215]
Currently the 'alpha' nuget is using NetStandard Library. This was deprecated by Microsoft. 

see: https://www.nuget.org/packages/NETStandard.Library.NETFramework/

Since this is a preview package it will not allow to promote the nuget from alpha. 

Finally as a generic question, has the original author lost interest in this project?

**Comment by alhardy** [comment]
@andrewspiteri thanks, I believe I've resolved that in the dev branch.

Definitely haven't lost interest in the project, just been flat out family and work wise in a new role the past couple of months.

**Comment by andrewspiteri** [comment]
I'm using your project in one of our core nugets internally. For now to go around it as, I copy pasted your source files into our project. I have no references and it worked out of the box.

We are using .net 4.7.1

If you wish to work full time on this, I would hire you. 

The only catch is that you would need to move to Malta -> https://en.wikipedia.org/wiki/Malta

**Comment by alhardy** [comment]
You could grab the Dev packages from myget https://www.myget.org/feed/Packages/appmetrics

Thanks for that, wouldn't be possible at this point in time

**Comment by pshrosbree** [comment]
Here is hoping you get time to get your refactoring into master!
:)

**Comment by alhardy** [comment]
I will ;)

**Comment by alhardy** [comment]
Fix for next release - https://github.com/AppMetrics/AppMetrics/commit/6c9fd6a7440e911bb8366e7e623cb093d24d2f89
