### ISSUE TITLE
http reporter not working (.NET CORE 2.0 web api)

### ISSUE THREAD

**Issue by mts57017** [AppMetrics/AppMetrics#216]
is there something special i need to do to post json from app metrics to api endpoint? i am getting http error 415 for all requests

**Comment by mts57017** [comment]
so i figured out what is going on....it looks like when app metrics is outputting to then endpoint, it is not in a format that can be picked up by the api. so if i use a stream reader, readtoendasync, i can see the data from the origin, like i am supposed too.

is this a .net core issue? something else?

**Comment by alhardy** [comment]
Do you have a code snippet?

**Comment by mts57017** [comment]
yeah let me get it

**Comment by mts57017** [comment]
![image](https://user-images.githubusercontent.com/29133739/35277631-090bad2e-000d-11e8-9bfc-cecc6e4de50a.png)

**Comment by mts57017** [comment]
this is how i have to capture now

![image](https://user-images.githubusercontent.com/29133739/35277683-2ef43ca4-000d-11e8-88af-e6c2fcf32580.png)

**Comment by alhardy** [comment]
This issue was moved to AppMetrics/Reporting#40
