### ISSUE TITLE
Is it possible to use with PerformanceCounter?

### ISSUE THREAD

**Issue by darting** [AppMetrics/AppMetrics#218]
Is it possible? Thanks.

**Comment by alhardy** [comment]
You would have to target .NET Full Framework as Performance Counters aren't supported in dotnet core. The future of Performance Counters is EventCounters, it is on my backlog to investigate this but that won't be any time soon.

In the mean time it shouldn't be too hard to write your own code to read the Performance Counters you're interested in and record with App Metrics.

**Comment by darting** [comment]
@alhardy 

Is this Performance Counters supported in dotnet core? I will try to write some testing.

**Comment by alhardy** [comment]
@darting did you end up building anything perf counter related?

This would be a separate assembly as it's windows specific.

**Comment by alhardy** [comment]
Don't  want to maintain a perf counter extension :(
