### ISSUE TITLE
Using App.Metrics in a library

### ISSUE THREAD

**Issue by Jericho** [AppMetrics/AppMetrics#219]
I am writing a library that performs some lengthy operation and I would like to be able to capture and report how long this operation takes. Does it make sense for my library to take a dependency on App.Metrics and to have a `IMetricsBuilder` parameter on my constructor which would allow developers to inject the builder of their choice?

What I have in mind would be something like this:

```csharp
public class Foo
{
    private readonly IMetricsRoot _metrics;

    public Foo(IMetricsBuilder metricsBuilder)
    {
        _metrics = metricsBuilder.Build();
    }

    public void Bar()
    {
        using (_metrics.Measure.Timer.Time(MyMetrics.MyTimer))
        {
           //  ... some lengthy operation ...
        }
    }
}
```

Any thoughts on my approach?

**Comment by alhardy** [comment]
Why do you need a custom `IMetricsBuilder`?

**Comment by Jericho** [comment]
I want to make sure developers can configure metrics capturing/reporting. e.g.: report to InfluxDB, report to a flat file, etc.

Is there a better way?

**Comment by Jericho** [comment]
Would it be better for my constructor to accept `IMetricsRoot` instead of `IMetricsBuilder`?

Something like this:

```csharp
public class Foo
{
    private readonly IMetricsRoot _metrics;

    public Foo(IMetricsRoot metrics)
    {
        _metrics = metrics;
    }

    public void Bar()
    {
        using (_metrics.Measure.Timer.Time(MyMetrics.MyTimer))
        {
           //  ... some lengthy operation ...
        }
    }
}
```

**Comment by alhardy** [comment]
The latter approach is better, well really you just need `IMetrics`.

Reporters are configured on startup see the [docs](https://www.app-metrics.io/reporting/reporters/).

You can also use the [sample projects](https://www.app-metrics.io/samples/metrics-code/) as a reference.
