### ISSUE TITLE
System.Runtime

### ISSUE THREAD

**Issue by JustasKazanavicius** [AppMetrics/AppMetrics#224]
Get an exception when using new version of System.Runtime

System.IO.FileLoadException : Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by alhardy** [comment]
Odd the [sample projects](https://github.com/AppMetrics/Samples.V2) have been updated to use the latest runtime.

![image](https://user-images.githubusercontent.com/729185/36032218-66e5d922-0e01-11e8-82af-93c7dbde8b9f.png)

**Comment by JustasKazanavicius** [comment]
It is a conflict between System.Threading.Tasks.Extensions which use System.Runtime 4.1.2.0 and App.Metrics. I don't know how, but if I install System.Threading.Tasks.Extensions 4.4.0 version, when solution use System.Runtime 4.1.2.0 version from my computer instead of 4.1.1.0 from Nuget

**Comment by alhardy** [comment]
What version of the .net framework are you on? App Metrics doesn't have any explicit references like that

**Comment by JustasKazanavicius** [comment]
I use 4.7 framework versions. System.Threading.Tasks.Extensions is used by other Nugget library.

**Comment by alhardy** [comment]
@JustasKazanavicius  did you find the issue here?

**Comment by JustasKazanavicius** [comment]
I use older version (4.3.0) of System.Threading.Tasks.Extensions . If I use new version (4.4.0) of System.Threading.Tasks.Extensions visual studio use different version of System.Runtime which not suitable for App.Metrics

**Comment by alhardy** [comment]
Hmm, I'm not sure how as AppMetrics 2.0.0- * is only referencing .net standard 1.6.1, see it's dependancies here https://www.nuget.org/packages/NETStandard.Library/1.6.1

**Comment by JustasKazanavicius** [comment]
​
 20180328_144108.mp4
<https://drive.google.com/file/d/1gKMQ2E0KTh6qQdMVl9HvXkXS6eGrp9X4/view?usp=drive_web>
​

Pagarbiai/Best Regards

Justas Kazanavičius

**Comment by alhardy** [comment]
Should be fixed with dependency clean up changes and multi-targetting now
