### ISSUE TITLE
Possible to prevent measurements with 0 value not to be flushed out when running scheduler

### ISSUE THREAD

**Issue by EdChavez** [AppMetrics/AppMetrics#226]
Hi,

Is it possible to have App Metrics Reporting not flush out measurements if nothing was measured during an interval. For instance, I have scheduler that runs every 1 minutes. The application may not measure anything for many minutes however there will be a measurements flushed out to InfuxDB every minute regardless if nothing was measured (with counter value 0). Is there a configuration setting to prevent this? If not, can this feature be considered?

**Comment by alhardy** [comment]
There is currently no such configuration setting. Question, what we be expected if a counter is at some stage decremented to 0?

**Comment by EdChavez** [comment]
Hi. My use cases only use counter.increment and timer.time. Didn't think about decrementing at all. I would say in the decrement to 0 scenario, the same, don't flush out 0 value to the Reporting DB. If another decrement occurs then flush out -1 value. Making the http call and writing to Influx DB these 0 value points uses extra resources and the data doesn't provide any additional value. Unordered time series can be turned into ordered by filling the gaps (i.e. tools like grafana does this). I'm not sure if there are other use cases like decrement that makes this tricky.

**Comment by alhardy** [comment]
I'm just thinking that maybe there shouldn't be any special logic around 0 values, re the point of using extra storage for example, the same would apply for any greater values which are constant for periods of time.

I'll think a bit more on this

**Comment by reisenberger** [comment]
>there shouldn't be any special logic around 0 values

+1 to this.  What if that metric represents how much of something remains?  Decrementing to zero would be a very important case.

**Comment by EdChavez** [comment]
Hi see your points and see how my proposed feature breakdowns in more complicated scenarios. My use case is simple - I reset the counters after every report flush.  Yes, my concern is about resource usage for a special case where (value=0) doesn't need to be recorded. Thanks for giving this some thought.

**Comment by alhardy** [comment]
@EdChavez I think 0 should still be reported, even if a metric is 0 most of the time.

Re storage concerns, AppMetrics supports various filtering capabilities when reporting, that'd be your best bet with storage related concerns. I can't think of a case where one would have many many metrics which are constantly reporting 0, if that is the case, those metrics probably aren't event worth reporting.
