### ISSUE TITLE
Provide ability to set Configuration for  ConfigurationBuilder()

### ISSUE THREAD

**Issue by dkutetsky** [AppMetrics/AppMetrics#227]
In the documentation, I could find how to configure health options using the extension method **.ConfigureAppHealthHostingConfiguration** for **WebHost.CreateDefaultBuilder(args)**.
Also, it should be available configuration health endpoint from appsetting.json.

But I am using  **IConfgirationBuilder** for configuring my asp.net application.

**var builder = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory())**

So, I can not change health status endpoint or any other options in Program/Startup or using appsettings.json.
Seems it should be a way to change this config for IConfgirationBuilder (additionally to configuring using IWebHostBuilder).

I am using NuGet packages v.2.0.0-preview1 (Health, Health.Core, Health.Endpoints, Health.Hosting, etc.)

**Comment by dkutetsky** [comment]
I checked this method  (appsettings.json + .UseHealth() in Program.cs) and it works, thanks.

Sorry, seems I confused you a little bit with issue naming.
To be correct, I need to override health check url (let's say use "/health_check" instead of "/health").
Not sure that it possible, because using config I could only enable/disable health endpoint.

Please see my code below:

_Program.cs:_
no modifications

Startup.cs
 ```
public void ConfigureServices(IServiceCollection services)
{
...
var metrics = AppMetricsHealth.CreateDefaultBuilder()            
                .HealthChecks.RegisterFromAssembly(services)              
                .Build();

services.AddHealth(metrics);
services.AddHealthEndpoints();
...

}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
   ...
   app.UseHealthEndpoint();
   ...
}
```

**Comment by alhardy** [comment]
Ah, yes at the moment there's not an option to set a custom route for the health check. Happy to add that in.

**Comment by alhardy** [comment]
Sorry my bad, it is possible, one way is to use a `IConfigureOptions` e.g.

```
 public class ConfigureHealthHostingOptions : IConfigureOptions<HealthEndpointsHostingOptions>
    {
        public void Configure(HealthEndpointsHostingOptions options) { options.HealthEndpoint = "/health_check"; }
    }
```

and register on the `IServiceCollection`

```
services.TryAddEnumerable(ServiceDescriptor.Singleton<IConfigureOptions<HealthEndpointsHostingOptions>, ConfigureHealthHostingOptions>());
```

another is using the `IWebHostBuilder` extensions, see the sandox project in the [AspNetCoreHealth](https://github.com/AppMetrics/AspNetCoreHealth/blob/dev/sandbox/HealthSandboxMvc/Host.cs#L31) repo.

If it's preferred to configure using `IApplicationBuilder`, the `IConfigureOptions` approach mentioned above should also work.

**Comment by dkutetsky** [comment]
Many thanks for the helping,
Way `services.TryAddEnumerable` works well for me, also, configuring in Program.cs with `webHostBuilder.ConfigureAppHealthHostingConfiguration() `works well.
I believe it will be helpful to add this to documentation - if you don't mind I could do this.

Not sure that understand proposed way to configure it using IApplicationBuilder:
as I see now, there are 3 ways how to configure url for health check:
 1. in Program.cs - from appsettings.json and using `webHostBuilder.UseHealth()`
 2. in Program.cs  - using `webHostBuilder.ConfigureAppHealthHostingConfiguration()`
 3. in Startup.cs/ConfigureServices() - using mentioned `services.TryAddEnumerable`

About IApplicationBuilder - as I read, you could do following,
but there are no arguments that I could pass to UseHealthEndpoint() extension method:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
            app.UseHealthEndpoint();
}
```

Did I miss something? Thanks again - for me two approaches work well.

**Comment by alhardy** [comment]
More than happy for any contributions go ahead, at the moment this is what I have around changing health endpoint configuration https://www.app-metrics.io/web-monitoring/aspnet-core/health/#hosting-configuration.

The proposed way to configure the endpoint when using the `IApplicationBuilder` extension not would be point 3, however yes the extension method could take `IConfigrationSection` as an optional parameter. Let's leave this ticket open for now
