### ISSUE TITLE
Could not load type 'App.Metrics.Reporting.Abstractions.IReportFactory' from assembly 'App.Metrics, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0d5193a913d1b812'

### ISSUE THREAD

**Issue by kongkong56** [AppMetrics/AppMetrics#228]
public void Configure(IApplicationBuilder app, IHostingEnvironment env, IApplicationLifetime lifetime)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMetricsReporting(lifetime);
}

error:
System.TypeLoadException:“Could not load type 'App.Metrics.Reporting.Abstractions.IReportFactory' from assembly 'App.Metrics, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0d5193a913d1b812'.”

**Comment by alhardy** [comment]
What are your projects dependencies and what version of .net are you using?

**Comment by alhardy** [comment]
Closing this due to no response, cannot replicate and no other related issues have been reported.
