### ISSUE TITLE
Telegraph Reporter

### ISSUE THREAD

**Issue by alhardy** [AppMetrics/AppMetrics#230]
Request: https://github.com/AppMetrics/InfluxDB/issues/17

**Comment by gickis** [comment]
Currently I'm using InfluxDB reporter on AppMetrics side and "HTTP Listener" input on Telegraf side. It's working like a charm. You can verify this input by this link https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_listener

**Comment by alhardy** [comment]
Ah cool, yes I added the HTTP reporter as a generic approach for this type of usage as I think the same approach can be used with elastic search via either beats or logstash.

For those wanting to use UDP instead of HTTP I guess a similar approach can be taken as this rather than building for direct to telegraf, thoughts?

Related question, do you have any performance concerns given AppMetrics samples/aggregates in process and would you find it useful to be able to send raw values instead?

Thanks for sharing!

**Comment by alhardy** [comment]
Would also be awesome if you could add some details to this telegraf approach in the documentation ;)

https://www.app-metrics.io/reporting/reporters/

**Comment by gickis** [comment]
I'll create pull request for documentation with example how to use Telegraf as InfluxDB relay later.

**Comment by alhardy** [comment]
@Alessar Thanks for your contrib! Any chance you add some documentation? https://github.com/AppMetrics/Docs.V2.Hugo/issues/27

**Comment by Alessar** [comment]
@alhardy Could You please review documentation at https://github.com/AppMetrics/Docs.V2.Hugo/pull/30 ?
