### ISSUE TITLE
how to metric so many microservices?

### ISSUE THREAD

**Issue by kongkong56** [AppMetrics/AppMetrics#232]
in microservices,how to metric counter,timer.etc

**Comment by alhardy** [comment]
No sure what your question is unfortunately?

**Comment by kongkong56** [comment]
In microservices, how to integrate appmetrics into a project and measure the health metrics of all interfaces of each microservice

**Comment by alhardy** [comment]
That's a very broad question. In terms of integration maybe start with referring to the documentation  https://www.app-metrics.io/web-monitoring/
