### ISSUE TITLE
Deserialize json to class?

### ISSUE THREAD

**Issue by mts57017** [AppMetrics/AppMetrics#236]
Does app metrics have a class to deserialize the app metric json coming into an http endpoint?

Example: JsonConvert.DeserializeObject<**APP METRICS CLASS**>(app metric json)

**Comment by alhardy** [comment]
Try https://github.com/AppMetrics/AppMetrics/blob/dev/src/App.Metrics.Formatters.Json/Converters/MetricDataConverter.cs

**Comment by mts57017** [comment]
thanks!

**Comment by alhardy** [comment]
It's not tested though, don't have a use case for it right now ;)

**Comment by mts57017** [comment]
no worries. i tested it it, and so far so good. I have app metrics reporting via http method. the api that it sends it to, accepts frombody MetricData, which works successfully. i do some additional processing before i kick it to influx.
