### ISSUE TITLE
Creating my own tags

### ISSUE THREAD

**Issue by JuniorCtba** [AppMetrics/AppMetrics#239]
i need to create some tag for specific logs, how can i do that? should i use like that https://www.app-metrics.io/getting-started/metric-types/ ?

var processPhysicalMemoryGauge = new GaugeOptions
{
Name = "Process Physical Memory",
MeasurementUnit = Unit.Bytes
}

var process = Process.GetCurrentProcess();

_metrics.Measure.Gauge.SetValue(MetricsRegistry.Gauges.TestGauge, process.WorkingSet64);

There is an easy way to configure that?

**Comment by alhardy** [comment]
Have you looked at the docs on tagging? https://www.app-metrics.io/getting-started/fundamentals/tagging-organizing/
