### ISSUE TITLE
App.Metrics adds lots of dependencies in .Net framework projects

### ISSUE THREAD

**Issue by Symbianx** [AppMetrics/AppMetrics#245]
Hello, first of all thank you for the work you've put into this project.
We are trying to adopt App.Metrics in our services but we are having issues with the amount of dependencies it brings into the project. 

I think this is due to the fact that the packages App.Metrics.Abstractions and App.Metrics.Concurrency target only the **.NetStandard 1.1**. 

Adding the **.Net Framework 4.5** target would remove the need for the NETStandard.Library dependency on framework projects thus removing most of the referenced packages.

The following is the list of packages installed by Visual Studio on a .Net 4.6.1 project with the **App.Metrics** package.
```
Microsoft.CSharp.4.4.1
Microsoft.NETCore.Platforms.1.1.0
Microsoft.Win32.Primitives.4.3.0
System.App.Context.4.3.0
System.Collections.4.3.0
System.Collections.Concurrent.4.3.0
System.Console.4.3.0
System.Diagnostics.Debug.4.3.0
System.Diagnostics.DiagnosticSource.4.3.0
System.Diagnostics.Tools.4.3.0
System.Diagnostics.Tracing.4.3.0
System.Globalization.4.3.0
System.Globalization.Calendars.4.3.0
System.IO.4.3.0
System.IO.Compression.4.3.0
System.IO.Compression.ZipFile.4.3.0
System.IO.FileSystem.Primitives.4.3.0
System.IO.FileSystem.4.3.0
System.Linq.4.3.0
System.Linq.Expressions.4.3.0
System.Net.Primitives.4.3.0
System.Net.Sockets.4.3.0
System.ObjectModel.4.3.0
System.Reflection.4.3.0
System.Reflection.Extensions.4.3.0
System.Reflection.Primitives.4.3.0
System.Resources.ResourceManager.4.3.0
System.Runtime.4.3.0
System.Runtime.Extensions.4.3.0
System.Runtime.Handles.4.3.0
System.Runtime.InteropServices.4.3.0
System.Runtime.Numerics.4.3.0
System.Security.Cryptography.Encoding.4.3.0
System.Security.Cryptography.Primitives.4.3.0
System.Security.Cryptography.Algorithms.4.3.0
System.Security.Cryptography.X509Certificates.4.3.0
System.Net.Http.4.3.0
System.Text.Encoding.4.3.0
System.Text.Encoding.Extensions.4.3.0
System.Text.RegularExpressions.4.3.0
System.Threading.4.3.0
System.Threading.Tasks.4.3.0
System.Threading.Timer.4.3.0
System.Xml.ReaderWriter.4.3.0
System.Xml.XDocument.4.3.0
NETStandard.Library.1.6.1
App.Metrics.Abstractions.2.0.0
App.Metrics.Concurrency.2.0.0
App.Metrics.Formatters.Ascii.2.0.0
App.Metrics.Core.2.0.0
App.Metrics.Formatters.Json.2.0.0
App.Metrics.2.0.0
```

**Comment by alhardy** [comment]
No problem, hopefully you find it useful.

Multi-targeting is an approach, that does then require me to add a bunch of #if preprocessor directives around framework specific code, not fun.

If you `dotnet publish` your app do you see the assemblies in the output artifact?

**Comment by Symbianx** [comment]
Actually, you won't need any preprocessor directives, since you already target netstandard1.1 all of the APIs are also available in .NET 4.5. 
I've changed to multi-targeting locally, ran your test suite and all of the tests succeeded.
If this change is something you are okay with, I can open a pull request.

I can't `dotnet publish` because we are still using the old .csproj format in our .NET framework projects. In fact, because of the old format we end up with a `packages.config` filled with dependencies.
To clarify, we are reluctant to long lists of dependencies because our solution has many dependencies and in the past we've had problems with libraries requiring different versions of the same dependency.

**Comment by alhardy** [comment]
Ah yes :)

> Actually, you won't need any preprocessor directives, since you already target netstandard1.1 all of the APIs are also available in .NET 4.5.

Cool, yeah open a PR.

Cheers

**Comment by Symbianx** [comment]
PR #248 opened.

**Comment by Symbianx** [comment]
After taking another look at the nuget dependencies, came to the conclusion that 
 https://github.com/AppMetrics/Concurrency has the same problem, will you accept a PR for the same thing on that project as well?

**Comment by alhardy** [comment]
I thought one of the reasons for netstandard was to avoid having to multi-target frameworks? :(

**Comment by Symbianx** [comment]
Yes, and it does, but unfortunately the old style projects don't deal so well with child dependencies :(

**Comment by alhardy** [comment]
Happy for a PR. One thing, can we target net45 conditionally, i.e. only when running on windows

**Comment by alhardy** [comment]
Mult-targetted on all appropriate packages
