### ISSUE TITLE
When installing app.metrics (latest stable 2.0.0) receive an error "Install failed. Rolling back..."

### ISSUE THREAD

**Issue by idormenco** [AppMetrics/AppMetrics#247]
Error that triggers rollback is: 'System.Collections' which was not found in the GAC.

Attempting to gather dependency information for package 'App.Metrics.2.0.0' with respect to project 'Metrix', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 18.6 sec
Attempting to resolve dependencies for package 'App.Metrics.2.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'App.Metrics.2.0.0'
Resolved actions to install package 'App.Metrics.2.0.0'
Retrieving package 'Microsoft.NETCore.Platforms 1.1.0' from 'nuget.org'.
Retrieving package 'NETStandard.Library 1.6.1' from 'nuget.org'.
Retrieving package 'App.Metrics.Abstractions 2.0.0' from 'nuget.org'.
Retrieving package 'App.Metrics.Concurrency 2.0.0' from 'nuget.org'.
Retrieving package 'App.Metrics.Formatters.Ascii 2.0.0' from 'nuget.org'.
Retrieving package 'App.Metrics.Core 2.0.0' from 'nuget.org'.
Retrieving package 'App.Metrics.Formatters.Json 2.0.0' from 'nuget.org'.
Retrieving package 'App.Metrics 2.0.0' from 'nuget.org'.
Retrieving package 'System.Collections 4.3.0' from 'nuget.org'.
Retrieving package 'System.Collections.Concurrent 4.3.0' from 'nuget.org'.
Retrieving package 'System.Diagnostics.Debug 4.3.0' from 'nuget.org'.
Retrieving package 'System.Diagnostics.Tools 4.3.0' from 'nuget.org'.
Retrieving package 'System.Diagnostics.Tracing 4.3.0' from 'nuget.org'.
Retrieving package 'System.Globalization 4.3.0' from 'nuget.org'.
Retrieving package 'System.IO 4.3.0' from 'nuget.org'.
Retrieving package 'System.IO.Compression 4.3.0' from 'nuget.org'.
Retrieving package 'System.Linq 4.3.0' from 'nuget.org'.
Retrieving package 'System.Linq.Expressions 4.3.0' from 'nuget.org'.
Retrieving package 'System.Net.Http 4.3.0' from 'nuget.org'.
Retrieving package 'System.Net.Primitives 4.3.0' from 'nuget.org'.
Retrieving package 'System.ObjectModel 4.3.0' from 'nuget.org'.
Retrieving package 'System.Reflection 4.3.0' from 'nuget.org'.
Retrieving package 'System.Reflection.Extensions 4.3.0' from 'nuget.org'.
Retrieving package 'System.Reflection.Primitives 4.3.0' from 'nuget.org'.
Retrieving package 'System.Resources.ResourceManager 4.3.0' from 'nuget.org'.
Retrieving package 'System.Runtime 4.3.0' from 'nuget.org'.
Retrieving package 'System.Runtime.Extensions 4.3.0' from 'nuget.org'.
Retrieving package 'System.Runtime.InteropServices 4.3.0' from 'nuget.org'.
Retrieving package 'System.Runtime.InteropServices.RuntimeInformation 4.3.0' from 'nuget.org'.
Retrieving package 'System.Runtime.Numerics 4.3.0' from 'nuget.org'.
Retrieving package 'System.Text.Encoding 4.3.0' from 'nuget.org'.
Retrieving package 'System.Text.Encoding.Extensions 4.3.0' from 'nuget.org'.
Retrieving package 'System.Text.RegularExpressions 4.3.0' from 'nuget.org'.
Retrieving package 'System.Threading 4.3.0' from 'nuget.org'.
Retrieving package 'System.Threading.Tasks 4.3.0' from 'nuget.org'.
Retrieving package 'System.Threading.Timer 4.3.0' from 'nuget.org'.
Retrieving package 'System.Xml.ReaderWriter 4.3.0' from 'nuget.org'.
Retrieving package 'System.Xml.XDocument 4.3.0' from 'nuget.org'.
Retrieving package 'Microsoft.CSharp 4.4.1' from 'nuget.org'.
Retrieving package 'Newtonsoft.Json 10.0.3' from 'nuget.org'.
Adding package 'Microsoft.CSharp.4.4.1' to folder 'D:\Metrix\packages'
Added package 'Microsoft.CSharp.4.4.1' to folder 'D:\Metrix\packages'
Added package 'Microsoft.CSharp.4.4.1' to 'packages.config'
Successfully installed 'Microsoft.CSharp 4.4.1' to Metrix
Adding package 'Microsoft.NETCore.Platforms.1.1.0' to folder 'D:\Metrix\packages'
Added package 'Microsoft.NETCore.Platforms.1.1.0' to folder 'D:\Metrix\packages'
Added package 'Microsoft.NETCore.Platforms.1.1.0' to 'packages.config'
Successfully installed 'Microsoft.NETCore.Platforms 1.1.0' to Metrix
Adding package 'Newtonsoft.Json.10.0.3' to folder 'D:\Metrix\packages'
Added package 'Newtonsoft.Json.10.0.3' to folder 'D:\Metrix\packages'
Added package 'Newtonsoft.Json.10.0.3' to 'packages.config'
Executing script file 'D:\Metrix\packages\Newtonsoft.Json.10.0.3\tools\install.ps1'...
Successfully installed 'Newtonsoft.Json 10.0.3' to Metrix
Adding package 'System.Collections.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Collections.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Collections.4.3.0' to 'packages.config'
Successfully installed 'System.Collections 4.3.0' to Metrix
Adding package 'System.Collections.Concurrent.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Collections.Concurrent.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Collections.Concurrent.4.3.0' to 'packages.config'
Successfully installed 'System.Collections.Concurrent 4.3.0' to Metrix
Adding package 'System.Diagnostics.Debug.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Diagnostics.Debug.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Diagnostics.Debug.4.3.0' to 'packages.config'
Successfully installed 'System.Diagnostics.Debug 4.3.0' to Metrix
Adding package 'System.Diagnostics.Tools.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Diagnostics.Tools.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Diagnostics.Tools.4.3.0' to 'packages.config'
Successfully installed 'System.Diagnostics.Tools 4.3.0' to Metrix
Adding package 'System.Diagnostics.Tracing.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Diagnostics.Tracing.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Diagnostics.Tracing.4.3.0' to 'packages.config'
Successfully installed 'System.Diagnostics.Tracing 4.3.0' to Metrix
Adding package 'System.Globalization.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Globalization.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Globalization.4.3.0' to 'packages.config'
Successfully installed 'System.Globalization 4.3.0' to Metrix
Adding package 'System.IO.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.IO.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.IO.4.3.0' to 'packages.config'
Successfully installed 'System.IO 4.3.0' to Metrix
Adding package 'System.IO.Compression.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.IO.Compression.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.IO.Compression.4.3.0' to 'packages.config'
Successfully installed 'System.IO.Compression 4.3.0' to Metrix
Adding package 'System.Linq.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Linq.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Linq.4.3.0' to 'packages.config'
Successfully installed 'System.Linq 4.3.0' to Metrix
Adding package 'System.Linq.Expressions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Linq.Expressions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Linq.Expressions.4.3.0' to 'packages.config'
Successfully installed 'System.Linq.Expressions 4.3.0' to Metrix
Adding package 'System.Net.Http.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Net.Http.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Net.Http.4.3.0' to 'packages.config'
Successfully installed 'System.Net.Http 4.3.0' to Metrix
Adding package 'System.Net.Primitives.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Net.Primitives.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Net.Primitives.4.3.0' to 'packages.config'
Successfully installed 'System.Net.Primitives 4.3.0' to Metrix
Adding package 'System.ObjectModel.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.ObjectModel.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.ObjectModel.4.3.0' to 'packages.config'
Successfully installed 'System.ObjectModel 4.3.0' to Metrix
Adding package 'System.Reflection.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Reflection.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Reflection.4.3.0' to 'packages.config'
Successfully installed 'System.Reflection 4.3.0' to Metrix
Adding package 'System.Reflection.Extensions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Reflection.Extensions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Reflection.Extensions.4.3.0' to 'packages.config'
Successfully installed 'System.Reflection.Extensions 4.3.0' to Metrix
Adding package 'System.Reflection.Primitives.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Reflection.Primitives.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Reflection.Primitives.4.3.0' to 'packages.config'
Successfully installed 'System.Reflection.Primitives 4.3.0' to Metrix
Adding package 'System.Resources.ResourceManager.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Resources.ResourceManager.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Resources.ResourceManager.4.3.0' to 'packages.config'
Successfully installed 'System.Resources.ResourceManager 4.3.0' to Metrix
Adding package 'System.Runtime.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.4.3.0' to 'packages.config'
Successfully installed 'System.Runtime 4.3.0' to Metrix
Adding package 'System.Runtime.Extensions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.Extensions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.Extensions.4.3.0' to 'packages.config'
Successfully installed 'System.Runtime.Extensions 4.3.0' to Metrix
Adding package 'System.Runtime.InteropServices.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.InteropServices.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.InteropServices.4.3.0' to 'packages.config'
Successfully installed 'System.Runtime.InteropServices 4.3.0' to Metrix
Adding package 'System.Runtime.InteropServices.RuntimeInformation.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.InteropServices.RuntimeInformation.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.InteropServices.RuntimeInformation.4.3.0' to 'packages.config'
Successfully installed 'System.Runtime.InteropServices.RuntimeInformation 4.3.0' to Metrix
Adding package 'System.Runtime.Numerics.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.Numerics.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Runtime.Numerics.4.3.0' to 'packages.config'
Successfully installed 'System.Runtime.Numerics 4.3.0' to Metrix
Adding package 'System.Text.Encoding.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Text.Encoding.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Text.Encoding.4.3.0' to 'packages.config'
Successfully installed 'System.Text.Encoding 4.3.0' to Metrix
Adding package 'System.Text.Encoding.Extensions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Text.Encoding.Extensions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Text.Encoding.Extensions.4.3.0' to 'packages.config'
Successfully installed 'System.Text.Encoding.Extensions 4.3.0' to Metrix
Adding package 'System.Text.RegularExpressions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Text.RegularExpressions.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Text.RegularExpressions.4.3.0' to 'packages.config'
Successfully installed 'System.Text.RegularExpressions 4.3.0' to Metrix
Adding package 'System.Threading.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Threading.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Threading.4.3.0' to 'packages.config'
Successfully installed 'System.Threading 4.3.0' to Metrix
Adding package 'System.Threading.Tasks.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Threading.Tasks.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Threading.Tasks.4.3.0' to 'packages.config'
Successfully installed 'System.Threading.Tasks 4.3.0' to Metrix
Adding package 'System.Threading.Timer.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Threading.Timer.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Threading.Timer.4.3.0' to 'packages.config'
Successfully installed 'System.Threading.Timer 4.3.0' to Metrix
Adding package 'System.Xml.ReaderWriter.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Xml.ReaderWriter.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Xml.ReaderWriter.4.3.0' to 'packages.config'
Successfully installed 'System.Xml.ReaderWriter 4.3.0' to Metrix
Adding package 'System.Xml.XDocument.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Xml.XDocument.4.3.0' to folder 'D:\Metrix\packages'
Added package 'System.Xml.XDocument.4.3.0' to 'packages.config'
Successfully installed 'System.Xml.XDocument 4.3.0' to Metrix
Adding package 'NETStandard.Library.1.6.1', which only has dependencies, to project 'Metrix'.
Adding package 'NETStandard.Library.1.6.1' to folder 'D:\Metrix\packages'
Added package 'NETStandard.Library.1.6.1' to folder 'D:\Metrix\packages'
Added package 'NETStandard.Library.1.6.1' to 'packages.config'
Successfully installed 'NETStandard.Library 1.6.1' to Metrix
Adding package 'App.Metrics.Abstractions.2.0.0' to folder 'D:\Metrix\packages'
Added package 'App.Metrics.Abstractions.2.0.0' to folder 'D:\Metrix\packages'
Added package 'App.Metrics.Abstractions.2.0.0' to 'packages.config'
Successfully installed 'App.Metrics.Abstractions 2.0.0' to Metrix
Adding package 'App.Metrics.Concurrency.2.0.0' to folder 'D:\Metrix\packages'
Added package 'App.Metrics.Concurrency.2.0.0' to folder 'D:\Metrix\packages'
Added package 'App.Metrics.Concurrency.2.0.0' to 'packages.config'
Successfully installed 'App.Metrics.Concurrency 2.0.0' to Metrix
Adding package 'App.Metrics.Formatters.Ascii.2.0.0' to folder 'D:\Metrix\packages'
Added package 'App.Metrics.Formatters.Ascii.2.0.0' to folder 'D:\Metrix\packages'
Install failed. Rolling back...
Package 'App.Metrics.Formatters.Ascii.2.0.0 : App.Metrics.Abstractions [2.0.0, )' does not exist in project 'Metrix'
Removed package 'App.Metrics.Concurrency.2.0.0 : NETStandard.Library [1.6.1, )' from 'packages.config'
Removed package 'App.Metrics.Abstractions.2.0.0 : Microsoft.CSharp [4.4.1, ), NETStandard.Library [1.6.1, )' from 'packages.config'
Removed package 'NETStandard.Library.1.6.1 : Microsoft.NETCore.Platforms [1.1.0, ), System.Collections [4.3.0, ), System.Collections.Concurrent [4.3.0, ), System.Diagnostics.Debug [4.3.0, ), System.Diagnostics.Tools [4.3.0, ), System.Diagnostics.Tracing [4.3.0, ), System.Globalization [4.3.0, ), System.IO [4.3.0, ), System.IO.Compression [4.3.0, ), System.Linq [4.3.0, ), System.Linq.Expressions [4.3.0, ), System.Net.Http [4.3.0, ), System.Net.Primitives [4.3.0, ), System.ObjectModel [4.3.0, ), System.Reflection [4.3.0, ), System.Reflection.Extensions [4.3.0, ), System.Reflection.Primitives [4.3.0, ), System.Resources.ResourceManager [4.3.0, ), System.Runtime [4.3.0, ), System.Runtime.Extensions [4.3.0, ), System.Runtime.InteropServices [4.3.0, ), System.Runtime.InteropServices.RuntimeInformation [4.3.0, ), System.Runtime.Numerics [4.3.0, ), System.Text.Encoding [4.3.0, ), System.Text.Encoding.Extensions [4.3.0, ), System.Text.RegularExpressions [4.3.0, ), System.Threading [4.3.0, ), System.Threading.Tasks [4.3.0, ), System.Threading.Timer [4.3.0, ), System.Xml.ReaderWriter [4.3.0, ), System.Xml.XDocument [4.3.0, )' from 'packages.config'
Removed package 'System.Xml.XDocument.4.3.0' from 'packages.config'
Removed package 'System.Xml.ReaderWriter.4.3.0' from 'packages.config'
Removed package 'System.Threading.Timer.4.3.0' from 'packages.config'
Removed package 'System.Threading.Tasks.4.3.0' from 'packages.config'
Removed package 'System.Threading.4.3.0' from 'packages.config'
Removed package 'System.Text.RegularExpressions.4.3.0' from 'packages.config'
Removed package 'System.Text.Encoding.Extensions.4.3.0' from 'packages.config'
Removed package 'System.Text.Encoding.4.3.0' from 'packages.config'
Removed package 'System.Runtime.Numerics.4.3.0' from 'packages.config'
Removed package 'System.Runtime.InteropServices.RuntimeInformation.4.3.0' from 'packages.config'
Removed package 'System.Runtime.InteropServices.4.3.0' from 'packages.config'
Removed package 'System.Runtime.Extensions.4.3.0' from 'packages.config'
Removed package 'System.Runtime.4.3.0' from 'packages.config'
Removed package 'System.Resources.ResourceManager.4.3.0' from 'packages.config'
Removed package 'System.Reflection.Primitives.4.3.0' from 'packages.config'
Removed package 'System.Reflection.Extensions.4.3.0' from 'packages.config'
Removed package 'System.Reflection.4.3.0' from 'packages.config'
Removed package 'System.ObjectModel.4.3.0' from 'packages.config'
Removed package 'System.Net.Primitives.4.3.0' from 'packages.config'
Removed package 'System.Net.Http.4.3.0' from 'packages.config'
Removed package 'System.Linq.Expressions.4.3.0' from 'packages.config'
Removed package 'System.Linq.4.3.0' from 'packages.config'
Removed package 'System.IO.Compression.4.3.0' from 'packages.config'
Removed package 'System.IO.4.3.0' from 'packages.config'
Removed package 'System.Globalization.4.3.0' from 'packages.config'
Removed package 'System.Diagnostics.Tracing.4.3.0' from 'packages.config'
Removed package 'System.Diagnostics.Tools.4.3.0' from 'packages.config'
Removed package 'System.Diagnostics.Debug.4.3.0' from 'packages.config'
Removed package 'System.Collections.Concurrent.4.3.0' from 'packages.config'
Removed package 'System.Collections.4.3.0' from 'packages.config'
Removed package 'Newtonsoft.Json.10.0.3' from 'packages.config'
Removed package 'Microsoft.NETCore.Platforms.1.1.0' from 'packages.config'
Removed package 'Microsoft.CSharp.4.4.1' from 'packages.config'
Removing package 'App.Metrics.Formatters.Ascii.2.0.0 : App.Metrics.Abstractions [2.0.0, )' from folder 'D:\Metrix\packages'
Removed package 'App.Metrics.Formatters.Ascii.2.0.0 : App.Metrics.Abstractions [2.0.0, )' from folder 'D:\Metrix\packages'
Removing package 'App.Metrics.Concurrency.2.0.0 : NETStandard.Library [1.6.1, )' from folder 'D:\Metrix\packages'
Removed package 'App.Metrics.Concurrency.2.0.0 : NETStandard.Library [1.6.1, )' from folder 'D:\Metrix\packages'
Removing package 'App.Metrics.Abstractions.2.0.0 : Microsoft.CSharp [4.4.1, ), NETStandard.Library [1.6.1, )' from folder 'D:\Metrix\packages'
Removed package 'App.Metrics.Abstractions.2.0.0 : Microsoft.CSharp [4.4.1, ), NETStandard.Library [1.6.1, )' from folder 'D:\Metrix\packages'
Removing package 'NETStandard.Library.1.6.1 : Microsoft.NETCore.Platforms [1.1.0, ), System.Collections [4.3.0, ), System.Collections.Concurrent [4.3.0, ), System.Diagnostics.Debug [4.3.0, ), System.Diagnostics.Tools [4.3.0, ), System.Diagnostics.Tracing [4.3.0, ), System.Globalization [4.3.0, ), System.IO [4.3.0, ), System.IO.Compression [4.3.0, ), System.Linq [4.3.0, ), System.Linq.Expressions [4.3.0, ), System.Net.Http [4.3.0, ), System.Net.Primitives [4.3.0, ), System.ObjectModel [4.3.0, ), System.Reflection [4.3.0, ), System.Reflection.Extensions [4.3.0, ), System.Reflection.Primitives [4.3.0, ), System.Resources.ResourceManager [4.3.0, ), System.Runtime [4.3.0, ), System.Runtime.Extensions [4.3.0, ), System.Runtime.InteropServices [4.3.0, ), System.Runtime.InteropServices.RuntimeInformation [4.3.0, ), System.Runtime.Numerics [4.3.0, ), System.Text.Encoding [4.3.0, ), System.Text.Encoding.Extensions [4.3.0, ), System.Text.RegularExpressions [4.3.0, ), System.Threading [4.3.0, ), System.Threading.Tasks [4.3.0, ), System.Threading.Timer [4.3.0, ), System.Xml.ReaderWriter [4.3.0, ), System.Xml.XDocument [4.3.0, )' from folder 'D:\Metrix\packages'
Removed package 'NETStandard.Library.1.6.1 : Microsoft.NETCore.Platforms [1.1.0, ), System.Collections [4.3.0, ), System.Collections.Concurrent [4.3.0, ), System.Diagnostics.Debug [4.3.0, ), System.Diagnostics.Tools [4.3.0, ), System.Diagnostics.Tracing [4.3.0, ), System.Globalization [4.3.0, ), System.IO [4.3.0, ), System.IO.Compression [4.3.0, ), System.Linq [4.3.0, ), System.Linq.Expressions [4.3.0, ), System.Net.Http [4.3.0, ), System.Net.Primitives [4.3.0, ), System.ObjectModel [4.3.0, ), System.Reflection [4.3.0, ), System.Reflection.Extensions [4.3.0, ), System.Reflection.Primitives [4.3.0, ), System.Resources.ResourceManager [4.3.0, ), System.Runtime [4.3.0, ), System.Runtime.Extensions [4.3.0, ), System.Runtime.InteropServices [4.3.0, ), System.Runtime.InteropServices.RuntimeInformation [4.3.0, ), System.Runtime.Numerics [4.3.0, ), System.Text.Encoding [4.3.0, ), System.Text.Encoding.Extensions [4.3.0, ), System.Text.RegularExpressions [4.3.0, ), System.Threading [4.3.0, ), System.Threading.Tasks [4.3.0, ), System.Threading.Timer [4.3.0, ), System.Xml.ReaderWriter [4.3.0, ), System.Xml.XDocument [4.3.0, )' from folder 'D:\Metrix\packages'
Removing package 'System.Xml.XDocument.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Xml.XDocument.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Xml.ReaderWriter.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Xml.ReaderWriter.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Threading.Timer.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Threading.Timer.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Threading.Tasks.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Threading.Tasks.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Threading.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Threading.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Text.RegularExpressions.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Text.RegularExpressions.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Text.Encoding.Extensions.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Text.Encoding.Extensions.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Text.Encoding.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Text.Encoding.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Runtime.Numerics.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Runtime.Numerics.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Runtime.InteropServices.RuntimeInformation.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Runtime.InteropServices.RuntimeInformation.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Runtime.InteropServices.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Runtime.InteropServices.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Runtime.Extensions.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Runtime.Extensions.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Runtime.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Runtime.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Resources.ResourceManager.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Resources.ResourceManager.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Reflection.Primitives.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Reflection.Primitives.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Reflection.Extensions.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Reflection.Extensions.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Reflection.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Reflection.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.ObjectModel.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.ObjectModel.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Net.Primitives.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Net.Primitives.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Net.Http.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Net.Http.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Linq.Expressions.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Linq.Expressions.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Linq.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Linq.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.IO.Compression.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.IO.Compression.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.IO.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.IO.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Globalization.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Globalization.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Diagnostics.Tracing.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Diagnostics.Tracing.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Diagnostics.Tools.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Diagnostics.Tools.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Diagnostics.Debug.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Diagnostics.Debug.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Collections.Concurrent.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Collections.Concurrent.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'System.Collections.4.3.0' from folder 'D:\Metrix\packages'
Removed package 'System.Collections.4.3.0' from folder 'D:\Metrix\packages'
Removing package 'Newtonsoft.Json.10.0.3' from folder 'D:\Metrix\packages'
Removed package 'Newtonsoft.Json.10.0.3' from folder 'D:\Metrix\packages'
Removing package 'Microsoft.NETCore.Platforms.1.1.0' from folder 'D:\Metrix\packages'
Removed package 'Microsoft.NETCore.Platforms.1.1.0' from folder 'D:\Metrix\packages'
Removing package 'Microsoft.CSharp.4.4.1' from folder 'D:\Metrix\packages'
Removed package 'Microsoft.CSharp.4.4.1' from folder 'D:\Metrix\packages'
Executing nuget actions took 27.26 sec
Failed to add reference. The package 'App.Metrics.Formatters.Ascii' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
  Reference unavailable.
========== Finished ==========
Time Elapsed: 00:01:15.0622193

**Comment by alhardy** [comment]
This PR may help? https://github.com/AppMetrics/AppMetrics/issues/245

Will push out a patch some time this week.
