### ISSUE TITLE
[Feature request] ability to report multiple values with InfluxDB

### ISSUE THREAD

**Issue by nullpainter** [AppMetrics/AppMetrics#253]
We are wishing to report latitude and longitude data using App Metrics with an InfluxDB reporter. However, there doesn't appear to be a straightforward way to report more than a single value to an InfluxDB record.

I'm very much aware that this type of data doesn't fit in neatly with the existing metrics types provided by App Metrics so could be considered out-of-scope of this project. However, I would like to propose that multi-value metrics such as user location is sufficiently complementary to counters, etc., that it would be a sensible thing to add. In our Grafana dashboard, we are using many App Metrics metrics to identify key user behaviour and data for a certain section of our application. Spread of geographic location is a key metric for us.

If you're unwilling to muddy your existing metrics with multi-value support, the alternative could be an easier way to access the underlying reporters and write data directly to InfluxDB. I'm currently digging around the App Metrics source code to try and do this myself, but it doesn't seem particularly easy.

**Comment by nullpainter** [comment]
I do, of course, always have the option to use [InfluxDB.NET](https://github.com/ziyasal/InfluxDB.Net).

**Comment by nullpainter** [comment]
> What have you looked at so far to support this?

I've really just had a _very cursory_ poke around your code to see how the current reporters and metrics hang together.

In the meantime, I've achieved what I wanted using the `InfluxDB.LineProtocol` package. Taking a look at the models, it appears that you copied some of these for your implementation? (for example, `LineProtocolPoint`)

Using this package is very straight-forward - exposing a similar 'raw' mechanism in App Metrics could be an approach?

Here's a simplified snippet of my code using `InfluxDB.LineProtocol`:

```
var point = new LineProtocolPoint("user__geolocation", new Dictionary<string, object>
{
	{"latitude", latitude},
	{"longitude", longitude},
});

var payload = new LineProtocolPayload();
payload.Add(point);

...

await client.WriteAsync(payload);
```

Or could this be considered an unnecessary overlap in functionality with an existing package?

**Comment by nullpainter** [comment]
> Would looking at geohash support in some way be useful?

As it happens, I had to modify my code to use geohashes due to it being expected by the Grafana panel in question. 

Even though geohashes are a single value - so technically out-of-scope of this feature request as originally written - they're still not able to be natively written to InfluxDB by App Metrics as they're string values.

I do like the out-of-the-box metric types you're providing. It forces one to think carefully about one's data and allows for capture in a consistent fashion. I would therefore be loathe to modify any of these. Following on from my previous comment, having some manner of low-level raw method in `IMeasureMetrics` could work nicely.

I dislike the word 'raw', but something like:

```c#
var options = new RawOptions  
{ 
  Name = "Location",
  Context = "user"
}

var data = new LineProtocolData(new Dictionary<string, object>
{
	{"geohash", geohash},
});

_metrics.Measure.Raw.Write(options, data);

```

**Comment by alhardy** [comment]
> Taking a look at the models, it appears that you copied some of these for your implementation?

Yep `LineProtocolPoint`  taken and modified from that package to suit my needs. Same approach taken for all other reporters.

> Or could this be considered an unnecessary overlap in functionality with an existing package?

I have thought about supporting "raw" metrics, as well as support for flushing them on write as opposed to always aggregating. Don't see it as an overlap since AppMetrics abstracts away reporters.

**Comment by NocturnalShadow** [comment]
Hello, I am also very interested in a feature of reporting multi-field data points. Is there any progress on that?

Essentially, all I need is just a "multi-field Gauge". 

So single-value Gauge reports like this:
cpu_usertime,host=i-09875asg value=82 1465839830100400200
cpu_idle,host=i-09875asg value=18 1465839830100400200

But multi-field Gauge could report like:
cpu,host=i-09875asg usertime=82 idle=18 1465839830100400200

Is it possible to implement?

**Comment by alhardy** [comment]
I haven't investigated yet, it's on my backlog but can't promise when I'll be able to get around to it. In the middleware of several other things at the moment.

**Comment by dflor003** [comment]
Any progress on this? If not, are you guys opposed to someone submitting a pull request for this?

**Comment by alhardy** [comment]
@dflor003 a PR would be great

**Comment by dflor003** [comment]
Hey, I know it's been a while, but there's still a need for this in a few apps my team needs. I've put together a proposal to create a multi-value gauge in #664 and I should have some time to submit a PR for this. Any feedback would be appreciated.
