### ISSUE TITLE
Exponential decay reservoir does not update the sum of samples when rescaling

### ISSUE THREAD

**Issue by karolz-ms** [AppMetrics/AppMetrics#256]
When exponential decay reservoir is rescaled, the count of the samples is updated as it should

https://github.com/AppMetrics/AppMetrics/blob/dev/src/App.Metrics.Core/ReservoirSampling/ExponentialDecay/DefaultForwardDecayingReservoir.cs#L289

but the sum of the sample values is not. I believe this to be a bug going all the way to the original Java implementation.

I have a fix: https://github.com/karolz-ms/AppMetrics/commit/3bdcfc3bb98d275368a02150f528d1321cac8d60 Would you like me to open a PR?

**Comment by alhardy** [comment]
Yes please. Thanks for taking the time.

**Comment by karolz-ms** [comment]
Thanks. PR sent, will keep an eye on it

Apologies in advance if some checks fail, I am still learning the ropes here, will fix as necessary.
