### ISSUE TITLE
Healthcheck endpoint security

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [AppMetrics/AppMetrics#259]
Hello, I've been looking over the docs to get started with an asp.net core webapi project and one of the things I could not find was how to secure the healthcheck endpoints.

I know I'm probably missing something obvious here but I would like to restrict those endpoints using our existing authorization code to users with certain roles, any ideas?

**Comment by WhatFreshHellIsThis** [comment]
I understand you don't want to get into the security aspect, that makes perfect sense but if you are leaving it to the user how does the user go about securing the endpoint in this case?

In my project this is an api server and the api has secured endpoints that require a JWT token to access and are controlled by roles.

The endpoints exposed by App.Metrics need to be secured, a public facing api server shouldn't allow anyone to see that information or affect the server through them unless authenticated and authorized.

Can you put some kind of hook into it perhaps so it checks with user provided code before allowing it to happen?

**Comment by WhatFreshHellIsThis** [comment]
I've done some digging and unfortunately I don't see any options here.  I tried to add my own middleware to secure the endpoint but App.Metrics installs it's middleware ahead of any that I can add in Startup.cs::Configure()

I know you'd prefer to leave it to the user but I don't really see how you can do that - this is a showstopping issue for any public facing server related use of App.Metrics.  

Is it possible to change how it starts so that we can at least insert our own middleware ahead of App.Metrics endpoints?

Any suggestions?

**Comment by WhatFreshHellIsThis** [comment]
Actually, I just had a thought: is it possible to get the same output App.Metrics sends out on it's own endpoints in my own code so I can expose it through my own api, I'm thinking specifically of the metrics-text and the healthcheck?  If this was possible then that would solve everything.

**Comment by alhardy** [comment]
That's probably possible but thinking more work than required.

> I tried to add my own middleware to secure the endpoint but App.Metrics installs it's middleware ahead of any that I can add in Startup.cs::Configure()

You do have control over where to register App Metrics middleware using the `IApplicationBuilder` [extensions](https://www.app-metrics.io/web-monitoring/aspnet-core/health/#how-to-use).

**Comment by alhardy** [comment]
A quick approach comes to mind which could look something like:

```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication();
            var metrics = AppMetrics.CreateDefaultBuilder().Build();
            services.AddMetrics(metrics).AddMetricsEndpoints();
            services.AddMvc().AddMetrics();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseAuthentication();

            app.Use(async (context, next) =>
            {
                if (context.Request.Path.Value.EndsWith("health") && !context.User.Identity.IsAuthenticated)
                {
                    await context.Response.WriteAsync("Unauthorized");
                    return;
                }

                await next.Invoke();

            });

            app.UseMetricsAllEndpoints();
            app.UseMetricsAllMiddleware();

            app.UseMvc();
        }
    }
```

**Comment by alhardy** [comment]
Re your initial thought, if you dig into the source for the [`MetricsEndpointMiddleware`](https://github.com/AppMetrics/AspNetCore/blob/dev/src/App.Metrics.AspNetCore.Endpoints/Middleware/MetricsEndpointMiddleware.cs#L39), you'll noticed that it simply uses `IMetricsResponseWriter` to write the response.

You could probably inject that into your controller along with `IMetrics` if you wanted to take that approach.

**Comment by WhatFreshHellIsThis** [comment]
Cool, ok there are some options there thank you.

**Comment by WhatFreshHellIsThis** [comment]
Tried to go the authorization middleware route but kept running into issues and finally decided to figure out how to get the same output out of App.Metrics and just use my own controller so I can continue to use our regular authorization code.

I used our own api controller instead of the built in App.Metrics endpoints and to provide the same output created a method in the controller to fetch the snapshot formatted for either plain text or json:


```
        /// <summary>
        /// Get the metrics snapshot
        /// </summary>
        /// <param name="format">Either "json" for json format or "plain" for plaintext format</param>
        /// <returns></returns>
        private async Task<string> GetTheMetrics(string format)
        {
           //metrics is injected in the controller constructor
            var snapshot = metrics.Snapshot.Get();

            var formatters = ((IMetricsRoot)metrics).OutputMetricsFormatters;
            string sResult = $"ERROR GETTING METRICS IN {format} FORMAT";

            foreach (var formatter in formatters)
            {
                if (formatter.MediaType.Format == format)
                {
                    using (var stream = new MemoryStream())
                    {
                        await formatter.WriteAsync(stream, snapshot);
                        sResult = System.Text.Encoding.UTF8.GetString(stream.ToArray());
                    }
                }
            }

            return sResult;
        }
```
