### ISSUE TITLE
AddMetricsResourceFilter()??

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [AppMetrics/AppMetrics#262]
QuickStart docs:
https://www.app-metrics.io/web-monitoring/aspnet-core/quick-start/

States at one point:

> " Modify the Startup.cs allowing App Metrics to inspect MVC routes by using the MvcOptions extensions method AddMetricsResourceFilter():"

Then gives sample startup.cs code that does not have AddMetricsResourceFilter() anywhere in the example code.

After that code block it again references the extension method:

> "The AddMetricsResourceFilter extension method on MvcOptions is required to allow App Metrics to inspect MVC route templates to tag metrics."

I tried to follow that example but none of my WEBAPI routes are appearing in my metrics so it appears to not be working.

I'm concerned that the docs are incorrect but I can't find any way to add AddMetricsResourceFilter(), it just doesn't seem to exist when following the example.

Are the docs messed up or does this one line in Startup.cs ConfigureServices method supersede all that:
`services.AddMvc().AddMetrics();`

**Comment by WhatFreshHellIsThis** [comment]
Hello, I am using the MVC package as it appears it's required so I will stick with that.

Sorry but I'm almost completely lost on all this at this point are there any docs or examples that will show the proper configuration required to automatically collect metrics for individual REST webapi routes?

I examined the code you linked to and it looks like you wrote a new route resolver, but I'm not sure what to do with that information.  Would it be the case that if I pulled the packages off of Nuget today that they are not the most up to date and this is the reason why I can't get it to work?

**Comment by alhardy** [comment]
@WhatFreshHellIsThis  [documentation](https://www.app-metrics.io/web-monitoring/aspnet-core/quick-start/#configuration) updated.

Happy to investigate your issue as suggested [here](https://github.com/AppMetrics/AppMetrics/issues/261#issuecomment-384816681) if you can provide a sample demostrating the issue.
