### ISSUE TITLE
Why is App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService triggering even when console report is off?

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [AppMetrics/AppMetrics#266]
Asp.net core 2.0 project: it is my understanding that unless you add the console reporter 

`App.Metrics.Reporting.Console` 

there would be no background process running, however I just turned on tracing to debug a separate issue and my trace log started getting hammered with this:

> 
> 2018-05-02 08:06:29.9057|TRACE|App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService|Delaying for 00:00:00.5000000
> 2018-05-02 08:06:30.4074|TRACE|App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService|Delaying for 00:00:00.5000000
> 2018-05-02 08:06:30.9221|TRACE|App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService|Delaying for 00:00:00.5000000
> 2018-05-02 08:06:31.4356|TRACE|App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService|Delaying for 00:00:00.5000000
> 2018-05-02 08:06:31.9377|TRACE|App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService|Delaying for 00:00:00.5000000
> 2018-05-02 08:06:32.4403|TRACE|App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService|Delaying for 00:00:00.5000000
> 2018-05-02 08:06:32.9568|TRACE|App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService|Delaying for 00:00:00.5000000
> 2018-05-02 08:06:33.4588|TRACE|App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService|Delaying for 00:00:00.5000000
> 2018-05-02 08:06:33.9671|TRACE|App.Metrics.AspNetCore.Reporting.ReportSchedulerHostedService|Delaying for 00:00:00.5000000
> 

I did try out the console reporter as per the example earlier but then removed that assembly from my project file and also removed the line of code calling it in Program.cs so I didn't expect to see this at all.

The docs seem to indicate that there is no background process running with the sole exception of the console reporter and it's up to us to trigger reporting so this code should not be running as far as I can tell.  

What is happening here and how do I stop it?

**Comment by alhardy** [comment]
Are you able to debug the AspNet Core project to confirm? See https://github.com/AppMetrics/AspNetCore/blob/4199a4cc89d26e778869d6199b6e678982a7b279/src/App.Metrics.AspNetCore.Reporting/ReportSchedulerHostedService.cs#L75

**Comment by WhatFreshHellIsThis** [comment]
I'm not sure I understand; what would you like confirmed?

**Comment by alhardy** [comment]
Try [switching off reporting](https://www.app-metrics.io/getting-started/fundamentals/configuration/) in your appsetting.json

```
{
  "MetricsOptions": {
    "ReportingEnabled": false
  }
}
```

**Comment by WhatFreshHellIsThis** [comment]
Will this setting interfere with reporting to InfluxDB?

**Comment by alhardy** [comment]
Yes that flag will disable reporting altogether.

Why not use your own configuration settings? e.g.

```
            return WebHost.CreateDefaultBuilder(args)
                          .ConfigureMetricsWithDefaults(
                              builder =>
                              {
                                  if (configuration.GetValue<bool>("EnableConsoleReporting")
                                  {
                                      builder.Report.ToConsole();
                                  }

                                  builder.Report.ToInfluxDb(influxOptions);
                              })
                          .UseMetrics()
                          .UseSerilog()
                          .UseStartup<Startup>()
                          .Build();
```

**Comment by WhatFreshHellIsThis** [comment]
Thank you, this information helped.
