### ISSUE TITLE
Customisable properties in /env

### ISSUE THREAD

**Issue by tomap** [AppMetrics/AppMetrics#267]
Hi,

Would it be possible to display the productversion in the /env endpoint?

https://github.com/AppMetrics/AppMetrics/blob/8793a239c907a25e1c0085e8ebb61204c63e82e6/src/App.Metrics.Core/Infrastructure/EnvironmentInfoProviderCache.cs#L42

Adding 
```FileVersionInfo.GetVersionInfo(Assembly.GetEntryAssembly().Location).ProductVersion```
should work

Currently, you only display the file version, but with dotnet command line, it is very convenient to set a version suffix, thus it make sense to display that info.
See --version-suffix here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore2x#options

Thank you

**Comment by alhardy** [comment]
@tomap Thanks for the suggestion. I'd be happy to take that as a PR, otherwise I can look at this in a later release

**Comment by tomap** [comment]
I did a PR :)

**Comment by alhardy** [comment]
Thanks! Just added the one comment on the PR
