### ISSUE TITLE
AppMetrics in .netframework 4.5.2 by web api Autofac issue

### ISSUE THREAD

**Issue by caodaiming** [AppMetrics/AppMetrics#271]
hi, 
.netframework 4.5.2 by webapi  not support autofac, follow sample and add autofac code.

""builder.RegisterType<ServiceCollection>().As<IServiceCollection>().InstancePerLifetimeScope();"
👍 builder.RegisterType<IMetrics>().InstancePerLifetimeScope();"

Error:
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "给定关键字不在字典中。",
  "ExceptionType": "System.Collections.Generic.KeyNotFoundException",
  "StackTrace": "   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   在 App.Metrics.Extensions.Owin.WebApi.MetricsWebApiMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   在 System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   在 System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"
}

**Comment by alhardy** [comment]
The Owin.WebApi package is obsolete, sorry I should really comment on this in that repo and NuGet.

It should be straight forward to just take the owin middleware or build out your own.

**Comment by caodaiming** [comment]
.netframework sample by new sample that asp.net webapi or mvc with autofac.

**Comment by caodaiming** [comment]
how using autofac in appmetrics by .netframework. hope get new sample about .netframework .

**Comment by alhardy** [comment]
you could do something like [this](https://github.com/AppMetrics/MicrosoftExtensions/blob/dev/sandbox/MetricsMicrosoftExtensionsSandbox/Host.cs#L158) and then check the [Autofac docs](http://autofaccn.readthedocs.io/en/latest/integration/netcore.html) on how to working with `IServiceCollection`

**Comment by caodaiming** [comment]
you have sample by autofac?

**Comment by alhardy** [comment]
No I don't. If you don't want to use `IServiceCollection` you can look at the [Microsoft Extensions](https://github.com/AppMetrics/MicrosoftExtensions/tree/dev/src/App.Metrics.Extensions.DependencyInjection) package as an example to build something similar with Autofac. 

If you're happy to take a dependancy on Microsoft DI then just config AppMetrics as per docs and pass the  `IServiceCollection'  to Autofac as show in the link in my previous comment.

Does this help?

**Comment by caodaiming** [comment]
you hava time write sample that .net framework webApi and mvc with autofac.

I'am look at the Microsoft extensions,but not solve this issue. Thx.

**Comment by caodaiming** [comment]
![image](https://user-images.githubusercontent.com/977531/39861301-c533c4fa-5472-11e8-8123-2a79703c3dd7.png)

**Comment by alhardy** [comment]
Closing this one, no plans to support OWIN as it's pretty much obsolete now
