### ISSUE TITLE
Logging some private / diagnostic only information at INFO level 

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [AppMetrics/AppMetrics#272]
Hello, please reconsider logging the below kind of information as "INFO" level, it's diagnostic information, not day to day operations information and should be logged in my opinion at DEBUG level at most.

Also of concern to some scenarios it leaks private internal information that should not be revealed in a basic "INFO" level log.

> 2018-05-09 10:47:19.6283|INFO|App.Metrics.Reporting.InfluxDB.InfluxDbMetricsReporter|Using Metrics Reporter App.Metrics.Reporting.InfluxDB.InfluxDbMetricsReporter. Url: http://127.0.0.1:8086/write?db=MyAppDB FlushInterval: 00:00:20

**Comment by WhatFreshHellIsThis** [comment]
As the maker of the tool I can see how it seems appropriate to log everything about it but speaking from the perspective of the developer user of the tool where our point of view must be in turn *our* end users of our software who will view and ultimately have to deal with logs (and privacy concerns) I don't believe  it is the right level at all and is a completely unnecessary inconvenience that we are forced to deal with in a workaround.

INFO level should be left to the use of the highest level of code that is running, the end user using the tool in their top level software and should not contain strictly diagnostic level information from lower level tools that are integrated into software.

When people want to diagnose they can set the log level lower to DEBUG or TRACE, but if they don't need or want to diagnose then they should be able to set it to INFO and not see any diagnostic information unless the top level application maker intends for them to see it.

When an internal tool uses INFO level for strictly internal diagnostic information you effectively are "polluting" the log with unnecessary information at that level.

**Comment by alhardy** [comment]
What happens when you want to diagnose your own code only at a debug or trace level?

AspNet Core logs a bunch of stuff at an info level, should that all be debug or trace as well? 

I don't agree that using log filtering is a "forced workaround".

**Comment by WhatFreshHellIsThis** [comment]
Yes asp.net core does log a bunch of similar diagnostic only related stuff at info level so does EF Core and there are people asking them to bring it down a level for the same reasons I've given here.  

Log filtering is not a good resolution; what you are asking me to do is turn OFF logging from App.Metrics unless the user has selected a DEBUG or TRACE level log then I must turn ON all logging from App.Metrics.  I'm forced to do this because it doesn't have, in my opinion, an appropriate default that matches the levels as they are traditionally intended in application logging.

At the end of the day I ask myself why is App.Metrics logging that particular information?  What is the purpose and to whom is it directed?  When I ask myself those questions it seems inevitable to me that it should be lower level than Info.   It's just not something an end user needs to see in their logs unless and until they *need* to see it then it should be a configuration setting to Debug away.

Those are my reasons, can you help me understand why you feel it needs to be at info level?

**Comment by alhardy** [comment]
> Log filtering is not a good resolution; what you are asking me to do is turn OFF logging from App.Metrics unless the user has selected a DEBUG or TRACE level log then I must turn ON all logging from App.Metrics

I'm suggesting that if you're not interested in any App Metric specific logs, just ignore it for all log levels.

> Those are my reasons, can you help me understand why you feel it needs to be at info level?

I'm not sure what "it" is referring to, just the info log message specific in the initial comment of this issue or others? I'm happy to review level levels on specific cases. Currently info log levels are set to what have been useful in my applications using App Metrics.

**Comment by WhatFreshHellIsThis** [comment]
Yes the log message I posted and any others that are strictly *diagnostic* in nature and not useful on an ongoing basis to the top level user of the software for years to come.

In my opinion any information that is useful only to diagnose problems should be lower than INFO level.  That particular log item leaks what is potentially private information to some into the log and is also unnecessary for day to day operations.

**Comment by alhardy** [comment]
All two places logging as info level changed to debug. Also re "private information", InfluxDB credentials for example were/are never logged, only the url and database.

**Comment by WhatFreshHellIsThis** [comment]
Thank you @alhardy I appreciate it!
