### ISSUE TITLE
can't get total http requests

### ISSUE THREAD

**Issue by john199604** [AppMetrics/AppMetrics#276]
Hello,

When i am targeting Prometheus to my .Net Core application and try to get datas with `http_requests_total` query, it does not show anything.

And when I take a look at `http://localhost:5050/metrics-text` it shows only these : 
```
application_httprequests_transactions_sum
application_httprequests_transactions_count
application_httprequests_transactions
application_httprequests_transactions_per_endpoint
application_httprequests_transactions_per_endpoint_coun
application_httprequests_transactions_per_endpoint_sum
```

how can i get other queries like the one that i mentioned before?

**Comment by bdrupieski** [comment]
What middleware are you using to record metrics? The default middleware out of the box?
