### ISSUE TITLE
application_health_results metric

### ISSUE THREAD

**Issue by megafinz** [AppMetrics/AppMetrics#277]
I'm trying to use the Web Monitoring Dashboard (https://grafana.com/dashboards/2204). There is a panel for metric that is called `application_health_results` which I'd like to use. The problem is that I can't see such metric in the exporter output, also I can't find any relevant information anywhere. Searched repositories for usage but no luck. Is that metric deprecated or am I doing something wrong?

**Comment by alhardy** [comment]
See this ticket: https://github.com/AppMetrics/Health/issues/9
