### ISSUE TITLE
New metric type for Prometheus histograms?

### ISSUE THREAD

**Issue by bdrupieski** [AppMetrics/AppMetrics#278]
Over the past few weeks I've started using AppMetrics and its Prometheus support. It's a fantastic package. Thank you for your work on this library.

I'm currently using AppMetrics timers to generate Prometheus summaries for a single application instance but will soon be recording and scraping metrics from multiple instances as we scale out. Prometheus summaries can't be aggregated, but Prometheus histograms can. I'd like to convert some of my summaries to histograms so that I can query and aggregate across instances.

Currently, AppMetrics does not support Prometheus histograms. AppMetrics histograms map more closely to Prometheus summaries. I think I could generate a makeshift Prometheus histogram using a bunch of AppMetrics counters out of the box, but I'd like to generate these more idiomatically.

There's no extensibility hook to define custom metrics and have them flow all the way to the Prometheus metrics endpoint. If I want to add in a new metric type to support Prometheus histograms, it has to be baked in. I was thinking of privately forking AppMetrics, adding what I need, and then publishing the package to my company's private NuGet, but I don't want to have to pull in upstream changes all the time to maintain that package.

Would you be receptive to a pull request for a new metric type with user-defined buckets that would map to Prometheus histograms? Or, does anyone have ideas or guidance for how to best approach this?

I'd be happy to write an initial implementation for review by project contributors/maintainers. The design of the project is well-defined enough that I can try to follow the other metrics as closely as possible. 

Since there's already a metric named Histogram I don't know what a new type for this purpose could be named. BucketHistogram? CustomHistogram? CustomBinHistogram? UserDefinedBinSizeHistogram?

**Comment by alhardy** [comment]
Thanks for the feedback. Always happy to take a PR, surely we can come to a solution which doesn't require you to maintain a custom fork.

@Rurouni is the original contributor of the Prometheus extension, would be great to get his thoughts

**Comment by bdrupieski** [comment]
Great! It might take a few weekends but I'll try to put something together for review.

**Comment by MikhaelSorkin** [comment]
Hello!
Is there any progress? Or may be some 'experimental' package?

**Comment by alhardy** [comment]
@mikenorgate I've merged your pull request realted to this ticket. After merging and testing I noticed the [Scale](https://github.com/AppMetrics/AppMetrics/blob/features%2F4.2.0/src/Core/src/App.Metrics.Abstractions/BucketHistogram/BucketHistogramValue.cs#L33) method on the BucketHistogramValue is unused?

Also, are you able to contribute some documentation for the new metrics types [here](https://github.com/AppMetrics/Docs.V2.Hugo)?

- List and explain the new metric types [here](https://www.app-metrics.io/getting-started/metric-types/)
- Add a details page for each e.g. https://www.app-metrics.io/getting-started/metric-types/histograms/

I'll push out a preview package once documented.

**Comment by alhardy** [comment]
Couple of other questions:
1. Should [Histogram Metrics](https://github.com/AppMetrics/AppMetrics/blob/features%2F4.2.0/src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/Extensions/MetricDataValueSourceExtensions.cs#L92) types be a Summary?
2. Should [Bucket Histogram Metrics](https://github.com/AppMetrics/AppMetrics/blob/features%2F4.2.0/src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/Extensions/MetricDataValueSourceExtensions.cs#L109) type be a Histogram?

**Comment by mikenorgate** [comment]
@alhardy I'm not sure, it's been a while since I've properly looked at it so I'll need to go through and refresh my memory on exactly how it works

**Comment by mikenorgate** [comment]
> Couple of other questions:
> 
> 1. Should [Histogram Metrics](https://github.com/AppMetrics/AppMetrics/blob/features%2F4.2.0/src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/Extensions/MetricDataValueSourceExtensions.cs#L92) types be a Summary?
> 2. Should [Bucket Histogram Metrics](https://github.com/AppMetrics/AppMetrics/blob/features%2F4.2.0/src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/Extensions/MetricDataValueSourceExtensions.cs#L109) type be a Histogram?

@alhardy I think you are right, that was probably a copy paste error. Its the same for bucket timers they should also be Histogram not Summary
