### ISSUE TITLE
Integration with Log Analytics/ Application Insights

### ISSUE THREAD

**Issue by MarekLani** [AppMetrics/AppMetrics#282]
Hello,

I would like to ask, whether there is out of the box integration with Application Insights or Log Analytics, and if not, if there is plan?

Thank you.
KR
Marek.

**Comment by alhardy** [comment]
There's no out of box integration, I have thought about it, initial thoughts are, I'm not sure about having an abstraction on top of application insights. 

Interested to know your thoughts. It wouldn't be difficult to build, use one of the existing reporters as a guide. 

Even though I'm not sure about the abstraction, I'd like to see it implemented ;)

**Comment by MarekLani** [comment]
Hi @alhardy thanks for answer. There will need to be decision made whether we go with the implementation of custom reporter. If so, I will definitely let you know.
Thanks.

**Comment by alhardy** [comment]
https://github.com/jdvor/appmetrics-applicationinsights
