### ISSUE TITLE
Bug in Elasticsearch sample?

### ISSUE THREAD

**Issue by mbalsam** [AppMetrics/AppMetrics#285]
Im trying to follow the tutorial:  [https://www.app-metrics.io/reporting/reporters/elasticsearch/](url)

In the Web Monitoring Section > Grafana section You say 

> Add an index and the document mappings to Elasticsearch using the default mappings provided in the github repository

The link it points in default mappings is:

[https://raw.githubusercontent.com/alhardy/AppMetrics.Extensions.Elasticsearch/master/visualization/App.Metrics.Sandbox-Elasticsearch-IndexAndMappingSetup.json](url)

When i put that into DevTools in kibana and click on 

`PUT appmetricssandbox/_mapping/timer?update_all_types`

I get 

`#! Deprecation: [update_all_types] is deprecated since indices may not have more than one type anymore`

When i click on 

`PUT appmetricssandbox/_mapping/counter?update_all_types`

> {
>   "error": {
>     "root_cause": [
>       {
>         "type": "illegal_argument_exception",
>         "reason": "Rejecting mapping update to [appmetricssandbox] as the final mapping would have more than 1 type: [timer, counter]"
>       }
>     ],
>     "type": "illegal_argument_exception",
>     "reason": "Rejecting mapping update to [appmetricssandbox] as the final mapping would have more than 1 type: [timer, counter]"
>   },
>   "status": 400
> }
>

**Comment by mbalsam** [comment]
[https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_70_mappings_changes.html#_the_literal_update_all_types_literal_option_has_been_removed](url)

> The update_all_types option has been removededit
> This option is useless now that all indices have at most one type.

**Comment by mbalsam** [comment]
We rolledback to version 5.4.0 bug are stuck at the step when we add the datasource and test it. 

In ElasasticSearch details 

Index name = appmetricssandbox
Time field name = @timestamp
We click save and test 

Error: No data field named @timestamp found

**Comment by alhardy** [comment]
Thanks @mbalsam. Any chance of logging ES issues in the [ES reporter repo](https://github.com/AppMetrics/Elasticsearch) please?

Related to your [issue](https://github.com/AppMetrics/Elasticsearch/issues/25)?
