### ISSUE TITLE
Change metric in flight?

### ISSUE THREAD

**Issue by mts57017** [AppMetrics/AppMetrics#286]
Is it possible to change a tag value in flight? We have a multi-tenant api and for each request we need to be able to add a tag that specified the client, in our case. Is this possible?

**Comment by alhardy** [comment]
Does this help? https://www.app-metrics.io/getting-started/fundamentals/tagging-organizing/#tagging-at-runtime

**Comment by alhardy** [comment]
Closing this out, feel free to re-open if more info is required
