### ISSUE TITLE
Response Timer produces jagged graphs

### ISSUE THREAD

**Issue by lyosha-kor** [AppMetrics/AppMetrics#290]
Hello.

I'm trying to log response time percentiles for a WebAPI app. 

I'm using InfluxDb and a `Timer` with the default reservoir and several tags. I also have a couple of global tags.

For some reason the resulting graphs are jagged -- like jumping between the same values for a period of time.

Here is a picture to show what I mean (I'm measuring the 99th and 75th percentiles) --

![2018-07-12 17_23_52-grafana - sports api](https://user-images.githubusercontent.com/33552936/42641565-7b6c1d2e-85fd-11e8-9e52-1912dbbd4d19.png)

This looks wrong. Any ideas what might be the cause and how to solve this?

My code is
```csharp
public class AppMetricsFilter : ActionFilterAttribute
{
    private readonly string _siteIdHeader;

    private static readonly TimerOptions TimerOptions = new TimerOptions { Name = "response_time" };
    private static readonly string[] MetricsTagKeys = { "operator_id", "action_name" };
    
    public AppMetricsFilter(string siteIdHeader)
    {
        _siteIdHeader = siteIdHeader;
    }

    public override async Task OnActionExecutionAsync(
        ActionExecutingContext context, ActionExecutionDelegate next)
    {
        var metrics = context.HttpContext.RequestServices.GetService<IMetricsRoot>();

        if (metrics != null)
            await ExecuteWithMetrics(context, next, metrics);
        else
            await next();
    }

    private async Task ExecuteWithMetrics(
        ActionExecutingContext context, ActionExecutionDelegate next, IMetricsRoot metrics)
    {
        var actionName = context.RouteData.Values["action"]?.ToString();
        var operatorId = context.HttpContext.Request.Headers[_siteIdHeader].FirstOrDefault();

        var metricsTags = new MetricTags(MetricsTagKeys, new[] { operatorId, actionName });

        using (metrics.Measure.Timer.Time(TimerOptions, metricsTags))
            await next();
    }
}
```

**Comment by kroppt** [comment]
I have been getting the same results using the default dashboard, reporting, and reservoir, along with InfluxDB. Given that, I think your implementation is working fine. But I certainly would like to know why our graphs look like this... I assumed that it represented the average of 95% of the data using standard deviation or something, but that doesn't follow the graph at all.

**Comment by alhardy** [comment]
@lyosha-kor @kroppt what version are you guys using?

**Comment by lyosha-kor** [comment]
@alhardy it's 2.1.0

**Comment by alhardy** [comment]
There's was a change I've pushed in the latest pre-release around sampling but I havn't noticed "jagged graphs" nor with the 2.1.0 version.

I've ran the latest [InfluxDB sandbox project](https://github.com/AppMetrics/InfluxDB/tree/dev/sandbox/MetricsInfluxDBSandboxMvc) locally which looks like this:

![image](https://user-images.githubusercontent.com/729185/42688821-31cd73cc-86e1-11e8-8e59-53b7990d2f04.png)

**Comment by alhardy** [comment]
If you'd like to play with sampling params the [reservoir sample](https://github.com/AppMetrics/Samples.V2/tree/master/AspNetCore2.Api.Reservoirs) is a good place to do that. The [grafana dashboard](https://github.com/AppMetrics/Samples.V2/tree/master/Grafana) for influxdb is included in the repo.

Results from running the sample:

![image](https://user-images.githubusercontent.com/729185/42689450-b0757f88-86e3-11e8-8804-2527d08de7d5.png)

To test sampling params there is a timer around a delay based on secons now as follows:

```
var second = DateTime.Now.Second;

            if (second <= 20)
            {
                return Task.CompletedTask;
            }

            if (second <= 40)
            {
                return Task.Delay(TimeSpan.FromMilliseconds(50), HttpContext.RequestAborted);
            }

            return Task.Delay(TimeSpan.FromMilliseconds(100), HttpContext.RequestAborted);
```

**Comment by kroppt** [comment]
@alhardy  I also am using 2.1.0.

My graph looks like the following (default AppMetrics dashboard):
![image](https://user-images.githubusercontent.com/14015672/42695323-a6f3c29e-867a-11e8-9520-56e6b8fe40e4.png)

For @lyosha-kor and me, it looks like the percentiles converge, which makes them useless.

Additionally, I believe the addition of the 75th percentile metric makes his graph appear different to mine with respect to the magnitude of the variance, while having the same convergence effect as mine.

In terms of implementation, I am using:
```c#
public void ConfigureServices(IServiceCollection services) {
	...
	var metrics = AppMetrics.CreateDefaultBuilder()
		.Report.ToInfluxDb(options =>
		{
			...
		})
		.Build();
	services.AddMvc().AddMetrics();
	services.AddMetrics(metrics);
	services.AddMetricsTrackingMiddleware();
	services.AddSingleton<IStartupFilter>(new DefaultMetricsTrackingStartupFilter());
	services.AddMetricsReportScheduler();
}
```

`USE dbname; SELECT last(*) FROM "application.httprequests__transactions"`:
```
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "name": "application.httprequests__transactions",
                    "columns": [
                        "time",
                        "last_count.hist",
                        "last_count.meter",
                        "last_last",
                        "last_max",
                        "last_mean",
                        "last_median",
                        "last_min",
                        "last_p75",
                        "last_p95",
                        "last_p98",
                        "last_p99",
                        "last_p999",
                        "last_rate.mean",
                        "last_rate15m",
                        "last_rate1m",
                        "last_rate5m",
                        "last_samples",
                        "last_stddev",
                        "last_sum"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00Z",
                            3,
                            3,
                            141.718927,
                            1289.223936,
                            516.117275333333,
                            141.718927,
                            117.408963,
                            1289.223936,
                            1289.223936,
                            1289.223936,
                            1289.223936,
                            1289.223936,
                            4.39891977646933,
                            34.6268727458361,
                            20.0892652477217,
                            32.0357437555689,
                            3,
                            546.759042091239,
                            1548.351826
                        ]
                    ]
                }
            ]
        }
    ]
}
```

If I am not mistaken, the datum confirms that the percentiles converged.

**Comment by alhardy** [comment]
@kroppt what does it look like if you have a larger sample size, at the moment it's just 3.

Also keep in mind quantiles are weighted and decay.

Possible to write a [unit test](https://github.com/AppMetrics/AppMetrics/blob/dev/test/App.Metrics.Sampling.Facts/WeightedSnapshotTests.cs) to to demonstrate?

**Comment by kroppt** [comment]
I did a quick test and got around 180 samples within 5 minutes, and got something like this:
![image](https://user-images.githubusercontent.com/14015672/42702762-0c3cfbd8-8690-11e8-9d4f-10b00bc4aafb.png)

So, I think you are right about the samples, although it doesn't seem to be decaying the number of samples like the other graph. I think perhaps I was mistaken and had restarted the server since the original graph was taken, resetting the count.

I would certainly be interested in seeing @lyosha-kor's sample size to confirm.

**Comment by alhardy** [comment]
You can adjust the interval to rescale the reservoir as demostrated [here](https://github.com/AppMetrics/Samples.V2/blob/master/AspNetCore2.Api.Reservoirs/MetricsRegistry.cs#L37).

Reservoir settings can be applied globally using `SampleWith` extension on the fluent builder.
