### ISSUE TITLE
Integration with Seq logging server

### ISSUE THREAD

**Issue by nskerl** [AppMetrics/AppMetrics#292]
First, thanks for the amazing work on this library! It's been a treat reading through this codebase.

I use [Seq](https://getseq.net/) to store low volume log events and errors, but I would like to start pushing sensor data. Of course, the volume involved in sensor data is obscene, and I would rather not pollute my event server with raw sensor measures when all I really want are the aggregates. Rather than take on another specialized backend, Id like to consider if Seq paired with AppMetrics can meet this need. 

I was able to push AppMetrics events through to Seq using a simple _output formatter_ but I am wondering if this integration should be done as a _reporter_ instead? What is gained by implementing as a reporter vs an output formatter with an existing reporter (HTTP in my case)?

Thanks for any guidance,

n

**Comment by alhardy** [comment]
Writing to Seq via an output formatter using the existing HTTP reporter is fine, it exists for this type of reusability. Some TSDBs have specific requirements, support mulitple formats or don't support HTTP, therefore reporter implementations also exist.

Seq/Serilog are awesome libraries, would love to see this done.

@nblumhardt would love to see a managed version of Seq ;)

**Comment by nblumhardt** [comment]
> would love to see a managed version of Seq ;)

On the (rather long!) list, @alhardy :-)

Using a Serilog sink adds a bit of overhead, plus pulls in a Serilog dependency (may not be to everyone's tastes).

Is there a path to contributing an implementation? I'd love to have a shot at it if no one else has beaten me (@nskerl?). Also could contribute a Seq license to the project, in case it'd help with testing (although the free single-user version is there, too).

**Comment by nskerl** [comment]
@nblumhardt So far I've only used the output formatter -> HTTP reporter.  The formatter we are using is mapping metrics onto our existing (and rather flawed) convention for sensor data, so I doubt its of much value to a generic use lib. I'd like to hear how you would design a Seq opinionated reporter.

@alhardy I did find a Serilog sink in use here: https://github.com/serilog-metrics/serilog-metrics

Thanks to both of you for the feedback.

**Comment by alhardy** [comment]
@nblumhardt 
> On the (rather long!) list

There's always a long list :)

> Is there a path to contributing an implementation?

Added you as a collaborator - https://github.com/AppMetrics/Seq

> Also could contribute a Seq license to the project

Thanks! Free single user version is fine though.

@nskerl 

Thanks for pointing the serilog reporter out. 

Agree not everyone would want a serilog dependency.

**Comment by nblumhardt** [comment]
Thanks @alhardy - should have some time to dig in later this week :-)
