### ISSUE TITLE
Appmetric's logs

### ISSUE THREAD

**Issue by meg0man** [AppMetrics/AppMetrics#296]
I use AppMetrics and Serilog for metrics and logging in my web application. In my kibana dashboard I noticed lots of logs from AppMetrics mainly from [App.Metrics.Scheduling.DefaultMeterTickerScheduler](https://github.com/AppMetrics/AppMetrics/blob/dev/src/App.Metrics.Core/Scheduling/DefaultMeterTickerScheduler.cs). I have not found any way to disable this but to add filter in Serilog's configuration.    

I don't want to collect this kind of logs so are there any way to configure AppMetrics to disable these logs?

**Comment by alhardy** [comment]
It is trace level logging, are you running with trace level logging outside of development? That's a lot of logging if so.

At the moment yes, if using serilog to disable app metrics logs you'll need to add a serilog filter

**Comment by meg0man** [comment]
Yes, I include trace level(verbose) logging outside of development, can't remember why such decision was made. Well, thank you, approach with serilog's filter is suitable for me.

I'm wondering what if I use other logging framework, will I receive App.Metrics's logs?

**Comment by alhardy** [comment]
I'm using [LibLog](https://github.com/damianh/LibLog) internally, which works with the most common .net logging libraries out-of-box
