### ISSUE TITLE
how to get container names in dokcer 

### ISSUE THREAD

**Issue by kongkong56** [AppMetrics/AppMetrics#298]
the serverTag is get envinfo.machinename,but the tag is container id in docker.
 public static MetricsOptions AddServerTag(this MetricsOptions options, string serverName = null)
        {
            if (!options.GlobalTags.ContainsKey("server"))
            {
                options.GlobalTags.Add("server", serverName ?? EnvInfo.MachineName);
            }
            else
            {
                options.GlobalTags["server"] = serverName ?? EnvInfo.MachineName;
            }

            return options;
        }
Before logging a new issue, please have a quick read through the [contribution guidlines](https://github.com/alhardy/AppMetrics/blob/master/CONTRIBUTING.md).

**Comment by alhardy** [comment]
You can define you're own tags on startup, see https://www.app-metrics.io/getting-started/fundamentals/tagging-organizing/
