### ISSUE TITLE
Repo for new AppMetrics extension

### ISSUE THREAD

**Issue by hanwavefront** [AppMetrics/AppMetrics#299]
I am writing an extension to App Metrics that will allow for reporting to [Wavefront](https://www.wavefront.com/), and I'm interested in putting it in a repo under AppMetrics (say AppMetrics/Wavefront).  What would the process be for that?  Thanks.

**Comment by alhardy** [comment]
Cool, I guess start implementing it that we can talk about bringing it in

**Comment by hanwavefront** [comment]
I have an early build ready to go -- you can check it out at https://github.com/wavefrontHQ/wavefront-appmetrics-csharp-sdk.  Let me know what you think and what the next steps would be.  Thanks!

**Comment by alhardy** [comment]
Looks good. We could leave this under your GitHub account and add to docs as a contribution package, thoughts? 

Can PR your documentation
https://github.com/AppMetrics/Docs.V2.Hugo

**Comment by hanwavefront** [comment]
Thanks Allan!  How do you envision this fitting into the docs -- as an additional page under Metrics Reporters?  Since all the existing reporters in the doc are under your account, I was thinking that it would make sense to put this there as well, and update the Wavefront repo so that it links to yours.  What do you think?

**Comment by alhardy** [comment]
Sounds good
