### ISSUE TITLE
Is instance created by `new MetricsBuilder().Build()` threadsafe

### ISSUE THREAD

**Issue by nhathongly** [AppMetrics/AppMetrics#302]
I want to use AppMetrics in my ASP.Net Web API 2 by implementing a custom `FilterAttribute` to count number of requests which satisfy specific conditions. I wonder if instance created by `new MetricsBuilder().Build()` is threadsafe. Is there any problem if I use it as a static field in the custom `FilterAttribute` so that all requests will share the same IMetrics instance?

**Comment by alhardy** [comment]
Yes, the same `IMetrics` instance should be shared by design.
