### ISSUE TITLE
Add ability to provide time measurement to IMeasureTimerMetrics.Time()

### ISSUE THREAD

**Issue by joshclark** [AppMetrics/AppMetrics#304]
The `IMeasureTimerMetrics` interface allows the user to provide either an Action method that will be executed and then the time to execute will be recorded or the user can get back an IDisposable that will record the metric when `Dispose()` is called.

I'd like to have a third way to record the time:  Let the caller just specify the duration directly.  The API would look something like this:
``` csharp
  void Time(TimerOptions options, MetricTags tags, long time);
```
The implementation would basically just call `ITimer.Record` similar to how the Action and TimerContext versions do.

Why do I want something like this?
I have a user asking for the ability to 
1. Disable the metric generation with the TimerContext is disposed.  Basically they want to have the context in a using block but then be able to say `context.Enabled = false` if they determine that the metric should not be recorded.
2. Add tags after the timer has started.  Specifically, they want to add an "isSuccessful" tag to be able to tell which times represent successful calls and which ones represent failures.  "I don't care how fast my page renders when I can't talk to the database."

My solution for both of these was to provide my own TimerContext-like IDisposable.  My api that wraps appmetrics would return this new context type and have the ability to add new tags on the fly and to disable the recording of the metric.  Basically I would do nothing in the "Start Timer" call other than record `IClock.Nanoseconds`.  In my context's Dispose call, I could check if I was still enabled, and if so create a new timer with `_metricRoot.Measure.Timer.Time(name, tags, totalTime);`

Thoughts on this approach?  Would you be interested in a PR for this?  Is there a better solution?

**Comment by alhardy** [comment]
Sounds reasonable to me, happy for a PR

**Comment by megakid** [comment]
I would also be keen to see this as I am trying to retrofit an application with AppMetrics (great lib by the way) and we already have various timer outputs that are measuring performance that I want to post to AppMetrics without using it's own timing methods.

**Comment by alastrange** [comment]
Interested in this as well.  Specifically, I would like to include a response code as a tag in a timed event.  As it exists right now with the defaults, tags must be finalized _before_ a timed event.
