### ISSUE TITLE
Sample with .Net 4.5.2 Web API and reporting to ElasticSearch/Http

### ISSUE THREAD

**Issue by MartinBodocky** [AppMetrics/AppMetrics#305]
Hi guys,

I would to know if I can build metric listener for Web API project .Net 4.5.2 which doesn't using Owin (or can use only Startup.cs). I have looked into your old examples, but those nuget packages are not existing any more.

Thank you for your help in advance,

Martin Bodocky

**Comment by alhardy** [comment]
App Metrics core packages target `netstandard1.6` so yes that would be possible.
