### ISSUE TITLE
Question - InfluxDB - How do I get the get the number of HTTP requests received between a specific start and end date/time?

### ISSUE THREAD

**Issue by adrian-ubalde** [AppMetrics/AppMetrics#306]
I have a question regarding the metrics that are pushed into InfluxDB. I'm looking for an InfluxDB measurement that I can query to get the number of HTTP requests received between a specific start and end date/time. Would the `application.httprequests__active` measurement be the correct measurement to query? E.g. `SELECT SUM(value) FROM "application.httprequests__active" WHERE time >= 1534225371930ms AND time <= 1534225401930ms AND app = 'MyApp'`

**Comment by alhardy** [comment]
I assume we're referring the the default metrics recorded by the asp.net core middleware. The active request count metric is the number of concurrent requests so not what you're after.

The default middleware doesn't provide a way really to measure the number of HTTP request over a give period. Even if using the counters recorded by meters in the default middleware, they are cumulative counts.

It should be simple enough to write a custom middleware to simply track a counter which auto-resets on flushing metrics, e.g. https://github.com/AppMetrics/AspNetCore/blob/dev/src/App.Metrics.AspNetCore.Tracking/Middleware/ActiveRequestCounterEndpointMiddleware.cs#L36

https://www.app-metrics.io/getting-started/metric-types/counters/#counter-reporting-options

**Comment by adrian-ubalde** [comment]
Yes your assumption is correct. Thanks for clarifying what `httprequests__active` is and for your suggestion on how to track the HTTP request count over a period.
