### ISSUE TITLE
Possible to have the metrics endpoint is a non-.Net Core Project?

### ISSUE THREAD

**Issue by mts57017** [AppMetrics/AppMetrics#307]
Is it possible to have the metric endpoints in a project that is NOT ASP.NET Core? Is so, how?

**Comment by alhardy** [comment]
The default middleware is written using asp.net core. You could implement equivalents in any version of the .net framework support `netstandard1.6`

**Comment by mts57017** [comment]
Gotcha. So currently, there is no way to use this in a project that is not based around .net core?

Regards,

Matthew Schneid
Senior Software Engineer
803.968.3823
Revionics
________________________________

**Comment by alhardy** [comment]
It is possible to use this project outside of .net core.

The web extensions part of it is written with asp.net core middleware though, equivalent would need to be written for owin middleware for example

**Comment by alhardy** [comment]
Closing this one out, I don't have capacity to maintain tracking middleware for older frameworks but should be easier enough to roll custom middleware tailored to your needs
