### ISSUE TITLE
System.Collections.Generic

### ISSUE THREAD

**Issue by jonmeyerny** [AppMetrics/AppMetrics#310]
DictionaryExtensions in System.Collections.Generic clashes with the name of a similar class in the same namespace in one of our other class libraries --- it is also potentially confusing if adding App.Metrics to a project also modifies System namespace. Can this be changed?

**Comment by alhardy** [comment]
Painful :( Sure will look into it

**Comment by jonmeyerny** [comment]
Thanks Allan.  That's great.

We have a reasonably large codebase and so adding a new core dependency tends to be controversial - it impacts deployments to e.g. Excel, Python, servers and ClickOnce.

Other than polluting namespaces, another other issue I've noticed is that App.Metrics is split into lots of small DLLs, with 12 different projects across 4 different Nuget packages in our use case. I think one reason folks like Newtonsoft Json is that it bundles everything you need into a single DLL with no dependencies ... Easy to add or update. For App.Metrics, I downloaded the AppMetrics, Concurrency, Elasticsearch and InfluxDB packages and then made a custom .csproj file to build the src from all of these in a single dll. I'll try going with this for now. If you decided to produce a unified bundle down the road we would then use that via a Nuget reference...  Cheers -- Jon

**Comment by alhardy** [comment]
The side effect of including everything in one assembly is forcing client dependencies on this they don't want referenced. E.g. initially app metrics had a hard dependency on Microsoft DI which was requested by some to remove, also I wouldn't be able to support lower versions of the .net framework in core packages if having a single assembly.

I've tried to simplify dependencies by using packages that bootstrap the most common features allowing clients to reference the one package e.g https://www.nuget.org/packages/App.Metrics.AspNetCore
