### ISSUE TITLE
ResetOnReporting does nothing

### ISSUE THREAD

**Issue by GadgetGeekUK** [AppMetrics/AppMetrics#314]
When defining a counter you can set CounterOptions property 'ResetOnReporting' to true like this:

```
            public static CounterOptions ReceivedMessages => new CounterOptions
            {
                Context = ContextName,
                Name = "Fetching",
                MeasurementUnit = Unit.Items,
                ResetOnReporting = true
            };
```

However, when the metrics are flushed, the counters are not reset, and will be cumulative with the next set of values.

You can force a reset when you configure an 'AppMetricsTaskScheduler', but in doing so you are overriding this property and have to name the individual counters:

```
            var scheduler = new AppMetricsTaskScheduler(
                TimeSpan.FromSeconds(5),
                async () =>
                {
                    await Task.WhenAll(((IMetricsRoot) metrics).ReportRunner.RunAllAsync());
                    metrics.Provider.Counter.Instance(MetricsRegistry.MyMetrics.ReceivedMessages).Reset();
                });
            scheduler.Start();
```

How should the 'ResetOnReporting' actually be used??

**Comment by alhardy** [comment]
Try using the [`MetricsSnapshopSerializer`](MetricsInfluxDBLineProtocolOutputFormatter.cs) on the `MetricsDataValueSource`

**Comment by GadgetGeekUK** [comment]
If I use the MetricSnapshotSerializer, the Serialize method will no longer take a JsonTextWriter as it's JSON output I require. I currently use:

`JsonSerializer.Create(_serializerSettings)`

**Comment by mortengjesing** [comment]
I have the same problem, I use the Http reporter with the MetricsJsonOutputFormatter

**Comment by mortengjesing** [comment]
I have made a pull request to fix the problem https://github.com/AppMetrics/AppMetrics/pull/369

**Comment by mortengjesing** [comment]
There was also a problem with ReportSetItems & ReportItemPercentages - i have fixed that as well.
