### ISSUE TITLE
Use with Docker containers in AWS

### ISSUE THREAD

**Issue by dawson1990** [AppMetrics/AppMetrics#315]
Im using App.Metrics.AspNetCore.Tracking to gather metrics on a service, this service is hosted in AWS and due to Auto Scaling there can be multiple hosts spun up or tore down, the metrics are then logged to Cloudwatch and exported via Lamba to Kibana. When there are multiple hosts spun up (say 3 for example), there are 3 different sets of metrics, one per host, being sent to Kibana.  

Is there  a way to combine all these hosts metrics into one ?  Not sure if even possible but just asking

**Comment by alhardy** [comment]
It all depends on how you're logging to Cloudwatch and what it supports in terms of tagging. AppMetrics supports multi-dimentional metrics through tagging
