### ISSUE TITLE
Is there any actual documentation?

### ISSUE THREAD

**Issue by Rast1234** [AppMetrics/AppMetrics#316]
I was trying to figure out how to set up simple reporting to influxdb in aspnetcore2 application. Current docs on github pages and a bunch of articles i was able to find seem to refer to 1.x version of AppMetrics, right? Samples in repo are outdated too, and some links from docs to samples lead nowhere.

Am i missing something?

I believe AppMetrics is very useful and beautiful tool, but i decided to move on to something else, because without proper docs and samples it is difficult to decide if it's going to work as expected.

Also there are a lot of AppMetrics nuget packages, not sure when to install which, and it is not documented either.

**Comment by alhardy** [comment]
https://www.app-metrics.io

Links to the latest samples are on the docs site
