### ISSUE TITLE
Counter or Histogram value provider

### ISSUE THREAD

**Issue by fatagun** [AppMetrics/AppMetrics#318]
I am building some metrics and registering them on app start as following:

```
_metricsRoot.Provider.Gauge.Instance(
                ClrMetricsRegistry.VirtualMemorySize64,
                () => new FunctionGauge(() => ClrMetricsValueProvider.GetVirtualMemorySize64()));
```

ClrMetricRegistry has the following GaugeOptions:

```
        public static readonly GaugeOptions VirtualMemorySize64 = new GaugeOptions
        {
            Name = "private_memory_size_64",
            Context = context,
            MeasurementUnit = Unit.Bytes
        };
```
ClrMetricsValueProvider has the following value provider:

```
        public static double GetVirtualMemorySize64()
        {
            var process = Process.GetCurrentProcess();
            return process.VirtualMemorySize64;
        }
```

This works great. How I can do the same for Counters and Histograms?

I am able to use `FunctionGauge ` for gauges. But not sure what I need to use for counter and histograms.

```
_metricsRoot.Provider.Counter.Instance(
               ClrMetricsRegistry.ThreadCount,
               () => **What comes here**);
```

Can you please elaborate?

Thanks.

**Comment by fatagun** [comment]
hello ?

**Comment by alhardy** [comment]
What's your use case for taking that approach with histograms and counters?

**Comment by fatagun** [comment]
Well I for example, I would like to report thread count. Every time report scheduler runs and logs, I want to see the current CLR thread count. 

The API for gauges provides that but not sure how to do it for counter or histogram data.

Thank you.

**Comment by alhardy** [comment]
The API unfortunately only supports this approach for gauges, if you want a count you could sum the gauge reported via your TSDB. 

You could also schedule updates to these metrics yourself
