### ISSUE TITLE
1, 5 and 15 minute percentage values with meter?

### ISSUE THREAD

**Issue by Kikimora** [AppMetrics/AppMetrics#322]
Hi All! Hopefully you can help me out with one thing. I want to generate app health status based on percentage of failed requests during last minute. I thought it is a good idea to use meter metric to calculate it. But I cannot figure out how to get 1 minute percentage (not rate) from it. Is this even possible with Meter metric?

**Comment by alhardy** [comment]
Have a look at the middleware provided in the asp.net core repo for ideas https://github.com/AppMetrics/AspNetCore/tree/dev/src/App.Metrics.AspNetCore.Tracking/Middleware

Not quite what you're after, but also look at the `Apdex` metric https://www.app-metrics.io/getting-started/metric-types/apdex/

**Comment by BCsabaEngine** [comment]
Something external lib like this: https://github.com/BCsabaEngine/metrics-1-5-15 ?
