### ISSUE TITLE
Are there any plans to support 'Health Check Response Format for HTTP APIs' ?

### ISSUE THREAD

**Issue by prochnowc** [AppMetrics/AppMetrics#324]
Hi,

are there any plans to support the 'Health Check Response Format for HTTP APIs' (https://datatracker.ietf.org/doc/draft-inadarei-api-health-check/) response formats in the future?

Thanks for this nice library!

**Comment by alhardy** [comment]
Interesting, I didn't know there was an RFC.

Happy to have a look, thanks for dropping the link

**Comment by alhardy** [comment]
Planning to remove the health check related implementation due to there being a Microsoft equivalent
