### ISSUE TITLE
[Feature] At run time, enable/disable recording of metrics by name or context

### ISSUE THREAD

**Issue by Jeremiah-Reyer** [AppMetrics/AppMetrics#325]
We would like to be able to enable and disable recording of metrics that have already been defined in our registry.  It looks like the current functionality for disabling metrics at runtime only disables the recording of ALL metrics and does not provide a way to re-enable them at runtime.  We would like to be able to enable and disable subsets of metrics by their name or context.

**Comment by alhardy** [comment]
It's possible to filter metrics from reporting but not disable. In what scenarios are you thinking that disabling individual metrics would be useful?

**Comment by Jeremiah-Reyer** [comment]
It would be useful for our users to have that level of control, so they can improve performance by opting out of recording metrics that they don't need.

**Comment by alhardy** [comment]
Could implement some type of no-op/disable option on `MetricsOptions`, not something I've needed myself thus far though so won't implement myself, will happily take a PR though
