### ISSUE TITLE
Unable to see logs

### ISSUE THREAD

**Issue by Lanayx** [AppMetrics/AppMetrics#326]
I can't see appmetrics' logs.  I know you are using liblog and if I use it myself it works. However it doesn't work with appmetrics' logs. Here is an example:

```
            XmlConfigurator.Configure(
                LogManager.GetRepository(Assembly.GetAssembly(typeof(LogManager))),
                new FileInfo("log4net.config"));

            var log = LogManager.GetLogger(typeof(Program)); // log4net way
            var logger = LogProvider.For<Program>();  //liblog way

            log.Info("Test1");
            logger.Info("Test2");
```
Both Test1 and Test2 are visible when I do `using MyProj.Logging`, but only Test1 when I do `using App.Metrics.Logging`. Could you probably provide any repo where AppMetrics is used and it's logs are produced well?

**Comment by alhardy** [comment]
Check any one of the sandbox projects in one of the repo, they all having logging configured (using Seq). App Metrics usings LibLog internally which supports log4net
