### ISSUE TITLE
Logging metrics across service / process / thread boundaries

### ISSUE THREAD

**Issue by permatth** [AppMetrics/AppMetrics#327]
Hi,

I currently try to log metrics in an existing system that comprises a lot of different services, processes and threads.  So far I have been using AppMetrics individually in each service / assembly, but now I am at the point where I have a metric which requires counting across the boundaries of services / assemblies.  That is, I need to operate on a metric from different, independently running services.  Only possibility I currently see is with an extra measurement service which provides access to the shared metrics.  Other options?    Any best practices how to do that?

**Comment by alhardy** [comment]
Could you just use the same metric name?

**Comment by permatth** [comment]
Using the same metric name and context is what I try to achieve.  The issue is that the different services and assemblies start independently from each other.  Hence, I do not know how to obtain a common IMetricsRoot (or similar) across the different services and assemblies.

**Comment by alhardy** [comment]
What's the reasoning and what would you like to achieve by "obtain a common IMetricsRoot (or similar) across the different services and assemblies."?

**Comment by bdrupieski** [comment]
It sounds like you might want to use Prometheus, which can aggregate metrics across different sources. You can then query on metrics from multiple sources in a single place, to do things like alert on them. This would basically be the measurement service you're considering, but is an off-the-shelf solution instead of rolling your own.

**Comment by permatth** [comment]
> What's the reasoning and what would you like to achieve by "obtain a common IMetricsRoot (or similar) across the different services and assemblies."?

The reasoning is that I would like to have common counters / meters / etc across the different services and assemblies.  

The situation is that in the system I try to monitor there are, depending on the configuration different mechanisms are used to spawn of expensive tasks that might run for a very long time.  One of these mechanisms is to start new proscesses that run the code from different assemblies depending on the task to be done.  Does that help to understand my problem?  

For one of the metrics I found a workaround by querying an external state whenever I report metrics.  However  these queries are far from optimal, because they have to query big data sets in a database instead of being able to observe the changes to the database directly in the updating tasks.
