### ISSUE TITLE
Schedule collection of metrics

### ISSUE THREAD

**Issue by ben-foster-cko** [AppMetrics/AppMetrics#328]
Hi,

Does AppMetrics support scheduling the collection of metrics similar to the Prometheus .NET library's collector?

I'd like to register some metrics such as memory usage that get collected each time the metrics endpoint is hit.

**Comment by alhardy** [comment]
The supported reporters collect metrics and push on a schedule yes.

Prometheus support in app metrics is just to expose metrics in Prometheus format, it doesn't support scraping metrics in a separate process yet.

**Comment by ben-foster-cko** [comment]
@alhardy thanks, do you have any examples/docs of the reporters?

**Comment by alhardy** [comment]
https://www.app-metrics.io/reporting/

There's a sample project in each of the reporting repos

**Comment by ben-foster-cko** [comment]
I couldn't see an example of this for Prometheus so just to clarify, are you saying there is no way of setting up reporters for prometheus each time the metrics endpoint is invoked?

**Comment by alhardy** [comment]
App Metrics doesn't provide push functionality for Prometheus, the typical way to ingest metrics to Prometheus is to pull. I don't have any plans to implement an integration with Prometheus pushgateway https://prometheus.io/docs/instrumenting/pushing/
