### ISSUE TITLE
What happens if the http reporter is pointed at an invalid URL?

### ISSUE THREAD

**Issue by mts57017** [AppMetrics/AppMetrics#332]
Hello,

What happens if if the http reporter is pointed to an invalid url? I noticed that if you don't include a url at all, the points where a counter or timer is recorded throws an error because the metricsroot is null. So my thought is is to point the url to something like localhost until we had an endpoint ready to go.

Thoughts?

**Comment by alhardy** [comment]
Off the top of my head, errros will be logged and the retry/back-off policy will kick in.

If you want to deploy without reporting over http to start with you could just feature flag it
