### ISSUE TITLE
Feature suggestion: contextual tags

### ISSUE THREAD

**Issue by aidansteele** [AppMetrics/AppMetrics#334]
Hi,

Firstly: thanks for the great library. I have been thinking it would be useful to add support for contextual (maybe "scoped" is a better term) tags. Right now our options for adding tags are either:

* Globally at `MetricsBuilder` configuration time
* Locally at the call-site of a metrics invocation, i.e. as a parameter to `Increment()` etc.

There are times where it would be useful to have something in the middle. A recent example is #300 wherein they wanted the ability to add "user id" or "device" tags. It would be handy if we could do that at an earlier stage (e.g. middleware in a web app) and all subsequent metrics calls inherit those tags. Example code:

```csharp
public class UserIdTagsEnrichmentMiddleware
{
	private readonly RequestDelegate _next;
	private readonly IMetrics _metrics;

	public UserIdTagsEnrichmentMiddleware(RequestDelegate next, IMetrics metrics)
	{
		_next = next;
		_metrics = metrics;
	}

	public Task Invoke(HttpContext context)
	{
		var tags = new MetricTags(new[] {"user_id", "user_type"}, new[] {"1234", "paid"});
		using (_metrics.PushTags(tags))
		{
			await _next(context);
		}
	}
}
```

In terms of implementation, we could use `AsyncLocal<T>` in .Net Standard and `CallContext` in .Net 4.5.2 to maintain a stack of contextual tags. This is how Serilog's [`LogContext`](https://github.com/serilog/serilog/blob/dev/src/Serilog/Context/LogContext.cs) does it. 

What do you think? If you think the idea is worthwhile, I'd be very happy to submit a PR for you to review and make changes as you see fit.

**Comment by alhardy** [comment]
Hi @aidansteele,

Happy you find it useful.

Happy for this as a new feature and more than happy for a PR 😉

Example code looks good to me.

**Comment by aidansteele** [comment]
Thanks for the speedy response @alhardy! I'll try to get an initial version of this submitted quite soon 👍

**Comment by aidansteele** [comment]
Sorry for the delayed response. I started working on this today and came up with a few questions that I'd like to clarify before continuing with the PR.

What's the purpose of context labels? Specifically, how are they distinct from tags?

Why does `MetricTags` have arrays of strings for keys and values, instead of perhaps a `Dictionary<string, string>`? https://github.com/AppMetrics/AppMetrics/blob/9adf17a6fa99052f3379af73d416efe33508f639/src/App.Metrics.Abstractions/MetricTags.cs#L15-L18

The JSON formatter calls `MetricTags.ToDictionary()`, which has the following line: https://github.com/AppMetrics/AppMetrics/blob/9adf17a6fa99052f3379af73d416efe33508f639/src/App.Metrics.Abstractions/MetricTagExtensions.cs#L44

This will return an `ArgumentException` if the key already exists, e.g. if there are already global or scoped tags with the same key. Would this still be the desired behaviour, or would we want to prefer most specific tags over the least specific?

Sorry for all the questions, but I figure I should first understand the rationale for the current implementation before making any changes.

**Comment by alhardy** [comment]
> What's the purpose of context labels? Specifically, how are they distinct from tags?

Context labels are used as part of the metric name, sort of acting like a namespace or category.

> Why does MetricTags have arrays of strings for keys and values, instead of perhaps a Dictionary<string, string>?

This was done some type ago, unfortunetly can't recall the reasoning. Planning to review this at some stage.

> This will return an ArgumentException if the key already exists, e.g. if there are already global or scoped tags with the same key. Would this still be the desired behaviour, or would we want to prefer most specific tags over the least specific?

I think `ArgumentException` is fine to avoid confusion if there are duplicates

**Comment by aidansteele** [comment]
Thanks for your feedback @alhardy. Now I have the confidence to proceed with the PR. Will try to get it soon, just foresee a bit of a mad scramble when I return to work this week :)

**Comment by AvivRubys** [comment]
Was any progress made on this? This feature would be a godsend for me right now :)

**Comment by AvivRubys** [comment]
This looks dead, so I've started working on it myself.
I've written the core of it, the part that can push new tags and remove them when exiting the scope.
I'm wondering how to expose it in `IMetrics` - Just a plain method like shown in the OP, or perhaps as a method under one of the existing services? `IManageMetrics` looks roughly right but I don't really understand the responsibilities of each service.
Any thoughts on this @alhardy ?

**Comment by WalissonPires** [comment]
Any news for this feature?

**Comment by suntereo** [comment]
The original middleware prototype example from aidansteele shows access to HttpContext. But there does not seem to be any good way to gain access to HttpContext with the current solution (Contextual tags #552).

For example, this is not ideal:

```
services.AddMetrics(metricsBuilder =>
{
    metricsBuilder.Configuration.Configure(options =>
    {
        options.AddServerTag();
        options.ContextualTags.Add("someTag", () =>
        {
            var sp = services.BuildServiceProvider(); //<-- not ideal; but how to get HttpContext??
            var httpContextAccessor = sp.GetRequiredService<IHttpContextAccessor>();
            return "something from http context";
        });
    });
});
```

Am I missing something? Or is this an oversight?
