### ISSUE TITLE
Bootstrapping Startup.cs configuration on ASP.NET Core 2.1

### ISSUE THREAD

**Issue by fabricioveronez** [AppMetrics/AppMetrics#335]
Hi, I have been tried to config the Web Metrics in an ASP.NET Core 2.1 application. When I used the Program.cs approach which worked well. On the other hand, when I tried Startup.cs approach doesn't happen. I have followed the example at the web site but the AddMetricsReportScheduler doesn't work in ASP.NET Core 2.1. Could you explain to me how to configure ?

**Comment by alhardy** [comment]
Have you added the hosted service? https://github.com/AppMetrics/MicrosoftExtensions/blob/dev/src/App.Metrics.AppNetCore/MetricsConfigureHostBuilderExtensions.cs#L39

**Comment by alhardy** [comment]
Thanks for pointing that out @marekhanzlik 

Will update the docs

**Comment by fabricioveronez** [comment]
I have replaced services.AddMetricsReportScheduler() by services.AddMetricsReportingHostedService() and It work. Thanks for help !!!

**Comment by LeonidVasilyev** [comment]
It looks like current documentation still doesn't state that you need to use `ServiceCollectionMetricsReportingExtensions.AddMetricsReportingHostedService()` from  `App.Metrics.Extensions.Hosting` NuGet package.

**Comment by danilobreda** [comment]
https://www.app-metrics.io/web-monitoring/aspnet-core/reporting/ is with the old and wrong method.
