### ISSUE TITLE
Postgres or TimescaleDb reporting

### ISSUE THREAD

**Issue by Kikimora** [AppMetrics/AppMetrics#337]
Hi, I have [TimescaleDb](https://www.timescale.com/) in my app stack and would like to avoid additional dependencies (read influx, graphite, etc). I wonder is there is any samples how to push data from AppMetrics into relational database like Postgres?

**Comment by alhardy** [comment]
I don't have any examples but it should be straight forward to implement a new reporter. Have a look at one of the existing reporters for guidance

**Comment by alhardy** [comment]
No plans to implement any new reporters, would be great to see that done outside the core library in which case I'd be more than happy to include in App Metrics documentation
