### ISSUE TITLE
Example of mocking IMetrics

### ISSUE THREAD

**Issue by ben-foster-cko** [AppMetrics/AppMetrics#338]
Do you have an example of how to mock IMetrics (specifically, timer)?

**Comment by alhardy** [comment]
What's the scenario for mocking?

**Comment by ThomasSiigNoergaard** [comment]
We have the following simplified scenario, where IMetrics is injected into the controller via built-in DI i dotnet core.

```
    private readonly IMetrics _metrics;

    public xController(IMetrics metrics)
    {
      _metrics = metrics;
    }

   public ActionResult Get(int id)
    {
      _metrics.Measure.Counter.Increment(MetricsRegistry.QueryCounter);
      ...
   }
```

Can this be mocked in any way?

**Comment by LordMike** [comment]
Hey @alhardy -- was there an official way to do this?

In our use case, we want to enable metrics in some instances, but be able to disable or enable it at runtime using feature flags. But to keep the rest of the code identical, we still want to inject `IMetrics`.

I think we'll end up mocking small snippets of interfaces such that we have a minimal `IMetrics` with all associated parts, that just no-op.
