### ISSUE TITLE
CompatibilityVersion.Version_2_2 not fully supported - missing full API paths

### ISSUE THREAD

**Issue by rgueldenpfennig** [AppMetrics/AppMetrics#340]
Since the release of .NET Core 2.2 it is possible (and recommended) to set the `CompatibilityVersion` to `Version_2_2`.

My StartUp.cs of a newly created ASP.NET Core app looks like this:

```
services.AddMvc()
        .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
        .AddMetrics();
```

Program.cs:
```
var metrics = AppMetrics.CreateDefaultBuilder()
    .OutputMetrics.AsPrometheusPlainText()
    .Build();

return WebHost.CreateDefaultBuilder(args)
    .ConfigureMetrics(metrics)
    .UseMetrics(
        (context, options) =>
        {
            options.EndpointOptions = endpointsOptions =>
            {
                endpointsOptions.MetricsTextEndpointOutputFormatter = metrics.OutputMetricsFormatters.GetType<MetricsPrometheusTextOutputFormatter>();
            };
        })
    .UseMetricsWebTracking()
    .ConfigureLogging(
        (context, builder) =>
        {
            builder.ClearProviders();
            builder.AddConfiguration(context.Configuration.GetSection("Logging"));
        })
    .UseStartup<Startup>()
```

When doing so the metric collection seems to not be able to determine the original route anymore. Only the variables (like GET, PUT, POST) are collected.

**Comment by bdrupieski** [comment]
It has to do with the endpoint routing stuff added in 2.2. The way it's determining the path no longer works starting in 2.2.

If you set the compatibility mode to 2.1 or earlier it will work.

**Comment by bdrupieski** [comment]
If you only use attribute-based routing (e.g. `[HttpGet("hello/there/{id}")]`, using something like this will work with endpoint routing enabled and compatibility version 2.2:

```
public class MetricsResourceFilter : IResourceFilter
{
    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        var templateRoute = context.ActionDescriptor?.AttributeRouteInfo?.Template;

        if (!string.IsNullOrEmpty(templateRoute))
            context.HttpContext.AddMetricsCurrentRouteName(context.ActionDescriptor.AttributeRouteInfo.Template);
    }

    public void OnResourceExecuted(ResourceExecutedContext context)
    {
    }
}
```

From poking around some ASP.NET Core GitHub discussions it sounds like what we'd need to completely address this is still internal to the routing implementation in ASP.NET Core 2.2. They're thinking of how to build out extensibility in the future to achieve what was possible with `IRouter` before.

Until then, maybe something like the above combined with a fallback to {ControllerName}.{ActionName} is a good stop-gap short term 80% solution.

**Comment by alhardy** [comment]
https://github.com/AppMetrics/AspNetCore/commit/008964cd35ad9e69c646fd5e1beb56e445750ad4
