### ISSUE TITLE
Feature request: Add Azure Monitor reporter

### ISSUE THREAD

**Issue by rikbosch** [AppMetrics/AppMetrics#342]
Azure Monitor has added support for custom metrics.

It would be great if appmetrics could directly report it's metrics to azure. (It is already possible to report metrics through Application Insights see https://docs.microsoft.com/nl-nl/azure/application-insights/app-insights-api-custom-events-metrics#getmetric)

documentation:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview

Azure montior already has an adapter for telegraph, can AppMetrics use telegraph for reporting? If so, is there an example of howto use it?

**Comment by alhardy** [comment]
There has been a feature request for this before, unfortunately I don't have capacity to implement it but would love a PR.

Re telegraf https://github.com/AppMetrics/Reporting/pull/50

**Comment by vip32** [comment]
this blog describes an example how to POST metrics to Azure Monitor

https://blog.kloud.com.au/2019/01/16/automating-azure-instrumentation-and-monitoring-part-3-custom-metrics/

has any work on the AM reporter already started?

**Comment by alhardy** [comment]
No work has been started on an Azure monitor reporter

**Comment by vip32** [comment]
is there still any interest for a AM reporter?

**Comment by alhardy** [comment]
@vip32 there has been a few requests

**Comment by alhardy** [comment]
https://github.com/jdvor/appmetrics-applicationinsights
