### ISSUE TITLE
Can not writing metrics to InfluxDb

### ISSUE THREAD

**Issue by HakanKaraoglu** [AppMetrics/AppMetrics#345]
Hi,

I read the document for the implementation of InfluxDB.Application working and see metrics but I can not write of InfluxDB. My project Asp.Net Core MVC

Nuget Packages :
`   <PackageReference Include="App.Metrics.AspNetCore.Core" Version="3.0.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Health.Core" Version="2.1.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Health.Endpoints" Version="2.1.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Mvc" Version="3.0.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Reporting" Version="3.0.0" />
    <PackageReference Include="App.Metrics.AspNetCore.Tracking" Version="3.0.0" />
    <PackageReference Include="App.Metrics.Reporting.InfluxDB" Version="3.0.0" />
`
Program.cs :
`public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseHealthEndpoints()
                .UseMetrics()
                .UseMetricsWebTracking()
                .UseStartup<Startup>();
    }
`
Startup.cs :
`public void ConfigureServices(IServiceCollection services)
        {
            var configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile(path: "appsettings.json", optional: false, reloadOnChange: true)
                .Build();

            var influxOptions = new MetricsReportingInfluxDbOptions();
            configuration.GetSection(nameof(MetricsReportingInfluxDbOptions)).Bind(influxOptions);
            influxOptions.MetricsOutputFormatter = new MetricsInfluxDbLineProtocolOutputFormatter();

            var metrics = AppMetrics.CreateDefaultBuilder()
                .Configuration.ReadFrom(configuration)
                .Report.ToInfluxDb(influxOptions)
                .Build();

            services.AddMetrics(metrics);
            services.AddMetricsTrackingMiddleware();
            services.AddMetricsReportingHostedService();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1).AddMetrics();
        }

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseMetricsAllMiddleware();
            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
`

Regards

**Comment by alhardy** [comment]
Have you tried the sample influxdb app? https://github.com/AppMetrics/Samples/tree/master/src/Api.InfluxDB.Sample

**Comment by HakanKaraoglu** [comment]
Hi @alhardy 
It works, thank you very much. But the project you gave me as an example contains old version packages (1.1.0). I want use 3.3.0 package. Can you give me any project for updated package versions?

**Comment by alhardy** [comment]
Or you could reference the samples in the influxdb repo https://github.com/AppMetrics/InfluxDB/tree/dev/sandbox

**Comment by vothanhphu** [comment]
Hi, Can you give the setting at the appsettings.json.
I just make a guide video here. You can check your setting
https://www.youtube.com/watch?v=i4u9SzfSkic&t=43s
