### ISSUE TITLE
Unable to use ElasticSearch Reporter

### ISSUE THREAD

**Issue by marcoschneidertui** [AppMetrics/AppMetrics#347]
Hi,

when trying to create a Reporter for ElasticSearch I receive this exception:

Method 'get_MetricFields' in type 'App.Metrics.Formatters.Elasticsearch.MetricsElasticsearchOutputFormatter' from assembly 'App.Metrics.Formatters.Elasticsearch, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0d5193a913d1b812' does not have an implementation.

Can you please give me an indication when there will be a stable release for elastic search reporting?

Thanks and best regards
Marco

**Comment by walliski** [comment]
I tried out the Elasticsearch reporter also, with no luck. It hasn't been updated to 3.0.0 as the other reporters, and I think the maintainer wrote somewhere that he will not continue supporting it. Also says that he does not have enough time to maintain everything (https://github.com/AppMetrics/Elasticsearch/issues/26).

**Comment by alhardy** [comment]
The elastic search reporter needs some love and yes doesn't work with the latest version of ES

**Comment by alhardy** [comment]
The elastic search reporter hasn't been taken across the the main repo https://github.com/AppMetrics/Elasticsearch. This is up for grabs
