### ISSUE TITLE
Question: Format output as strongly typed POCO. 

### ISSUE THREAD

**Issue by jompa234** [AppMetrics/AppMetrics#348]
I could not get the elastic search reporter working and I understand that it needs some more love. 

I am currently pushing logs to elastic search through Serilog and the elastic search sink. I am doing the same with the metrics via a custom reporter that I wrote that only performs a Log.Logger.Information(metricsData) in the FlushAsync(). 

Right now I am experimenting with pushing the metrics using the json formater and it works well but I have not been able to break the metrics document down to fields. 

I have had a quick look at the Elasticsearch formatter that you have written and I see that there is some custom mappings and such. 

Serilog has the ability to destructure a logged POCO using the destructuring operator @. 
I could use that as a quick way to push the metrics over and get the metrics as separate fields that I can search on and do visualizations on in Kibana etc. 

Do you have any ideas if it is a feasible task to extract the most interesting metrics into a strongly typed POCO that serilog is able to destruct withouth falling back to .ToString() ?

Or is the contents of the MetricsDataValueSource too "abstract", if you know what I mean?

**Comment by alhardy** [comment]
Yes the ES reporter needs some love, I haven't need the reporter myself in my current role, don't have plans to work on the ES reporter any time soon. Would be great to see someone provide the love it needs
