### ISSUE TITLE
Custom value for Timer?

### ISSUE THREAD

**Issue by otto-gebb** [AppMetrics/AppMetrics#351]
How can I record a custom TimeSpan as a value of a Timer?
I have a long-running workflow (aka Saga), and at the end of it I calculate the duration by retrieving the start time from the DB. So the `using(action)` method doesn't work for me.

How can I do something like this?

```
metrics.Measure.Timer.Time(myTimerOptions, myDuration);
```

**Comment by bdrupieski** [comment]
@otto-gebb Does this work for you?
```
metrics.Provider.Timer.Instance(myTimerOptions).Record(myDuration, TimeUnit.Seconds);
```

**Comment by otto-gebb** [comment]
@bdrupieski Perfect! Thank you!
