### ISSUE TITLE
AppMetrics compatibility with Azure Functions

### ISSUE THREAD

**Issue by PedroFcul** [AppMetrics/AppMetrics#353]
I've been using AppMetrics with Azure's Web Applications and it's been working fine, but now i needed to add it to an Azure Function and i didn't find any documentation on how to do it, so i've done it the same way as i would for a Web Application.

The thing is, although my code works fine, I can't find the endpoint for accessing the metrics. 
Which leads me to ask, is there a way to use AppMetrics along with Azure Functions?

**Comment by bdrupieski** [comment]
You can use AppMetrics with Azure Functions but will have to push the metrics somewhere using a reporter. You cannot expose a metrics endpoint with Azure Functions.

**Comment by PedroFcul** [comment]
Yea that was my concern, thanks for the answer, i'll close the issue
