### ISSUE TITLE
What's the point of FlushInterval?

### ISSUE THREAD

**Issue by c-s-n** [AppMetrics/AppMetrics#355]
**Background**
While integrating App Metrics into an ASP.NET Web application, I stumbled over the reporting of collected metrics.

**Problem**
A lot of confusion is imho created by the `FlushInterval` configuration option (mainly `IReportMetrics.FlushInterval`, but also in various reporting options or builders). After some research I found that it seems to be passed around a lot, validity checks are performed on it, unit test for configuring the property are there, but it actually never gets evaluated anywhere! In none of the reporters, not in `DefaultMetricsReportRunner` and also not in `MetricsReporterBackgroundService`, which has its own `WaitBetweenReportRunChecks` time.

That means reporting depends solely on when `IRunMetricsReports.RunAllAsync` resp. the delegated to `FlushAsync` methods get called.

Besides the flush internval being potentially useless, it could also confuse in respect to whether some reporters might automatically flush metrics during runtime (e.g. on measurement).

**Question**
Am I missing something here?
Would it maybe make sense to have e.g. the `DefaultMetricsReportRunner` evaluate the `FlushInterval` of the reporters and even when calling `RunAllAsync` frequently, to internally check for whether it is time to flush again?

**Comment by patrickjozef** [comment]
The MetricsReporterBackgroundService, which takes care of reporting the metrics in an asp .net core project, really uses the FlushInterval. See ; https://github.com/AppMetrics/MicrosoftExtensions/blob/17db892622233670f1269ee3887ecb371c27523c/src/App.Metrics.Extensions.Hosting/MetricsReporterBackgroundService.cs 
on line 58.

SchedulerTaskWrapper has a ShouldRun method, which uses the defined flush interval.
