### ISSUE TITLE
Provide a mechanism to hide metric type name from report

### ISSUE THREAD

**Issue by Hallupa** [AppMetrics/AppMetrics#356]
If I increment a counter called e.g. mycompany.posts, when the counter is reported it changes the name to 'counter.mycompany.posts' so e.g. in Graphite it appear 'counter.mycompany.posts'.

I don't want 'counter' at the start though. I've looked through the source code and it seems the ConcatIntrinsicMetricTags method adds that and I can't see a way of disabling it.

Please can there be a new option to make prepending the metric type name optional

**Comment by alhardy** [comment]
Could you post a code snippet show how you're defining and recording your metric

**Comment by Hallupa** [comment]
So for setting up the metrics I use:

var metrics = new MetricsBuilder()
                .Configuration.Configure(
                    options =>
                    {
                        options.DefaultContextLabel = "sending-agent";
                        options.ReportingEnabled = true;
                        options.Enabled = true;
                    })
                .Report
                .ToGraphite(
                    options =>
                    {
                        options.Graphite.BaseUri = new Uri(graphiteAddress);
                        options.ClientPolicy.BackoffPeriod = TimeSpan.FromSeconds(30);
                        options.ClientPolicy.FailuresBeforeBackoff = 5;
                        options.ClientPolicy.Timeout = TimeSpan.FromSeconds(10);
                        options.FlushInterval = TimeSpan.FromSeconds(10);

                        var metricFields = new MetricFields();
                        metricFields.Counter[CounterFields.Value] = "count";
                        var graphiteOptions = new MetricsGraphitePlainTextProtocolOptions
                        {
                            MetricPointTextWriter = new DefaultGraphitePointTextWriter()
                        };
                        options.MetricsOutputFormatter = new MetricsGraphitePlainTextProtocolOutputFormatter(graphiteOptions, metricFields);
                    })
                .Build();

And for reporting I use:

var sendCounter = new CounterOptions
{
    Name =  "sending-agent.post",
    Context = "com",
    MeasurementUnit = Unit.Calls,
    Tags = MetricTags.Empty,
    ReportSetItems = false
};
metrics.Measure.Counter.Increment(sendCounter);

In Graphite the counter then appears as: counter.com.sending-agent.post.count
but ideally would just want: com.sending-agent.post.count
