### ISSUE TITLE
AppMetrics Grafana dashboard is empty

### ISSUE THREAD

**Issue by mehmetcakmaz** [AppMetrics/AppMetrics#357]
Hi,
I use app metrics (v3.00) in asp.net core 2.2 with prometheus platin text exporter. I tried using grafana [dashboard](https://grafana.com/dashboards/2204) but is empty. 

![image](https://user-images.githubusercontent.com/10825597/52918431-f6ce1780-3307-11e9-90b2-59e2636fdd8d.png)

I tried the queries myself in prometheus it's work. 

![image](https://user-images.githubusercontent.com/10825597/52918465-4dd3ec80-3308-11e9-981c-aa7616bbb183.png)

What can be the reason for this. Thanks

**Comment by walliski** [comment]
I had problems with things not showing up also. I checked the `__requires` key from the dashboard JSON, and saw from there that you need `grafana-piechart-panel`, so I installed it by running `grafana-cli plugins install grafana-piechart-panel` in the docker container running Grafana. Maybe it could help you out also?

**Comment by mehmetcakmaz** [comment]
@walliski installing the piechart plugin solves my problem. thank you so much

**Comment by walliski** [comment]
And if someone still stumbles in here, if you are running it through Docker you can do the install easier by adding an environment variable to the container: `GF_INSTALL_PLUGINS=grafana-piechart-panel`

**Comment by simonwh** [comment]
Thanks @walliski, that was indeed it!
