### ISSUE TITLE
Programmatic health checks

### ISSUE THREAD

**Issue by nullpainter** [AppMetrics/AppMetrics#360]
Is there a recommended or supported way to programmatically use AppMetrics health reporting? 

We have a mixture of health checks in our systems:

1. Self-contained checks which verify the health of systems; and
2. Application code which on completion reports its health.

All external connectivity includes a call to the second variant. Behind the scenes, this uses InfluxDB tags to identify both connectivity health (did we establish a connection to the server?) and response health (did the remote API respond with a HTTP 20x?), and another tag to indicate the health check type. This allows us to have one or two graphs in Grafana for the overall system health, or one per service.

For example:

```C#
_metricsService.Healthy("cognitive-services-speech", HealthCheckType.Connectivity);
```

or where external services respond with a success flag:

```C#
_metricsService.Health(response.Success, "test-service", HealthCheckType.Response);
```

We are currently using a gauge for this, but I am keen to try and use the built-in health check framework in AppMetrics. However, this seems most suited for the self-contained style of health checks.

What are your thoughts on this? Is there an approach I have missed, or are we best to continue using gauges for the time-being?

M

**Comment by alhardy** [comment]
There is a [health check reporter](https://github.com/AppMetrics/Health/blob/dev/sandbox/HealthSandbox/Host.cs#L106) which runs all configured checks and records results as Gauges. This then allows support for flushing health check results using any of the out-of-box reporters and having to record the health check result as a metric yourself.

Does this help?

**Comment by nullpainter** [comment]
Thanks Allan, and apologies for delay in replying. The distinction -- which I'm happy to be corrected on -- is that all of your health checks appear to be self-contained, rather than being explicitly invoked based on the result of a _non-health_ operation.

Here's a trivial example, demonstrating invocation of a service we want to capture the health of using my hand-rolled health framework. I put these health checks in for all network-based calls and, if I'm building a RESTful API, for my own endpoints. It's a particularly useful technique for third-party APIs which don't provide explicit health check endpoints as it allows implicit health capture. In Grafana, we can then graph both implicit and explicit health checks together.

 I have an overload on the various health methods which accepts InfluxDB tags so we can individually measure the health of individual endpoints for an API if desired.

```c#
const string MetricsCategory = "flaky-service";

public MyResponse DoThings()
{
    try
    {
        // Call service which we want to capture the health of
        var response = _myService.DoThings();

        // Capture response/business health based on whether the service returned a successful
        // business response, and network connectivity health where applicable (i.e., for any 
        // database calls, calls over HTTPS, etc.)
        _metricsService.Health(MetricsCategory, response.Success, HealthCheckType.Response);
        _metricsService.Healthy(MetricsCategory, HealthCheckType.Connectivity);

        return response;
    }
    catch (Exception)
    {
        // Lazily assume any failures are connectivity-related and mark service as unhealthy
        _metricsService.Unhealthy(MetricsCategory, HealthCheckType.Connectivity);
    }
}

**Comment by nullpainter** [comment]
I've tidied up my code and realise that my health metrics can be simplified into a collection of small extension methods on `IMeasureMetrics`. So, this is probably something which doesn't strictly belong into AppMetrics (apart from being in a helper package perhaps).
