### ISSUE TITLE
[Question] Collecting metrics for closed systems.

### ISSUE THREAD

**Issue by sommmen** [AppMetrics/AppMetrics#362]
Hello,

I am currently creating an application on a pretty closed system that requires high performance. This app basically fetches data from SQL server (MSSQL) and then ultimately sends them through to another service.

An example I would like to get insight in is: Given that i have to send 1000 messages a second, how many hours can I run before the database is filled up too much, so that each call to the database take up too long to fit in a 1 second timeframe?

Since performance is a big thing i'd like to gather in production (and whilst testing) performance metrics. Now unfortunately i have some limitations:
- I cannot just install applications on the machine. It runs some .NET app(s) and it contains an MSSQL database but that will be all. I would have to present a serious argument to install additional software suits. The usage of libraries/packages are more flexible.
- The system is closed in terms of the system, but also in regard to internet access. Only specific protocols and apps have a connection (remote support). I therefore cannot report all data to a server.

Now my question is - what would be an appropriate way to measure performance? 

My current setup is; I created a class that uses the stopwatch class to measure timing of operations. The class has a thread that writes these values to a .CSV file. I then copy this over to my PC, open it with excel, import it to a workbook and i can see the data (I created some graphs etc).

Ultimately i would like to:
- Get performance data
- Save it locally
   This can be in the DB or some file.

I see that i could create a custom report service that would output data to csv so that i could then import it into excel or something similar? I am also looking into window's native performance counters as we speak.

I would then download the data when needed and perform analysis on that.

Thanks in Advance.

**Comment by alhardy** [comment]
Please read through to documentation to determine how App Metrics can be used.
