### ISSUE TITLE
Use AppMetrics with a console application

### ISSUE THREAD

**Issue by hmehr** [AppMetrics/AppMetrics#363]
This is more of a question since I couldn't find anything on the documentation.

So far we have been using AppMetrics to collect metrics to be pushed to our Prometheus with Asp.net core applications.
But now, I am trying to create a console application that needs instrumentation. We need to expose a metrics endpoint ( that Prometheus can see to pull data from).

In our web application we use extension methods on IWebhostBuilder to set up AppMetrics, but that's not available in a console app. In a console application how would you go about exposing metrics over HTTP on a web server?  Is it even within the realm of possibility? What do you advise?

```` C#
  public static IWebHostBuilder CreateWebHostBuiler(string[] args)
  {
        var webhostbuilder =  WebHost.CreateDefaultBuilder(args);
        // some bootstrapping
       webhostbuilder.UseMetricsEndpoints()
                .UseMetricsWebTracking()
                .ConfigureAppMetricsHostingConfiguration(options =>
                    {
                        options.MetricsEndpoint = "/metrics-proto";
                        options.MetricsTextEndpoint = "/metrics";
                    })
                .UseMetrics(( context, options ) =>
                    {
                        IMetricsRoot Metrics = AppMetrics.CreateDefaultBuilder().OutputMetrics.AsPrometheusPlainText().Configuration.ReadFrom(context.Configuration).Build();
                        options.EndpointOptions = endpointsOptions =>
                        {
                            endpointsOptions.MetricsTextEndpointOutputFormatter = Metrics.OutputMetricsFormatters.GetType<MetricsPrometheusTextOutputFormatter>();
                        };
                    });
  }
`````

Apologies if it's a non-issue. But humor me ( and any other uninitiated ones out there looking for the same question)

**Comment by alhardy** [comment]
Have a look at the sample projects for working examples

**Comment by nick-kompas-cko** [comment]
Is there a sample project in .NET Core 2 console app using AppMetrics? If so I don't see it anywhere

**Comment by lindalinya** [comment]
@alhardy  the site of the sample projects for a console application in the document (https://www.app-metrics.io/samples/) response 404. Are there any other samples that can help us?
