### ISSUE TITLE
New AspNetCoreHealth Authorization Feature For Discussion

### ISSUE THREAD

**Issue by jvonruden** [AppMetrics/AppMetrics#366]
Add Authorization Feature to AspNetCoreHealth. Instead of implementing Authorization details in AspNetCoreHealth use dependency injection with IHealthAuthorizationFilter interface to allow the calling application to implement their own Authorization Mechanism.  The HttpContext context is passed into the IHealthAuthorizationFilter Authorized method because the most likely scenario is the caller will want to check for an Authorization header and secrets.

**Thoughts?**

Here is the actual feature implemented ready for contribution:  
https://github.com/jvonruden/AspNetCoreHealth/commit/2400b4ce0c4b47f334ce2694d872d97c0eb620c4

**Summary:**

**1)** Created an Interface: IHealthAuthorizationFilter

	public interface IHealthAuthorizationFilter
	{
		bool Authorized(HttpContext context, CancellationToken token = default);
	}

**2)** In HealthApplicationBuilderExtensions.cs use dependency injection to see if someone has provided IHealthAuthorizationFilter and use it instead AuthorizedHealthAuthorizationFilter (Always returns Authorized == true)

	var healthAuthorizationFilter = app.ApplicationServices.GetService<IHealthAuthorizationFilter>() ?? new AuthorizedHealthAuthorizationFilter();
	appBuilder.UseMiddleware<HealthCheckEndpointMiddleware>(responseWriter, endpointsOptionsAccessor.Value.Timeout, healthAuthorizationFilter);

**3)** In the HealthCheckEndpointMiddleware Invoke method just before the _healthCheckRunner is called check for the Authorization from the provided IHealthAuthorizationFilter.

if (!_healthAuthorizationFilter.Authorized(context))
{
  _logger.MiddlewareAuthorizationInvalid<HealthCheckEndpointMiddleware>();
  context.Response.StatusCode = StatusCodes.Status401Unauthorized;
  await context.Response.WriteAsync("Invalid authorization.", cancellationToken: cancellationTokenSource.Token);
}
else
{
	// _healthCheckRunner stuff.
}

**4)** The Fact Middleware test is a working example using the IHealthAuthorizationFilter HealthCheckEndpointAuthorizationMiddleware.cs

**Comment by alhardy** [comment]
@jvonruden I've just been using an `IStartupFilter` to restrice access to health and metrics, something like the following:

```
public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
        {
            return RequireSecretToMetricsAndHealth;

            void RequireSecretToMetricsAndHealth(IApplicationBuilder app)
            {
                app.Use(async (context, next2) =>
                {
                    var key = ExtractToken(context);

                    if (_endpoints.Any(e => string.Compare(context.Request.Path.Value, e, StringComparison.InvariantCultureIgnoreCase) == 0))
                    {
                        if (key != _key)
                        {
                            context.Abort();
                            return;
                        }
                    }

                    await next2.Invoke();
                });

                next(app);
            }
        }
```

**Comment by jvonruden** [comment]
This makes sense. I wonder if this scenario/solution is captured in documentation since it is pretty common to want to lock down the health endpoints

**Comment by jvonruden** [comment]
If not I would be happy to contribute and update to the docs

**Comment by alhardy** [comment]
Would be great if you could contribute to the docs. Thanks
