### ISSUE TITLE
Change default size for metric check

### ISSUE THREAD

**Issue by PedroS11** [AppMetrics/AppMetrics#368]
Hello,

I'm using the predefined health checks for Memory checks (AddProcessPrivateMemorySizeCheck, AddProcessVirtualMemorySizeCheck and AddProcessPhysicalMemoryCheck) and the messages come with size in Byte units. Is it possible to change the message for Gb or Mb? Bytes can be difficult to understand.

**Comment by alhardy** [comment]
Probably easy to implement as a custom check rather than make configurable.
