### ISSUE TITLE
App.Metrics.Reporting.Socket.Client.SocketSettings validates address incorrectly

### ISSUE THREAD

**Issue by LeonHagenaarsKeus** [AppMetrics/AppMetrics#370]
In the validation of SocketSettings.cs, an endpoint is validated by creating it with `string endpoint = $"{address}:{port}";`
In the Endpoint getter however the endpoint is created by using {protocol}://{address}:{port}.
This means that entering an ip address as the address wil result in an invalid operation exception, entering tcp://[ip] will pass this validation, but wil result in the endpoint tcp://tcp://[ip], which does not work.

**Comment by MyracleDesign** [comment]
I think it is related to here if I enter the following in overUdp the validation is failing
```
builder.Report.OverUdp(new MetricsInfluxDbLineProtocolOutputFormatter(), "127.0.0.1", 4444);
```
It fails in the SocketSettings.cs in line 69 
```
127.0.0.1:4444 must be a valid absolute URI
```

**Comment by alhardy** [comment]
duplicate https://github.com/AppMetrics/AppMetrics/issues/549
