### ISSUE TITLE
TravisCI: The name 'ReSharperReports' does not exist in the current context

### ISSUE THREAD

**Issue by Alessar** [AppMetrics/AppMetrics#373]
Error occurred when compiling build script:
`/home/travis/build/AppMetrics/Reporting/build.cake(239,2)`:
error CS0103: The name `ReSharperReports` does not exist in the current context

**Comment by sflusov** [comment]
Hi @alhardy , 

I've received absolutely the same error in the [pull request](https://github.com/AppMetrics/Elasticsearch/pull/29) to ElasticSearch project
Could you explain how to fix to it?

`Error: Error occurred when compiling build script: /home/travis/build/AppMetrics/Elasticsearch/build.cake(237,5): error CS0103: The name 'ReSharperReports' does not exist in the current context`

**Comment by alhardy** [comment]
@sflusov I've just moved all reporters to the main repo, I'll be doing the same for ES sometime soon and will look at your PR and the build failure. Builds have also been updated to use Azure DevOps
