### ISSUE TITLE
System.InvalidCastException while adding HealthEnpoint in Startup.cs

### ISSUE THREAD

**Issue by hasanalituran** [AppMetrics/AppMetrics#383]
Hi, I was trying to implement health checks in my asp.net core v2.2 project with the help of the docs [here](https://www.app-metrics.io/web-monitoring/aspnet-core/health/). I debugged the applications to which I send get requests and it seems that my application perfoms health checks as expected.  When it comes to seeing the health check result at /health endpoint, first I got the warning that displays the below message.

> No formatter has been registered. See App.Metrics.Formatters.Ascii & App.Metrics.Formatters.Json for example.

So, I have downloaded **App.Metrics.Formatters.Ascii** & **App.Metrics.Formatters.Json** from nuget but never been able to add them like in the example in startup.cs.
`services.AddMetrics()
.AddAsciiEnvironmentInfoSerialization();
// Enables plain text format on the /env endpont.`. Unfortunately, `AddAsciiEnvironmentInfoSerialization()` or any other formatter method was not recognized in my project. Other than what the title says I wanna learn what causes this.

Lastly, I tried to add `app.UseHealthEndpoint();` in startup.cs and program.cs (not at the same time) but in app start it throws `System.InvalidCastException: 'Object cannot be stored in an array of this type.'` exception. Are these problems related to my project version (.NET Core v2.2) or is there something missing? Any help is appreciated. Thanks in advance.

**Comment by alhardy** [comment]
Try the sample project https://github.com/AppMetrics/Samples.V2/tree/master/AspNetCore2.Health.Api.QuickStart
