### ISSUE TITLE
HealthEndpointsHostingOptions.AllEndpointsPort have no affect on Health Endpoint port

### ISSUE THREAD

**Issue by BenBorn** [AppMetrics/AppMetrics#387]
If you specify in the config HealthEndpointsHostingOptions.AllEndpointsPort=5003. The Port of the Health-Endpoint is not set to 5003. Only if I set HealthEndpointPort = 5003 then the endpoint is exposed on port 5003.
From my point the problem is in the method:
https://github.com/AppMetrics/AspNetCoreHealth/blob/5f386180e8e5241b59768a58684e66ccf4e4ab20/src/App.Metrics.AspNetCore.Health.Endpoints/Builder/HealthApplicationBuilderExtensions.cs#L89
Because here is no check about AllEndpointsPort.

**Comment by alhardy** [comment]
Planning to remove the health check related implementation due to there being a Microsoft equivalent
