### ISSUE TITLE
Microsoft HealthChecks Metrics Reporting

### ISSUE THREAD

**Issue by JonasMH** [AppMetrics/AppMetrics#389]
I have an application that requires me to use the Microsoft Health Checks instead of AppMetrics Health, but I would still like to have the health checks available in the metrics output. But after looking around I couldn't find a way to do that, so based on AppMetrics Health's [HealthReporterBackgroundService.cs](https://github.com/AppMetrics/MicrosoftExtensions/blob/dev/src/App.Metrics.Health.Extensions.Hosting/HealthReporterBackgroundService.cs) I created my own little spinoff that uses HealthCheckService to pull checks from.

Gist: https://gist.github.com/JonasMH/5667813db08b339e5fb979660626c016

Throught it would be a nice addition to the library. Haven't made a pull-request with it as I wasn't sure where it would belong as it no longer uses the AppMetrics Health library at all and is more of an extensions to the base AppMetrics AspNetCore library.

So let me know if it's something you would like in the library and where the code should go, then I'll make pull request with tests, extensions and so on.

Pretty new to AppMetrics, but I'm a big fan so far! :-)

**Comment by alefcarlos** [comment]
@JonasMH, how can i use this in my project ? I'm also using Microsoft Health Checks instead of AppMetrics Health.
