### ISSUE TITLE
Please consider referencing Microsoft.Extensions.DependencyInjection.Abstractions instead of implementation

### ISSUE THREAD

**Issue by prochnowc** [AppMetrics/AppMetrics#390]
We are using Autofac as DI container for our applications. When upgrading App.Metrics from v1 to v2 we discovered that `Microsoft.Extensions.*` and `Microsoft.AspNetCore.*` packages do have a dependency on `Microsoft.Extensions.DependencyInjection`. It looks like App.Metrics only uses the Abstractions. Please consider changing the reference from `Microsoft.Extensions.DependencyInjection` to `Microsoft.Extensions.DependencyInjection.Abstractions` because App.Metrics should not depend on DI container implementation.

Thanks!

**Comment by plachor** [comment]
btw @alhardy  do you need to target this dependency in version 2.2.0 ? This is similar case to Newtonsoft.Json dependency affecting ASP version compatibility?

**Comment by prochnowc** [comment]
@alhardy @vhatsura Thanks for the change. Please also consider downgrading the references to 2.1. Our apps are targeting AspNetCore 2.1 because its an LTS release. I think most business apps will target 2.1

**Comment by alhardy** [comment]
Targeting >=2.1.0 should work. PR would be great.

**Comment by plachor** [comment]
@alhardy are there any plans to release App.Metrics with this backward compatibility for ASP 2.1 ?

**Comment by alhardy** [comment]
No I don't plan to release App.Metric later versions with backwards compat for 2.1
