### ISSUE TITLE
RegisterFromAssembly extension not registering health checks

### ISSUE THREAD

**Issue by ignas-sakalauskas-cko** [AppMetrics/AppMetrics#391]
Hi There,

I've noticed that referencing health checks from a library project in an application which has it's own health checks but does not explicitly reference App Metrics nuget package, won't register applications' health checks.

Example project:
https://github.com/ignas-sakalauskas/AppMetricsHealthCheckMissing

Run the WebApi project and hit the health endpoint `http://localhost:5000/_system/health`

Actual result:
```
{
    "healthy": {
        "HealthCheckLib": "OK"
    },
    "status": "Healthy"
}
```

However, the expected result is:
```
{
    "healthy": {
        "HealthCheckLib": "OK",
        "HealthCheckWebApi": "OK"
    },
    "status": "Healthy"
}
```

Setting dependency context doesn't solve the issue, and a simple solution (workaround?) is to explicitly reference App Metrics nuget package in `WebApi.csproj` -- see a comment in the `WebApi.csproj` in my repo.

Since the project successfully builds, however silently fails to register all the health checks, this looks like a bug to me. Could you please shed more light on this?

Thanks,
Ignas

**Comment by alhardy** [comment]
Planning to remove the health check related implementation due to there being a Microsoft equivalent
