### ISSUE TITLE
AppMetrics not picking up other routes than GET favicon.ico

### ISSUE THREAD

**Issue by walliski** [AppMetrics/AppMetrics#395]
Hey

I have an Asp.net Core app (2.2.2) that I am trying to see web metrics from. We are using Mvc, but App Metrics does not seem to pick up requests to our routes, only for the `favicon.ico` file (which fails with a 404, but only shows up as `GET`, and not the whole route.).

I've tried using the latest App.Metrics nugets, and also tried with `3.1.0-alpha-0114`.

In startup.cs I am doing this:

```
services.AddMvc().AddMetrics()

var metrics = AppMetrics.CreateDefaultBuilder()
                .Report.ToInfluxDb("http://127.0.0.1:8086", "qsrepmet")
                .Build();
services.AddMetrics(metrics);
services.AddMetricsTrackingMiddleware();
services.AddMetricsReportingHostedService();
services.AddMetricsEndpoints();
```

I've also tried adding the `.SetCompatibilityVersion(CompatibilityVersion.Version_2_1)`, but it didn't help.

And

```
app.UseMetricsAllMiddleware();
app.UseMetricsAllEndpoints();
```

Anything obvious that I am doing wrong? I am not that familiar with asp.net core that I could figure this out 🤔

**Comment by justmara** [comment]
Doesn't it look similar like this [old issue](https://github.com/AppMetrics/AspNetCore/issues/38)?

**Comment by khorneee** [comment]
if you run net core 2.2 change for this and run
`services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)`
that works

**Comment by justmara** [comment]
@khorneee sure, but this can be used only as temporal solution. surely it must be fixed in appmetrics itself without forcing applications to downgrade.
