### ISSUE TITLE
MetricsEndpointMiddleware doesn't satisfy AllowSynchronousIO option of Kestrel server

### ISSUE THREAD

**Issue by stukselbax** [AppMetrics/AppMetrics#396]
Recently we started migration to the prometheus engine to store our metrics, so we used the /metrics endpoint processed by this library. Also we have configured it with prometheus formatter.

```c#

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost
                .CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseMetrics()
                .UseMetricsEndpoints(options =>
                {
                    options.MetricsEndpointOutputFormatter = new MetricsPrometheusTextOutputFormatter();
                })
                .UseKestrel(o => o.AllowSynchronousIO = false);
    }
```

There is an option in kestrel server which disable synchronous api in order to prevent potential blocking of threads. So what we observing is if `AllowSynchronousIO == false`, the formatters of library throw since they use synchronous methods when writing to the stream:

```text
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.WriteSimpleValue(StreamWriter writer, String family, Double value, IEnumerable`1 labels, String namePostfix) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\Internal\AsciiFormatter.cs:line 115
   at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.WriteMetric(StreamWriter streamWriter, MetricFamily family, Metric metric) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\Internal\AsciiFormatter.cs:line 110
   at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.WriteFamily(StreamWriter streamWriter, MetricFamily metricFamily) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\Internal\AsciiFormatter.cs:line 58
   at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.Write(Stream destination, IEnumerable`1 metrics, NewLineFormat newLine) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\Internal\AsciiFormatter.cs:line 36
   at App.Metrics.Formatters.Prometheus.MetricsPrometheusTextOutputFormatter.WriteAsync(Stream output, MetricsDataValueSource metricsData, CancellationToken cancellationToken) in C:\projects\prometheus\src\App.Metrics.Formatters.Prometheus\MetricsPrometheusTextOutputFormatter.cs:line 47
   at App.Metrics.AspNetCore.Endpoints.Middleware.MetricsEndpointMiddleware.Invoke(HttpContext context) in C:\projects\aspnetcore\src\App.Metrics.AspNetCore.Endpoints\Middleware\MetricsEndpointMiddleware.cs:line 41
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

As for now we have to set `AllowSynchronousIO == true`, but I think the library must be [async all the way](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx). The same behavior observed with default output formatter, and with /metrics-text default output formater. Checked with 2.0 and 3.0 versions of app.metrics, and with aspnetcore 2.1 and 2.2.

**Comment by alhardy** [comment]
Should be fixed by https://github.com/AppMetrics/AppMetrics/issues/403

**Comment by alhardy** [comment]
Actually no, other cases need to be updated

**Comment by czioutas** [comment]
May I ask what is the state of this?
Soon .net core 3 will be released and this will be the default case.

**Comment by alhardy** [comment]
Fair bit to change, I'll look at .net core 3 once it's release, and this ticket following that

**Comment by razfriman** [comment]
Just ran into this issue while migrating to .net core 3

**Comment by pwlsjk** [comment]
It seems that `Newtonsoft.Json.JsonWriter` isn't async, called from `App.Metrics.Health.Formatters.Json.HealthStatusJsonOutputFormatter.WriteAsync` :



`
InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
`

    Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(byte[] buffer, int offset, int count)
    System.IO.StreamWriter.Flush(bool flushStream, bool flushEncoder)
    System.IO.StreamWriter.Dispose(bool disposing)
    System.IO.StreamWriter.Close()
    Newtonsoft.Json.JsonTextWriter.CloseBufferAndWriter()
    Newtonsoft.Json.JsonTextWriter.Close()
    Newtonsoft.Json.JsonWriter.Dispose(bool disposing)
    Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
    App.Metrics.Health.Formatters.Json.HealthStatusJsonOutputFormatter.WriteAsync(Stream output, HealthStatus healthStatus, CancellationToken cancellationToken)
    App.Metrics.AspNetCore.Health.Core.DefaultHealthResponseWriter.WriteAsync(HttpContext context, HealthStatus healthStatus, CancellationToken token)
    App.Metrics.AspNetCore.Health.Endpoints.Middleware.HealthCheckEndpointMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
    App.Metrics.AspNetCore.Tracking.Middleware.ApdexMiddleware.Invoke(HttpContext context)
    App.Metrics.AspNetCore.Tracking.Middleware.PerRequestTimerMiddleware.Invoke(HttpContext context)
    App.Metrics.AspNetCore.Tracking.Middleware.RequestTimerMiddleware.Invoke(HttpContext context)
    App.Metrics.AspNetCore.Tracking.Middleware.ErrorRequestMeterMiddleware.Invoke(HttpContext context)
    App.Metrics.AspNetCore.Tracking.Middleware.ActiveRequestCounterEndpointMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`

**Comment by hundreder** [comment]
Any news about this?

**Comment by alhardy** [comment]
Going to start picking up core 3.0 related work, no ETA, any help appreciated, there's a new features/4.0.0 branch

**Comment by johnnyreilly** [comment]
Is there any plan to release 4.0.0? As far as I can tell the fix for this is in 4.0.0 but the latest release is 3.2.0. Thanks for all your work!

**Comment by martinothamar** [comment]
As @stukselbax said here: https://github.com/AppMetrics/AppMetrics/pull/507#issuecomment-581852762

There's more work to be done, synchronous `Write` calls which need to be switched to `WriteAsync` etc

**Comment by TarasKuzBinariks** [comment]
4.3.0 and i still have this problem. netcoreapp3.1. Is it only me?

**Comment by xithan** [comment]
No, you are not alone. I have the same problem with 4.3.0

**Comment by WalissonPires** [comment]
In windows **/metrics** and **/metrics-text** work. In Linux/docker **/metrics** works while **/metrics-text** throws the error already reported by colleagues.

Using version 4.3.0 and .NET 7.

Has anyone managed to solve it without having to enable synchronous writing?

**Comment by WalissonPires** [comment]
Any chance of this being resolved?

**Comment by hundreder** [comment]
I know this isnnot the anser youd like, but you should move away from OpenMetrics towards Opet Telemetry, at least for new projects.
