### ISSUE TITLE
Setup in Program.cs vs Startup.cs

### ISSUE THREAD

**Issue by Lobosque** [AppMetrics/AppMetrics#397]
Hello,

I am having a little trouble to understand the difference between configuring App Metrics using `Program.cs` or `Startup.cs` - Is there anything in the docs explaining what are the difference between the two methods?
I remember reading somewhere that configuring under `Program.cs` is preferred. However, configuring under `Startup.cs` is generally easier, specially regarding reading configuration from `applicationsettings.json`. I would go this route but would like to know what the downsides would be.

**Comment by alhardy** [comment]
If you find it preferrable to add to `Startup.cs` go with that
