### ISSUE TITLE
Allow overriding ContextName for default metrics

### ISSUE THREAD

**Issue by tdabasinskas** [AppMetrics/AppMetrics#400]
Looking into the source code, it seems that `Application` prefix for context names [is hardcoded](
https://github.com/AppMetrics/AspNetCore/blob/master/src/App.Metrics.AspNetCore.Core/Internal/HttpRequestMetricsRegistry.cs#L20):

```chsharp
 public static string ContextName = "Application.HttpRequests";
```

[Prometheus provides the guidelines for naming the metrics](https://prometheus.io/docs/practices/naming/) and one of the things these guidelines states is the following:

> A metric name. should have a (single-word) application prefix relevant to the domain the metric belongs to. The prefix is sometimes referred to as namespace by client libraries. For metrics specific to an application, the prefix is usually the application name itself. Sometimes, however, metrics are more generic, like standardized metrics exported by client libraries. Examples:
    - prometheus_notifications_total (specific to the Prometheus server)
    - process_cpu_seconds_total (exported by many client libraries)
    - http_request_duration_seconds (for all HTTP requests)

The hardcoded `Application` prefix for the metrics makes this somehow incompliant with the guidelines.

Would it be possible to support overriding of this, similarly it is possible to do with the custom metrics via `options.DefaultContextLabel`?

**Comment by okman523** [comment]
@alhardy How to override the context in the asp.net core middleware?

**Comment by alhardy** [comment]
This is not configurable, happy with a PR if really wanted

**Comment by kwinkel** [comment]
I wrote a workaround for this behaviour, maybe it helps someone.

```csharp
/// <summary>
/// Responsible to workaround this: https://github.com/AppMetrics/AppMetrics/issues/400
/// </summary>
public class PrometheusMetricNameFormatter
{
    public string Format(string prefix, string name)
    {
        if (prefix.Equals("application", StringComparison.InvariantCultureIgnoreCase))
        {
            prefix = null; // or whatever you want to do
        }
            
       return PrometheusFormatterConstants.MetricNameFormatter(prefix, name);
   }
}
```

Step 2) Configure OutputMetrics -> Prometheus to use this metric-name-formatter
```csharp
var metricNameFormatter = new PrometheusMetricNameFormatter();
metricsOptions.OutputMetrics.AsPrometheusPlainText(prometheus => prometheus.MetricNameFormatter = metricNameFormatter.Format);
```

@tdabasinskas

**Comment by Simonl9l** [comment]
Per Step 2m this does not seem to fire...

Had to:

```C#
.UseMetrics(options =>
                {
                    options.EndpointOptions = endpointsOptions =>
                    {
                        endpointsOptions.MetricsTextEndpointOutputFormatter =
                            new MetricsPrometheusTextOutputFormatter(new MetricsPrometheusOptions
                            {
                                LabelNameFormatter = MetricFormatter.FormatLabel,
                                MetricNameFormatter = MetricFormatter.FormatName,
                                NewLineFormat = NewLineFormat.Auto
                            });
                        endpointsOptions.MetricsEndpointOutputFormatter = 
                            new MetricsPrometheusProtobufOutputFormatter(new MetricsPrometheusOptions
                            {
                                LabelNameFormatter = MetricFormatter.FormatLabel,
                                MetricNameFormatter = MetricFormatter.FormatName,
                                NewLineFormat = NewLineFormat.Auto
                            }); 
                    };
                });
```

if also seems that the following also does nothing :
```C#
 .ConfigureMetrics(builder =>
                {
                    builder.Configuration.Configure(options =>
                    {
                        options.DefaultContextLabel = "mylabelprefix";
                    });
```
