### ISSUE TITLE
Adding request domain as a tag

### ISSUE THREAD

**Issue by martinjt** [AppMetrics/AppMetrics#402]
I'm wondering if there is an interception point where I'd be able to tag all metrics with the current request's domain?

The usecase is a single site hosting multiple domains/customers, and wanting to be able to monitor which ones are causing slowness.

The workaround I have right now would be a custom IMetrics implementation, but it feels wrong to access the static context from there.

**Comment by WalissonPires** [comment]
up

**Comment by alhardy** [comment]
This wouldn't be a very typical use case. Suggest for such scenarios to write custom tracking middleware rather than use what comes out of the box with the ASP.NET Core tracking package
