### ISSUE TITLE
AsciiFormatter.Write closes stream it does not own

### ISSUE THREAD

**Issue by bdrupieski** [AppMetrics/AppMetrics#403]
When it writes out the Prometheus endpoint output, `AsciiFormatter.Write` uses a `StreamWriter` that closes the `Stream` passed to the method, here: https://github.com/AppMetrics/Prometheus/blob/8cb2945de7110deab7da02294d5683c76585018a/src/App.Metrics.Formatters.Prometheus/Internal/AsciiFormatter.cs#L32

If there's any middleware that runs after this that wants to do anything with the response stream, then any attempt to read or seek that stream will throw a `ObjectDisposedException` with the message "Cannot access a closed Stream.". I have some debug logging middleware that was inspecting response streams that was throwing an exception here because of this.

I'm also finally getting around to trying out histograms (from this original issue a long, long time ago: https://github.com/AppMetrics/AppMetrics/issues/278) and wanted to try to write some test histogram stuff to the end of the stream. If it's closed I can't do that.

There's a `StreamWriter` constructor overload that takes a `bool` to control whether or not to leave the stream open. After poking around a bit it looks like this implementation was mostly copied from https://github.com/prometheus-net/prometheus-net, which does leave the stream open:

https://github.com/prometheus-net/prometheus-net/blob/e277cbee85f1c4cfa22253f39e5454e4361838e0/Prometheus.NetStandard/Internal/AsciiFormatter.cs#L20

Could I create a PR to leave this stream open, or is it preferred to keep it the way it is? I did notice that other `IMetricsOutputFormatter` implementations also close the output stream, so if we changed this one to leave it open then they would be inconsistent. However, it seems like it's better to always leave it open anyhow and let the user who passed it in close it.

**Comment by alhardy** [comment]
Experienced the same issue in the InfluxDB reporter as a result of [this PR](https://github.com/AppMetrics/InfluxDB/pull/47)
