### ISSUE TITLE
Dashboard "No data points" unless specific pod selected

### ISSUE THREAD

**Issue by sc250024** [AppMetrics/AppMetrics#406]
Greetings,

Having a problem with the AppMetrics dashboard. Basically, I can view the metrics only if I select a specific application pod under the `server` variable. Otherwise, every pane displays **No data points** otherwise.

=> If I select **only one** pod under `server`, it works.
=> If I select **All** under `server`, it doesn't work.
=> If I select **2 or more** pods under `server`, it doesn't work.

Here's a quick GIF showing the problem.

![oct-26-2018 14-49-00](https://user-images.githubusercontent.com/8792243/47567569-332bd100-d92f-11e8-9268-00ae027c7f46.gif)

I also found some variable errors other than this. I would be happy to open a PR fixing the dashboard, but I would just need some assistance with this part. I'm using:

=> Grafana 5.3.2
=> Prometheus 2.4.3

**Comment by ducas** [comment]
where does the source for this live?

**Comment by ducas** [comment]
ping... can someone link me to where i can submit the pull request? the prometheus repo is archived, but i can't find the dashboards in this repo.

**Comment by alhardy** [comment]
Prom support is moved to this repo
