### ISSUE TITLE
PushGateway support

### ISSUE THREAD

**Issue by endofcake** [AppMetrics/AppMetrics#407]
Hi,

Are there any plans to add support for pushing metrics to Push Gateway? The reason I'm asking it that we're running lots of containers on ephemeral ports, and scraping them with Prometheus is really non-trivial. In theory we could aggregate with cAdvisor, but its app metrics support is in alpha and isn't easy to set up either.

So using PushGateway as a workaround (similar to `andrasm/prometheus-net`) could be a decent solution to this.

Thanks.

@alhardy

**Comment by alhardy** [comment]
@bdrupieski I will move it over to this repo, I left it for now when combining repos because it was failing to build.

**Comment by saurabhtyagi00** [comment]
I also face issues in pushing metrics to prom/pushgateway. Here is my solution code:

`var metrics = new MetricsBuilder()
                    .Report.ToConsole()
                    .Report.OverHttp(options =>
                    {
                        options.HttpSettings.RequestUri = new Uri("http://192.168.0.76:9091/metrics/job/myjob");
                        options.MetricsOutputFormatter = new MetricsPrometheusProtobufOutputFormatter();
                    })
                    .Build();

                var counter = new CounterOptions { Name = "my-counter"};
                metrics.Measure.Counter.Increment(counter);

                await Task.WhenAll(metrics.ReportRunner.RunAllAsync());`

Hope someone find it helpful.

**Comment by justinmchase** [comment]
@saurabhtyagi00 Can you including your `using` statements and which dependencies you had to install to get this to work? I believe I have the latest version but am just not seeing these extension methods.

**Comment by saurabhtyagi00** [comment]
<PackageReference Include="App.Metrics.AspNetCore" Version="4.1.0" />
    <PackageReference Include="App.Metrics.Formatters.Prometheus" Version="4.1.0" />
    <PackageReference Include="App.Metrics.Reporting.Http" Version="4.1.0" />

**Comment by saurabhtyagi00** [comment]
> @saurabhtyagi00 Can you include your `using` statements and which dependencies you had to install to get this to work? I believe I have the latest version but am just not seeing these extension methods.

    <PackageReference Include="App.Metrics.AspNetCore" Version="4.1.0" />
    <PackageReference Include="App.Metrics.Formatters.Prometheus" Version="4.1.0" />
    <PackageReference Include="App.Metrics.Reporting.Http" Version="4.1.0" />
