### ISSUE TITLE
Feature Request: TextFile - Rollover Interval

### ISSUE THREAD

**Issue by grahamehorner** [AppMetrics/AppMetrics#410]
IMHO it would be great if the TextFile reporter support an interval/duration whereby a new file would be created to capture metrics, this would avoid large files and/or locking of the file which would prevent moving to a offline location.

**Comment by sommmen** [comment]
#idea rollover on a set filesize instead?

**Comment by grahamehorner** [comment]
could even have the rollover be declined as a lambda expression that is evaluated when a flush is performed ;)

**Comment by sommmen** [comment]
Now we talkin'!
