### ISSUE TITLE
remove global tags in name of metric

### ISSUE THREAD

**Issue by sommmen** [AppMetrics/AppMetrics#413]
Metrics contain the global tags both in the tags field and in the name:

![image](https://user-images.githubusercontent.com/8641495/56077417-4565d280-5ddc-11e9-91a0-f307b5b74cc5.png)

This seems unnecessarily double to me, i'd like an option to remove these from the name.

**Comment by alhardy** [comment]
How are you serializing your metrics?

**Comment by mortengjesing** [comment]
@alhardy this was bugging me too, so i did some investigation and it seems that the name is set inside https://github.com/AppMetrics/AppMetrics/blob/2a72b41fc677737d42bd72f96895620ba08b41cf/src/Core/src/App.Metrics.Core/Internal/DefaultMetricContextRegistry.cs#L77 i did some code to allow to configure this. But i am uncertain if the name is used as a key to identify a combination of name and tags.

**Comment by sommmen** [comment]
> How are you serializing your metrics?

A custom serializer so that I can use it with entity framework.
I now manually remove the redundant tags from the name like so:

`var indexOfPipeChar = name.IndexOf("|", StringComparison.Ordinal);`
`Name = name.Remove(indexOfPipeChar, name.Length - indexOfPipeChar);`

However the issue kinda applies to the other formatters also.
