### ISSUE TITLE
Backoff implemention for Influx sink

### ISSUE THREAD

**Issue by plachor** [AppMetrics/AppMetrics#414]
Hi @alhardy, 

Could you consider resetting `_failureAttempts` on successful delivery in `DefaultLineProtocolClient` class? 

https://github.com/AppMetrics/AppMetrics/blob/dev/src/Reporting/src/App.Metrics.Reporting.InfluxDB/Client/DefaultLineProtocolClient.cs#L67

For now `_failureAttempts` is a cumulative counter across whole timeline so we can set it to 5 for instance and after a week of almost continuous delivery trigger this backoff due to some out-liners. Wouldn't it make sense to reset counter on success ? 

Are there any estimations around release date of 3.1 stable version ? (issue with nJson)

**Comment by vhatsura** [comment]
@plachor, I believe the issue can be closed due to merging PR with changes

**Comment by plachor** [comment]
Sure, thank you for your effort around this topic.
