### ISSUE TITLE
Passwrod protection for metrics endpoints

### ISSUE THREAD

**Issue by V0v1kkk** [AppMetrics/AppMetrics#415]
Hello.

How I can protect my _prometheus_ metrics endpoints by password (_basic auth_)?
I found how configure custom http endpoint, but unfortunately I couldn't find any option for do that with _prometheus_.

**Comment by alhardy** [comment]
A `StartupFilter` is one approach e.g. https://github.com/AppMetrics/Docs.V2.Hugo/commit/095e6f6c6560ddd43ac4ceff46ac0380d84bef49
