### ISSUE TITLE
.Net Core Preview 4 - Background Service?

### ISSUE THREAD

**Issue by ronMilne** [AppMetrics/AppMetrics#416]
I'm trying to understand how to configure AppMetrics within a console background worker project using .Net Core preview 4.  I have so far
```csharp
        public static IHostBuilder CreateHostBuilder(string[] args) =>
           Host.CreateDefaultBuilder(args)
                .ConfigureServices(services =>
                {
                    services.AddMetrics();
                    services.AddHostedService<Worker>();
                });
    }
```
How do I specify options for the AddMetrics, also outputting metrics to the console?

**Comment by alhardy** [comment]
Do the [sample projects](https://github.com/AppMetrics/Samples.V2/blob/master/AspNetCore2.Api.QuickStart/Program.cs#L16) help?
