### ISSUE TITLE
Question: Advice for Application Insights reporter

### ISSUE THREAD

**Issue by jdvor** [AppMetrics/AppMetrics#417]
I'm looking for an advice regarding implementation of a reporter to Microsoft Azure Application Insights.

[Relevant Microsoft documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics)
>  If you are implementing your own pre-aggregation logic, you can use the Track(ITelemetry metricTelemetry) method to send the resulting aggregates.

This looks to me exactly what needs to be done as App.Metrics are doing their own aggregation, so it boils down to translating `*ValueSource` types from `MetricsContextValueSource` in the reporter to `MetricTelemetry` instances.

Simplified Application Insights DTO for publishing metrics aggregated on client side (pseudo-code):
```
MetricTelemetry 
{
    double Sum,
    double? Max,
    double? Min,
    int? Count,
}
```
[original MetricTelemetry](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.metrictelemetry?view=azure-dotnet)

Questions:

1. Is there a way how to get min, max and stdev in sources which do not seem to expose them (MeterValue, ApdexValue)?
2. ~~In what situations the collections `MeterValue.SetItem[] Items` and `CounterValue.SetItem[] Items` would have something in them (so far I've seen them always empty)?~~

**Comment by alhardy** [comment]
Meters and Apdex metric types in App Metrics don't calculate these values.

**Comment by jdvor** [comment]
3. If I'm not mistaken the property which allows resetting a metric after reporting is only available in `CounterOptions` and `ApdexOptions`. What is the reasoning for it not being available for example on histogram? (Where it seem to me would be most useful as statistics such as min, max, stddev are really not that interesting in a cumulative scope - i.e. minimal value ever recorded.)

**Comment by jdvor** [comment]
I already have a working implementation of the reporter. Would you be interested in PR into App.Metrics and if so, do you have any PR guidelines?
The link for contributing in README.md seems to be broken at the moment.

**Comment by alhardy** [comment]
Cool. I'd prefer that to be a community driven repo outside of App.Metrics. Interested in having a look and happy to have it included in the documentation.

**Comment by jdvor** [comment]
I'd be interested in your opinion on this [implementation](https://github.com/jdvor/appmetrics-applicationinsights).

I have pointed out some outstanding issues in [README.md](https://github.com/jdvor/appmetrics-applicationinsights/blob/master/README.md) which are simply a result of two metric frameworks / abstractions having different opinions here and there. Nothing major I think, so at this point it looks usable to me.

**Comment by alhardy** [comment]
LGTM

**Comment by jdvor** [comment]
> LGTM

That's quite an interesting tool. I've had no idea something like that exists. Default setting generates quite a lot false positives for C# code, but I guess that would be easy to tune by per project lgtm.yml. Thanks for the tip.

**Comment by jdvor** [comment]
I've just realized you've probably meant "Looks Good To Me" and I've accidentally discovered this https://lgtm.com - a code analysis tool that can be easily integrated into GitHub (or used without it).

**Comment by jdvor** [comment]
Released [RC1](https://www.nuget.org/packages/App.Metrics.Reporting.ApplicationInsights/) (pre-release channel).
I'm closing this ticket.
