### ISSUE TITLE
ResetOnReporting for Meter, Histogram and Timer

### ISSUE THREAD

**Issue by EgorManevich** [AppMetrics/AppMetrics#420]
Hi,

Thank you for work!
It would be very useful if `ResetOnReporting` for `count` was allowed for Meter, Histogram and Timer. Unfortunately now I have to add counter every time I need to display rate.
I tried using InfluxDb's `non_negative_difference` function on cumulative count, but it throws away those points that are reported after server reset.
I understand that reset would probably mess up statistical information, but in my use-case it doesn't matter

Thanks

**Comment by ashishkalel** [comment]
I am also in need of this feature. Any progress on this feature? 
In the meantime, can anyone please suggest the workaround to solve this problem with some example code?
