### ISSUE TITLE
The resource filter is not calling when an API is called.

### ISSUE THREAD

**Issue by JoobinMo** [AppMetrics/AppMetrics#423]
Hi guys,

Well in my project I have used this package, but it is not working, Well I have been using this in many project but this one is the only one that is not working, am using influxDb and Grafana.

this is the Startup :

        public virtual void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IPushMessage, FireBasePush>();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            services.AddMvcCore().AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV").AddJsonFormatters();
            services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder.AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowCredentials());
            });

            ILoggerFactory loggerFactory = new LoggerFactory()
               .AddConsole()
               .AddDebug();

            services.AddSingleton<Microsoft.Extensions.Logging.ILogger>(loggerFactory.CreateLogger("Logger"));

            var database = Configuration["InfluxDBName"];
            var uri = new Uri(Configuration["InfluxURL"]);
            bool HasMonitoring = bool.Parse(Configuration["HasMonitoring"]);

            if (HasMonitoring)
            {
                services.AddMetrics(options =>
                {
                    options.WithGlobalTags((globalTags, info) =>
                    {
                        globalTags.Add("app", info.EntryAssemblyName);
                        globalTags.Add("env", "stage");
                    });
                })
                    .AddHealthChecks()
                    .AddReporting(
                        factory =>
                        {
                            factory.AddInfluxDb(
                                new InfluxDBReporterSettings
                                {
                                    InfluxDbSettings = new InfluxDBSettings(database, uri),
                                    ReportInterval = TimeSpan.FromSeconds(5)
                                });
                        })
                    .AddMetricsMiddleware(options => options.IgnoredHttpStatusCodes = new[] { 404 });
            }

            services.AddMvc(config =>
            {
                if (HasMonitoring)
                {
                    config.AddMetricsResourceFilter();
                }

                config.RespectBrowserAcceptHeader = true;
                config.Filters.Add(new HttpGlobalExceptionFilter(Env));
                config.Filters.Add(new HttpAuthorizationFilter());
            }).AddControllersAsServices().AddJsonOptions(opt =>
            {

            });

            services.AddApiVersioning();

            services.AddSingleton(Configuration);
            services.AddTransient<IDbConnection>(db => new SqlConnection(
                    Configuration["ConnectionString"]));

            services.RegisterDoaminServices();

            ConfigLog();

            services.AddSingleton(Log.Logger);

            services.AddAutoMapper(typeof(MappingProfile));
            //services.AddCors();

            services.AddDistributedRedisCache(options =>
            {
                options.Configuration = Configuration["RedisCnnString"];
            });

            services.AddSingleton<IConnectionMultiplexer>(ConnectionMultiplexer.Connect(Configuration["RedisCnnString"]));

            services.Configure<Audience>(Configuration.GetSection("Audience"));
            services.Configure<CacheTimeoutConfiguration>(Configuration.GetSection("CacheTimeOut"));

            services.AddSingleton<IMSFCacheManager, Core.MSFA.Core.Cache.CacheManager>();

            var ActiveScheduler = Configuration["ActiveScheduler"];
            if (!string.IsNullOrEmpty(ActiveScheduler) && bool.Parse(ActiveScheduler))
            {
                Log.Information("Scheduleder Start");
                services.AddSingleton<IScheduledTask, NotificationTask>();
                services.AddSingleton<IScheduledTask, PackageInviteTask>();
            }

            services.AddScheduler((sender, args) =>
            {
                Log.Information(args.Exception.Message);
                args.SetObserved();
            });

            //Needed for accessing action context in the tag helpers
            services.TryAddSingleton<IActionContextAccessor, ActionContextAccessor>();

            services.RegisterAllTypes<IEntityValidator<IEntity>>(new[] { typeof(LevelValidator).Assembly });

            var serviceProvider = services.BuildServiceProvider();
            ServiceProviderHandler.Initialize(serviceProvider);
        }

And this is Configure : 

        public virtual void Configure(IApplicationBuilder app, IHostingEnvironment env, IHttpContextAccessor contextAccessor, ILoggerFactory loggerFactory,IServiceProvider serviceProvider, IApplicationLifetime lifetime)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            bool HasMonitoring = bool.Parse(Configuration["HasMonitoring"]);

            if (HasMonitoring)
            {
                app.UseMetrics();
                app.UseMetricsReporting(lifetime);
            }

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseStaticFiles();

            app.UseCors("CorsPolicy");
            app.UseMvc();

            app.UseMvc(routes =>
            {
                routes.MapRoute("default", "{controller=Home}/{action=Index}/{id?}");
            });
}

So of course Monitoring is enabled from setting, Also HealthCheck part is working and is sending the datas into the InfluxDB. The main problem is this line config.AddMetricsResourceFilter(); 
which should be called for each request but it does not.

**Comment by alhardy** [comment]
Have you compared to the sample projects provided?

**Comment by JoobinMo** [comment]
Hi thanks for the reply, Yea I did actually the package has changed in the newer versions so I have figure it already :) .
