### ISSUE TITLE
AppMetrics endpoint routing?

### ISSUE THREAD

**Issue by NinoFloris** [AppMetrics/AppMetrics#424]
Now that 3.0 is getting more ready each day, where old routing is obsolete.
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/
>While it’s still possible to use the old UseMvc() or UseRouter() middleware in a 3.0 application, we recommend that every application migrate to Endpoint Routing if possible. We are taking steps to address compatibility bugs and fill in previously unsupported scenarios. We welcome your feedback about what features are missing or anything else that’s not great about routing in this preview release.

2.2 has had endpoint routing support for a while now too. 
Is support for it coming to AppMetrics?

**Comment by razfriman** [comment]
Yes please!!

**Comment by raz-canva** [comment]
I have traced it down to `ResolveMatchingTemplateRouteAsync` which is using the MVC-style route data to resolve route names.

This needs to also check for the newer Endpoint Routing feature (e.g. `RouteEndpoint`)
