### ISSUE TITLE
ElasticSearch Health Reporter

### ISSUE THREAD

**Issue by rohan-buchner** [AppMetrics/AppMetrics#429]
I have created a very basic implementation of a health reporter that reports to ElasticSearch. (Only because of the current [ElasticReporter not functioning)](https://github.com/AppMetrics/Elasticsearch/issues/27) 

The difference being that THIS implementation is for Health ONLY/specifically. Thus not to be confused with the current Metric Elastic Search Reporter.

[Health-Reporter-ElasticSearch](https://github.com/rohan-buchner/Elasticsearch/tree/Health-Reporter-ElasticSearch)

I basically cloned the Slack Health Reporter, added NEST, and tried to stick to the existing structure only tweaking where needed.

**A few questions/comments:**
1.)Would this be something that is even worth submitting back to the project? 

2.) As I (assume) realise, via means of reporting taking Health metrics to the `healthBuilder.Report.ToMetrics` module, and then using the standard Metric Reporter to report to ElasticSearch... I can maybe achieve the same thing? (thus is this duplicated effort)

3.) I'm aware that the NEST NuGet module I'm using is dotnet core only (and I haven't investigated if there is a net461 version (as I'm developing on OSX), I'll be honest, I'm not going to write a 461 implementation at this stage.

**Comment by alhardy** [comment]
Planning to remove the health check related implementation due to there being a Microsoft equivalent
