### ISSUE TITLE
AddHttpPostCheck Extension

### ISSUE THREAD

**Issue by rohan-buchner** [AppMetrics/AppMetrics#430]
There is a super nice `AddHttpGetCheck` built in extension... But this does not work so well for 3rd party services that is a dependency for some of our systems. E.g If a payment gateway is down, we'd like the health check to fail, then have our infra-swap over to another provider... 

I've locally added a `AddHttpPostCheck` which is just a clone of `AddHttpGetCheck` but it allows me to pass in some HTTP content.

```
  public static IHealthBuilder AddHttpPostCheck(
            this IHealthCheckBuilder healthCheckBuilder,
            string name,
            Uri uri,
            HttpContent content, <-------------
            TimeSpan timeout,
            HealthCheck.QuiteTime quiteTime,
            bool degradedOnError = false)
```

I believe this might be useful for others/to add it into the existing pre-build check extensions? (If this is perhaps seen as something that would be useful to others, I can make a PR with the new extension added...)

**Comment by alhardy** [comment]
Planning to remove the health check related implementation due to there being a Microsoft equivalent
