### ISSUE TITLE
Comparison with OpenCensus 

### ISSUE THREAD

**Issue by ramonsmits** [AppMetrics/AppMetrics#431]
How does AppMetrics compare to OpenCensus and more specifically to its c# client?

- https://github.com/census-instrumentation/opencensus-csharp/

Both seem to be framework to setup the collection of metrics and to get the metrics data converted into a supported data store.

**Comment by ramonsmits** [comment]
@alhardy Was this already answered somewhere?

**Comment by alhardy** [comment]
No it wasn't. I haven't looked at that project, tickets fairly dated with no response so closed it off.

Do you have anything to share in terms of a comparison?

**Comment by ramonsmits** [comment]
@alhardy No, unfortunately not. It's my question hence why I asked if maybe there is some comparison docs available somewhere.
