### ISSUE TITLE
Can we remove metrics that haven't been updated for a period?

### ISSUE THREAD

**Issue by MartinJarvisTix** [AppMetrics/AppMetrics#438]
In our use case we want to be able to tag metrics with a client account identifier in a multi-tenanted application.  We've got the tagging working, but after a metric has been created with a tag it seems to be kept in memory from that point on, even after hours/days of not being updated.

I can understand why in most cases you would want this, but in our case it looks much like a memory leak. 

Is there a way to remove older metrics programatically?

**Comment by plachor** [comment]
Maybe in a form of optional sliding expiration argument?

**Comment by kwinkel** [comment]
Having the same use case. I think there should be an option to clear the metrics after publishing them.
https://github.com/AppMetrics/AppMetrics/blob/7474c6552f8474b705036a76e81c44c1be6ec791/src/Core/src/App.Metrics.Core/Internal/DefaultMetricContextRegistry.cs#L121

**Comment by alhardy** [comment]
[This](https://github.com/AppMetrics/AppMetrics/pull/508) was merged in the 4.1.0 release

**Comment by kwinkel** [comment]
It's not about resetting the value to zero, but to remove it from memory at all.
I would suggest to add a Property to the MetricOptions like `FlushOnReport` to remove the metric after reporting.
For my use-case, I really want to get rid of zero-valued Metrics.

Sample output:
```
# TIMESTAMP: 637293781104534594
# MEASUREMENT: [Metrics Spam] test
# TAGS:
                 param1 = 1166
       application_name = Metrics Spam
    application_version = 1.0.0
application_environment = Development
application_deployment = dev
                  mtype = counter
                   unit = none
# FIELDS:
                  value = 0
--------------------------------------------------------------
# TIMESTAMP: 637293781104534594
# MEASUREMENT: [Metrics Spam] test
# TAGS:
                 param1 = 1170
       application_name = Metrics Spam
    application_version = 1.0.0
application_environment = Development
application_deployment = dev
                  mtype = counter
                   unit = none
# FIELDS:
                  value = 0
--------------------------------------------------------------
# TIMESTAMP: 637293781104534594
# MEASUREMENT: [Metrics Spam] test
# TAGS:
                 param1 = 1174
       application_name = Metrics Spam
    application_version = 1.0.0
application_environment = Development
application_deployment = dev
                  mtype = counter
                   unit = none
# FIELDS:
                  value = 0
```

param1 may be a tag which changes a lot, eg. an user-id
without the ability to optionally flush zero-valued metrics, the memory and network-io usage will explode after time

**Comment by maxim-pop** [comment]
We are facing same memory leak issue. The library keeps metrics in memory forever. Instead for event based metrics with multiple dimensions (e.g. incoming http requests by url) cache must be cleaned up after flush.

**Comment by alhardy** [comment]
https://github.com/AppMetrics/AppMetrics/issues/609
