### ISSUE TITLE
invalid metric type "dictionary_file_words_count untyped"

### ISSUE THREAD

**Issue by risingl** [AppMetrics/AppMetrics#439]
![111](https://user-images.githubusercontent.com/51189122/58613936-9462bb00-82e9-11e9-9f4d-9800bcbb37d3.PNG)

May 30 02:45:49 localhost prometheus: level=warn ts=2019-05-30T06:45:49.531054232Z caller=scrape.go:804 component="scrape manager" scrape_pool=mysql-server-master target=http://10.25.8.19:9104/metrics msg="append failed" err="invalid metric type \"dictionary_file_words_count untyped\""
May 30 02:46:00 localhost prometheus: level=warn ts=2019-05-30T06:46:00.016145643Z caller=scrape.go:804 component="scrape manager" scrape_pool=mysql-server-slave target=http://10.25.8.20:9104/metrics msg="append failed" err="invalid metric type \"dictionary_file_words_count untyped\""
May 30 02:46:04 localhost prometheus: level=warn ts=2019-05-30T06:46:04.535013717Z caller=scrape.go:804 component="scrape manager" scrape_pool=mysql-server-master target=http://10.25.8.19:9104/metrics msg="append failed" err="invalid metric type \"dictionary_file_words_count untyped\""
May 30 02:46:15 localhost prometheus: level=warn ts=2019-05-30T06:46:15.019218802Z caller=scrape.go:804 component="scrape manager" scrape_pool=mysql-server-slave target=http://10.25.8.20:9104/metrics msg="append failed" err="invalid metric type \"dictionary_file_words_count untyped\""

**Comment by risingl** [comment]
![image](https://user-images.githubusercontent.com/51189122/58614112-0fc46c80-82ea-11e9-95c1-d71b38e71228.png)

**Comment by risingl** [comment]
Does anybody have the same problem?

**Comment by alisaeed12** [comment]
I didn`t find the solution on the Internet and here too, but I fix this problem.

This problem apparently caused to pluggin:
mysql> SHOW VARIABLES LIKE '%dictionary%';
+-----------------------------------+-------+
| Variable_name | Value |
+-----------------------------------+-------+
| validate_password.dictionary_file | |
+-----------------------------------+-------+
1 row in set (0.00 sec)

To resolve this problem, I disabled in the mysql:

mysql> SELECT @@plugin_dir;
+--------------------------+
| @@plugin_dir |
+--------------------------+
| /usr/lib64/mysql/plugin/ |
+--------------------------+
1 row in set (0.00 sec)

mysql> UNINSTALL COMPONENT 'file://component_validate_password';

Restart mysql and the mysqld_export connect to Prometheus.

Thanks
Ali Saeed
