### ISSUE TITLE
New reporter appmetrics-applicationinsights

### ISSUE THREAD

**Issue by jdvor** [AppMetrics/AppMetrics#440]
@alhardy Could you list https://github.com/jdvor/appmetrics-applicationinsights in  https://www.app-metrics.io/reporting/reporters/ ?

**Comment by alhardy** [comment]
Done. Could you add some basic docs to the page > https://github.com/AppMetrics/Docs.V2.Hugo/blob/dev/content/reporting/reporters/app-insights.md

**Comment by jdvor** [comment]
PR https://github.com/AppMetrics/Docs.V2.Hugo/pull/51
