### ISSUE TITLE
Version conflict detected

### ISSUE THREAD

**Issue by piko123us** [AppMetrics/AppMetrics#444]

**Comment by piko123us** [comment]
HI 
I tried installing App metrics on my Core project .However i am getting the following error

Version conflict detected for Microsoft.AspNetCore.Antiforgery. Install/reference Microsoft.AspNetCore.Antiforgery 2.2.0 directly to project AppMEtricsDemo to resolve this issue. 
 AppMEtricsDemo -> App.Metrics.AspNetCore.Mvc 3.1.0 -> Microsoft.AspNetCore.Mvc 2.2.0 -> Microsoft.AspNetCore.Mvc.ViewFeatures 2.2.0 -> Microsoft.AspNetCore.Antiforgery (>= 2.2.0) 
 AppMEtricsDemo -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.AspNetCore.Antiforgery 


Please suggest..

**Comment by alhardy** [comment]
Have you tried upgrading Microsoft.AspNetCore.App?

**Comment by piko123us** [comment]
> Have you tried upgrading Microsoft.AspNetCore.App?
To Which version ??can you please specify..

**Comment by alhardy** [comment]
Have you tried referring to the sample aspnetcore apps ?https://github.com/AppMetrics/AppMetrics/tree/dev/src/AspNetCore/sandbox
