### ISSUE TITLE
Reporting to InfluxDB stops after some time

### ISSUE THREAD

**Issue by uveta** [AppMetrics/AppMetrics#445]
Hello,

I am experiencing problems when reporting metrics from my asp net core application to InfluxDB. The application has default metrics configured per asp net core web metrics guide [https://www.app-metrics.io/web-monitoring/aspnet-core/tracking-middleware](url)

After unspecified period of time application simply stops reporting metrics data to InfluxDB and does not recover from it. I have tried redirecting AppMetric logs but have not seen any error or warning. I have attached partial logs for one such occurrence, around the time when metrics reporting stopped (last received report was at 17:19:15). Especially interesting is the following part, where DefaultForwardDecayingReservoir simply appears to stop after creating a snapshot at 17:19:16.

> 17:19:16 App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir: Lock entered for App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir snapshot
> 17:19:16 App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir: Lock exited after getting App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir snapshot
> 17:19:16 App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir: Retrieved App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir snapshot
> 17:19:16 App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir: Getting App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir snapshot
> 17:19:16 App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir: Lock entered for App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir snapshot
> 17:19:16 App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir: Lock exited after getting App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir snapshot
> 17:19:16 App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir: Retrieved App.Metrics.ReservoirSampling.ExponentialDecay.DefaultForwardDecayingReservoir snapshot
> 17:19:20 App.Metrics.Scheduling.DefaultMeterTickerScheduler: 5 meters all ticked in 55 ticks using App.Metrics.Scheduling.DefaultMeterTickerScheduler
> 17:19:20 App.Metrics.Scheduling.DefaultMeterTickerScheduler: Starting App.Metrics.Scheduling.DefaultMeterTickerScheduler scheduler
> 17:19:20 App.Metrics.Scheduling.DefaultMeterTickerScheduler: App.Metrics.Scheduling.DefaultMeterTickerScheduler scheduler started
> 17:19:25 App.Metrics.Scheduling.DefaultMeterTickerScheduler: 5 meters all ticked in 58 ticks using App.Metrics.Scheduling.DefaultMeterTickerScheduler
> 17:19:25 App.Metrics.Scheduling.DefaultMeterTickerScheduler: Starting App.Metrics.Scheduling.DefaultMeterTickerScheduler scheduler
> 17:19:25 App.Metrics.Scheduling.DefaultMeterTickerScheduler: App.Metrics.Scheduling.DefaultMeterTickerScheduler scheduler started
> 17:19:30 App.Metrics.Scheduling.DefaultMeterTickerScheduler: 5 meters all ticked in 84 ticks using App.Metrics.Scheduling.DefaultMeterTickerScheduler
> 17:19:30 App.Metrics.Scheduling.DefaultMeterTickerScheduler: Starting App.Metrics.Scheduling.DefaultMeterTickerScheduler scheduler
> 17:19:30 App.Metrics.Scheduling.DefaultMeterTickerScheduler: App.Metrics.Scheduling.DefaultMeterTickerScheduler scheduler started
> 17:19:35 App.Metrics.Scheduling.DefaultMeterTickerScheduler: 5 meters all ticked in 62 ticks using App.Metrics.Scheduling.DefaultMeterTickerScheduler

Please note that there is a second service for which i configured AppMetrics reporting to same InfluxDB instance, and that one did not show any of the symptoms. Are there any additional logs which I could check or do you have any other suggestions for my issue?

[appmetrics.log](https://github.com/AppMetrics/AppMetrics/files/3275283/appmetrics.log)

**Comment by alhardy** [comment]
cannnot replicate
