### ISSUE TITLE
Question: Which metric can be used to track the hit rate

### ISSUE THREAD

**Issue by sleemer** [AppMetrics/AppMetrics#447]
What is the recomended way to track the hit rate using AppMetrics? Correct me if I'm wrong, but it seems like Meter doesn't provide what I need: to measure the (e.g. cache) hit rate, that can be calculated as **keyspace_hits / (keyspace_hits + keyspace_misses)**.

**Comment by alhardy** [comment]
What are you referring to re "hit rate", meters are used to measure the rate of things, counters can be used to count things

**Comment by sleemer** [comment]
What I wanted to measure was percentage of hits in the result set cache, compared to the total requests. At the end I managed to find HitRatioGauge https://www.app-metrics.io/getting-started/metric-types/gauges/, that I can use to create what I need. That is great, but not ideal - I have to use 2 separate meters to track the hit ratio of the one value, and then, in order to report it's value I have to create an instance of the HitRatioGauge class. And if I report on the hot path it's not that good for overall performance of my app. Is there better way to do that?
