### ISSUE TITLE
Timer userValue is not passed to the meter

### ISSUE THREAD

**Issue by haefele** [AppMetrics/AppMetrics#448]
I've added some metrics to my application and it's been super easy to get it all setup and working.
Some of these metrics are timers, a combination of histograms and meters if I understood correctly.

I'm passing some `userValue` to the `IMetricsRoot.Measure.Timer.Time` method, and they correctly show up in the histogram as `lastUserValue` and so on.

But they don't end up in the meter as a item.

The relevant code seems to be here:
https://github.com/AppMetrics/AppMetrics/blob/bf425b1eee561390c704a05c9ca281a97a139bda/src/Core/src/App.Metrics.Core/Timer/DefaultTimerMetric.cs#L154

I'm currently using it to time the duration of my HTTP requests, and passing in the URL as a userValue.
Now it would also be super useful to have different meters for each URL, so i can see how often which endpoint is called.

**Comment by alhardy** [comment]
That already comes out of box https://github.com/AppMetrics/AppMetrics/blob/dev/src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/PerRequestTimerMiddleware.cs

**Comment by haefele** [comment]
But for the (admittedly weird) case when I'm not using all the features that come out of the box?
Does it work when I provide Tags for it like it's done in the "out of the box middleware"?
https://github.com/AppMetrics/AppMetrics/blob/0c5212a69423c7d49eee4c82fd0cb2151a532dc8/src/AspNetCore/src/App.Metrics.AspNetCore.Core/Internal/Extensions/MetricsExtensions.cs#L177-L178

I have the same situation for my internal command pattern - the middleware obviously won't help there, so any help is still very much appreciated.

**Comment by ugumba** [comment]
Why was this issue closed?
The "userValue" given to ITimer.NewContext() would be incredibly useful to pass through to prometheus and grafana.
My use case is not for HTTP requests, but for timing compute intensive tasks.
The set of methods running tasks is large and dynamic, so adding a timer for each is prohibitive.
