### ISSUE TITLE
3.1版本无法监控程序

### ISSUE THREAD

**Issue by jerry2000** [AppMetrics/AppMetrics#450]
参考官网例子，使用3.1.0版本无法度量程序，2.0的版本可以正常度量到，能否提供一下3.1的例子？

**Comment by mikejr83** [comment]
Running this through Google Translate:

> Referring to the official website example, the program cannot be measured using version 3.1.0, and the version 2.0 can be measured normally. Can you provide an example of 3.1?

I'm attempting to do the same. Using packages from 3.2.0 are not working correctly. I'm trying to get a health check endpoint running `/health` that returns the status code along with the JSON summary of the checks.

**Comment by alhardy** [comment]
health has been decommissioned.
