### ISSUE TITLE
Repeat the same data

### ISSUE THREAD

**Issue by JiZhangXiong** [AppMetrics/AppMetrics#456]
Repeated data has been reported multiple times

For example, I set the report to 5 seconds, I requested 1 API, but every 5 seconds will report this data，There are 20 identical data in Influxdb

**Comment by alhardy** [comment]
This is expected for certain metrics types which are for example not configured to reset on reporting. Also see the [reservoir sampling](https://www.app-metrics.io/getting-started/reservoir-sampling/) documentation
