### ISSUE TITLE
Avoid reporter flushing previous interval data

### ISSUE THREAD

**Issue by Kamalesh46** [AppMetrics/AppMetrics#458]
Hi,

I am noticing a weird issue, when there are no datapoints for a sliding window interval, reporter which is running in `AppMetricsTaskScheduler` is flushing data from last interval which has datapoints. Is it the expected behavior, if it is do we have any workaround to stop publishing old data. 

Here is `MetricsBuilder` configuration
```
 var metricsLogger = new MetricsBuilder()
                .Configuration.Configure(options =>
                {
                    options.GlobalTags["app"] = DefaultContext;
                    options.GlobalTags["host"] = Environment.MachineName;
                    options.ReportingEnabled = true;
                    options.Enabled = true;
                    options.DefaultContextLabel = DefaultContext;
                })
                .SampleWith.SlidingWindow()
                .Report.OverUdp(options =>
                {
                    options.SocketSettings.Address = config.Value.Host;
                    options.SocketSettings.Port = config.Value.Port;
                    options.MetricsOutputFormatter = formatter;
                    options.Filter = filter;
                    options.FlushInterval = TimeSpan.FromSeconds(config.Value.FlushIntervalInSeconds);
                    options.SocketPolicy = new SocketPolicy();
                }).Build();
```

![Capture](https://user-images.githubusercontent.com/6126239/61477582-9b0ec580-a95d-11e9-994d-921e72dc0c60.JPG)

**Comment by alhardy** [comment]
Try using this reservoir configuration which should give you what you're after https://github.com/AppMetrics/Samples.V2/blob/master/AspNetCore2.Api.Reservoirs/MetricsRegistry.cs#L37
