### ISSUE TITLE
change azure storage account packages to use maintained packages

### ISSUE THREAD

**Issue by chinwobble** [AppMetrics/AppMetrics#461]
The azure packages that appmetrics depends on are no longer maintained by Microsoft and they have created new packages. These include:

https://www.nuget.org/packages/WindowsAzure.Storage

This has been replaced with:
https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/
https://www.nuget.org/packages/Microsoft.Azure.Storage.File/
https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/
https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table

**Comment by alhardy** [comment]
Planning to remove the health check related implementation due to there being a Microsoft equivalent
