### ISSUE TITLE
Prometheus v2.11.1 seems to be unable to parse App Metrics output

### ISSUE THREAD

**Issue by setagana** [AppMetrics/AppMetrics#463]
Hi all,

Hope you can help with this issue - I'm trying to convince my team that we should use App Metrics instead of ElasticAPM for our APM needs.

I'm setting up a demo environment using the latest version of Prometheus (2.11.1) and your NuGet packages, and they don't seem to be playing well together. In Prometheus the target status permanently stays 'Down' with the stated error: **strconv.ParseFloat: parsing "=": invalid syntax**

That error is when using the Plain Text Prometheus format, I switched to that cause I couldn't get the protobuf format to work either, though I didn't remember to capture the error message before I switched.

Current out-put of my metrics-text endpoint (which Prometheus is failing with) is:

```
# TIMESTAMP: 637003822827045303
# MEASUREMENT: [Application.HttpRequests] Apdex
# TAGS:
                 server = RD0003FF5F3589
                    app = Checkout
                    env = release
                  mtype = apdex
                   unit = result
# FIELDS:
                samples = 5
                  score = 1
              satisfied = 4
             tolerating = 1
            frustrating = 0
--------------------------------------------------------------
# TIMESTAMP: 637003822827045303
# MEASUREMENT: [Application.HttpRequests] Active
# TAGS:
                 server = RD0003FF5F3589
                    app = Checkout
                    env = release
                  mtype = counter
                   unit = Active Requests
# FIELDS:
                  value = 0
--------------------------------------------------------------
# TIMESTAMP: 637003822827045303
# MEASUREMENT: [Application.HttpRequests] Transactions Per Endpoint
# TAGS:
                  route = GET api/transactions
                 server = RD0003FF5F3589
                    app = Checkout
                    env = release
                  mtype = timer
                   unit = req
               unit_dur = ms
              unit_rate = min
# FIELDS:
            count.meter = 1
                 rate1m = 0.00224639923754379
                 rate5m = 2.15596837187279
                rate15m = 6.77124132993322
              rate.mean = 0.114921697020513
                samples = 1
                   last = 268.0711
             count.hist = 1
                    sum = 268.0711
                    min = 268.0711
                    max = 268.0711
                   mean = 268.0711
                 median = 268.0711
                 stddev = 0
                   p999 = 268.0711
                    p99 = 268.0711
                    p98 = 268.0711
                    p95 = 268.0711
                    p75 = 268.0711
--------------------------------------------------------------
# TIMESTAMP: 637003822827045303
# MEASUREMENT: [Application.HttpRequests] Transactions Per Endpoint
# TAGS:
                  route = GET api/transactions/{id}
                 server = RD0003FF5F3589
                    app = Checkout
                    env = release
                  mtype = timer
                   unit = req
               unit_dur = ms
              unit_rate = min
# FIELDS:
            count.meter = 3
                 rate1m = 0.0026538071307258
                 rate5m = 2.2290451645691
                rate15m = 6.84689687494603
              rate.mean = 0.347758673383289
                samples = 3
                   last = 0.3425
             count.hist = 3
                    sum = 44.8334
                    min = 0.3425
                    max = 43.8978
                   mean = 14.2961987040157
                 median = 0.5931
                 stddev = 20.2345467011379
                   p999 = 43.8978
                    p99 = 43.8978
                    p98 = 43.8978
                    p95 = 43.8978
                    p75 = 43.8978
--------------------------------------------------------------
# TIMESTAMP: 637003822827045303
# MEASUREMENT: [Application.HttpRequests] Transactions
# TAGS:
                 server = RD0003FF5F3589
                    app = Checkout
                    env = release
                  mtype = timer
                   unit = req
               unit_dur = ms
              unit_rate = min
# FIELDS:
            count.meter = 5
                 rate1m = 0.00094624439122418
                 rate5m = 0.179981861077199
                rate15m = 0.188196663502879
              rate.mean = 0.36012566345903
                samples = 5
                   last = 0.3824
             count.hist = 5
                    sum = 332.3015
                    min = 0.0915
                    max = 287.1417
                   mean = 61.4881608807752
                 median = 0.6301
                 stddev = 108.146885948742
                   p999 = 287.1417
                    p99 = 287.1417
                    p98 = 287.1417
                    p95 = 287.1417
                    p75 = 44.0558
--------------------------------------------------------------
```

My prometheus scrape config looks as follows
```
  - job_name: 'checkout'
    scrape_interval: 10s
    scheme: https
    metrics_path: /metrics-text
    static_configs:
      - targets: ['<<my-host-name>>']
```

There are no network connectivity issues between the target and Prometheus, and the App Metrics packages seem to be doing their work fine. If I can provide any more info to help debug, I'd be happy to do so.

**Comment by setagana** [comment]
I can now add more info about the protobuf side - when trying to scrape the host, prometheus displays the error **expected value after metric, got "MNAME"**

I tried uploading the protobuf file being served by the application to [an online decoder](https://protogen.marcgravell.com/decode) and it indicated the file was of an invalid protobuf format / was corrupted. The metrics protobuf file in question will be available for the next week [here](https://file.io/tapyF9?expires=1w).

**Comment by setagana** [comment]
Went looking into the format of Prometheus a bit more to see if this might be a quick fix that I could PR for you folks - but it looks to me like you guys never implemented support for Prometheus 2, which has been out for around 2 years. I guess I can't recommend anybody to use a library that's fallen that far behind the curve. Pity, cause this is one of the best looking metrics libraries for .NET.

**Comment by Roshek** [comment]
I've had a similar issue (I'm new to Prometheus), but it turns out, after Prometheus 2 they [dropped support](https://github.com/RichiH/OpenMetrics/blob/master/markdown/protobuf_vs_text.md) for the protobuf format, so I guess the protobuff formater is only there to support older Prometheus 1 deployments.

I think the actual problem here might be that you are not using the correct text formatter for your metrics text endpoint, because the output you provided in your first post is formatted using the MetricsTextOutputFormatter, but you should use MetricsPrometheusTextOutputFormatter.

You can read more about this in [the docs](https://www.app-metrics.io/reporting/reporters/prometheus/#asp-net-core-configuration) (which should maybe state that the protobuf format is deprecated so other people don't run into this problem).

**Comment by Roshek** [comment]
I've had a similar issue (I'm new to Prometheus), but it turns out, after Prometheus 2 they dropped support for the protobuf format, so I guess the protobuff formater is only there to support older Prometheus 1 deployments.

I think the actual problem here might be that you are not using the correct text formatter for your metrics text endpoint, because the output you provided in your first post is formatted using the MetricsTextOutputFormatter, but you should use MetricsPrometheusTextOutputFormatter.

You can read more about this in the docs (which should maybe state that the protobuf format is deprecated so other people don't run into this problem).

Edit: after reading your post more carefully I noticed you have tried the prometheus text formatter, but still failed, so other than checking if you set it up correctly, I don't know what is causing your problems. I have a deployment with Prometheus 2.11.1 and App Metrics 3.1 and it works fine for me.

**Comment by setagana** [comment]
That would've been a nice easy fix, Roshek, but I don't think I made any obvious mistakes. Here's the Program.cs contents that weren't working for me:

```
public class Program
    {
        public static void Main(string[] args)
        {
            var metrics = AppMetrics.CreateDefaultBuilder()
                .OutputMetrics.AsPrometheusPlainText()
                .Build();

            CreateWebHostBuilder(args)
                .ConfigureMetrics(metrics)
                .UseMetrics(options => {
                    options.EndpointOptions = endpointsOptions =>
                        {
                            endpointsOptions.MetricsEndpointOutputFormatter = metrics.OutputMetricsFormatters.OfType<MetricsPrometheusTextOutputFormatter>().First();
                        };
                })
                .Build()
                .Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
```

**Comment by Roshek** [comment]
Seems all right, although I used the Startup.cs method to configure the services and the middleware pipeline. Does this generate any output if you call the /metrics endpoint with curl?

**Comment by alhardy** [comment]
Fixed
