### ISSUE TITLE
how to export json source for Grafana

### ISSUE THREAD

**Issue by fawdlstty** [AppMetrics/AppMetrics#465]
Json data sources that suitable grafana require manually supplying urls: /, /search, /query, /annotations. Optional urls: /tag-keys, /tag-values.
What methods should I use in appmetrics to provide access to url requests?

ref: <https://github.com/grafana/simple-json-datasource>

**Comment by alhardy** [comment]
Not sure what is meant by "provide access to url requests?"

In terms of "how to export json source for Grafana" refer to Grafana's docs
