### ISSUE TITLE
RequestTimerMiddleware with Exception in the request

### ISSUE THREAD

**Issue by Sarmuu** [AppMetrics/AppMetrics#468]
So how are request timers tracked when API throws an exception?

Currently I don't think it handles it probably and keeps the request in activeSessions permanently and not log any timer, is this intended?

**Comment by alhardy** [comment]
Looking at the tracking middleware should answer your question https://github.com/AppMetrics/AppMetrics/tree/dev/src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware

**Comment by Sarmuu** [comment]
Yep, I've checked that, currently it does not handle exceptions and does not log the timer when exception occurred in the downstream middleware.

I don't think this is intended?

**Comment by alhardy** [comment]
Fixed
