### ISSUE TITLE
Question: Process metrics

### ISSUE THREAD

**Issue by kimbell** [AppMetrics/AppMetrics#469]
We are currently using another nuget package for handling logging to Prometheus. App.Metrics seems more flexible and something we are considering. 

One of the things our current package has metrics for are things such as memory usage, GC collections, exception count, etc. 

Are any of these types available using one of the many packages under the App.Metrics umbrella?

**Comment by alhardy** [comment]
Nothing out of box, you would have to get those values and use app metrics to track and report

**Comment by dustincjensen** [comment]
@alhardy do you have a suggested method for doing this in a .NET Core Web app? My company also would like to report on memory usage, etc. But I can't find any suggestions about how to add/update those metrics.

Our current implementation provides our own `/metrics` endpoint and updates the CPU, Memory Usage gauges before getting the snapshot. Is there a way to update gauges before the snapshot when using the endpoints middleware that automatically provides the `/metrics` endpoint?

**Comment by alhardy** [comment]
@dustincjensen not sure I understand.

You just have to update the guages anywhere in code and `/metrics` will display the current snapshot

**Comment by pgruderman** [comment]
This is really quite inconvenient.  It's also inefficient since the values are needed only when someone requests metrics.  It would be really nice if there was a way to wire up a gauge directly to the code for calculating it, so that the app metrics library could calculate the value on demand.

**Comment by btshft** [comment]
> This is really quite inconvenient. It's also inefficient since the values are needed only when someone requests metrics. It would be really nice if there was a way to wire up a gauge directly to the code for calculating it, so that the app metrics library could calculate the value on demand.

I also encountered the need to collect metrics on demand. 
I came up with the following solution for .NET Core 3.1 app

```c#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMetrics(s =>
        {
            s.OutputMetrics.AsPrometheusPlainText();
        });

        services.AddMetricsEndpoints(o =>
        {
            o.MetricsEndpointEnabled = true;
            o.MetricsEndpointOutputFormatter = o.MetricsOutputFormatters
                .OfType<MetricsPrometheusTextOutputFormatter>()
                .First();
        });
    }

    public void Configure(IApplicationBuilder app)
    {
        app.UseRouting();
        app.UseEndpoints(endpoints =>
        {
            var metricsApp = endpoints.CreateApplicationBuilder()
                .Use(async (context, next) =>
                {
                    // Simplified for example
                    var metrics = context.RequestServices.GetRequiredService<IMetrics>();

                    metrics.Measure.Counter.Increment(new CounterOptions
                    {
                        Name = "On Demand Counter",
                        ResetOnReporting = false,
                    });

                    await next();
                })
                .UseMetricsEndpoint();

            endpoints.MapGet("/metrics", metricsApp.Build());
        });
    }
}
```
