### ISSUE TITLE
Question: How to get Health Reporting working inWebHost

### ISSUE THREAD

**Issue by DominikPf** [AppMetrics/AppMetrics#472]
I want to report my Health Checks to (in this case) InfluxDb.

The docs are not ready yet:
https://www.app-metrics.io/reporting/health-reporters/metrics/

And the Sample only shows the way to go if i have a *IMetricsBuilder*
https://github.com/AppMetrics/Health/blob/dev/sandbox/HealthSandbox/Host.cs#L106

My App is completely configured in Program.cs via *IWebHost*:
```c#
.ConfigureMetricsWithDefaults((ctx, builder) =>
{
    builder.Report.ToInfluxDb(new MetricsReportingInfluxDbOptions()
    {
        InfluxDb = new InfluxDbOptions
      {
         BaseUri = new Uri(ctx.Configuration["Metrics:Influx:Url"]),
         Database = ctx.Configuration["Metrics:Influx:Database"],
         UserName = ctx.Configuration["Metrics:Influx:UserName"],
         Password = ctx.Configuration["Metrics:Influx:Password"]
       }
    });
})
.ConfigureHealthWithDefaults((ctx, builder) =>
{
     builder.HealthChecks.AddHttpGetCheck("Google", new Uri("https://google.com"), TimeSpan.FromSeconds(10));
     builder.Report.ToMetrics(/*How to get IMetrics?*/)
})
.UseMetricsWebTracking()
.UseHealth()
.UseMetrics()
```

Is there a other way or do i need to have IMetrics (so i will need to configure my app in Startup?)

**Comment by alhardy** [comment]
Planning to remove the health check related implementation due to there being a Microsoft equivalent
