### ISSUE TITLE
TimescaleDB

### ISSUE THREAD

**Issue by Doidel** [AppMetrics/AppMetrics#476]
Just wondering if support for [timescaledb](https://www.timescale.com/) is on the horizon?
Thanks

**Comment by ghd258** [comment]
+1

**Comment by ghd258** [comment]
support for timescaledb

**Comment by alhardy** [comment]
I don't plan to implement any additional reporters in the core repo, it's too much to maintain. Although it'd be great to see other implement additional reporters which I'd be happy to review and reference in AppMetrics documentation
