### ISSUE TITLE
Feature: HttpGetCheck: Allow Setting of Headers (UserAgent)

### ISSUE THREAD

**Issue by jasonkenneth** [AppMetrics/AppMetrics#477]
Problem
We would like to add a UserAgent to the HealthCheck http requests. 

Reason
We have many types of health checks (cloud provider load balancer, kubernetes, prometheus, AppMetrics, etc) that get logged to a logging aggregator. Most of the "checkers" set the UserAgent string making it helpful to quantify the checks in determining load and the source of the load. Having a UserAgent set or being able to set the UserAgent header would help bring AppMetrics in line with the others and make my job easier.

**Comment by alhardy** [comment]
Planning to remove the health check related implementation due to there being a Microsoft equivalent
