### ISSUE TITLE
Graphite URI scheme must be either net.tcp or net.udp or net.pickled (Parameter 'BaseUri')

### ISSUE THREAD

**Issue by mabublue** [AppMetrics/AppMetrics#478]
Trying to report to Graphite but getting the error 'Graphite URI scheme must be either net.tcp or net.udp or net.pickled (Parameter 'BaseUri')' each time (see image 1) below.

I have tried setting the option 'options.Graphite.Protocol' but this appears to be Read Only (see image 2 below).

Any ideas?

(Please note: I am using .NET Core 3.0 rc1 so hoping this is not the issue)

I am running the latest grafana and graphite in docker containers alongside Visual Studio.

Happy to provide more info if required.

Thanks,

Martin

![image](https://user-images.githubusercontent.com/7532751/65383167-977c2e00-dd54-11e9-9c34-6cd30574b4b8.png)

![image](https://user-images.githubusercontent.com/7532751/65383235-95ff3580-dd55-11e9-955a-dba86e127172.png)

**Comment by vhatsura** [comment]
Hey, @mabublue. As I see, your graphite uri is http based. As you can see from error message `Graphite URI scheme must be either net.tcp or net.udp or net.pickled (Parameter 'BaseUri')`, your scheme should be `net.tcp`, `net,udp` or `net.pickled`. The definite scheme depends on your graphite configuration.
So, your graphite address should be `net.tcp://127.0.0.1:2003`, `net.udp://127.0.0.1:2003` or `net.pickled://127.0.0.1:2003`.

**Comment by mabublue** [comment]
@vhatsura Thank you!! I changed http to net.udp and seems to be working. I'll test further tomorrow evening to ensure I can report the metrics, but I am no longer getting an error.

I was following the examples in the documentation which clearly show http in the url (see image below).

Anyway, Problem solved and closing comment.

Martin

![image](https://user-images.githubusercontent.com/7532751/65387100-1db16800-dd87-11e9-9f3f-89bf227a9810.png)

**Comment by madzaf** [comment]
Could someone update the documentation because I just had the exact same misunderstanding ?
