### ISSUE TITLE
Exclude specific endpoint from tracking

### ISSUE THREAD

**Issue by dil-mweber** [AppMetrics/AppMetrics#479]
I have set up the AppMetrics and currently target all the Endpoints. Unfortunatly this contains the "health" checks and we get a lot of data from them so we want to exclude all endpoints with api/health. 

Is there a way to do so in the Startup.cs.

```
                var metrics = AppMetrics.CreateDefaultBuilder().Configuration.Configure(o =>
                    {
                        o.GlobalTags.Add("application", "Test App");
                    })
                    .Report.OverTcp(o =>
                    {
                        o.SocketSettings.Address = configuration.TelegrafHost;
                        o.SocketSettings.Port = int.Parse(configuration.TelegrafPort);
                        o.MetricsOutputFormatter = new MetricsInfluxDbLineProtocolOutputFormatter();
                    });
                services.AddMetrics(metrics);
                services.AddMetricsReportingHostedService();
```

**Comment by vhatsura** [comment]
Hey, @dil-mweber.

You can find documentation about filtering at [filtering metrics page](https://www.app-metrics.io/getting-started/filtering-metrics/).

**Comment by dil-mweber** [comment]
Hi @vhatsura,

thanks for the fast response and the link, my problem was whenever I added a filter form the filtering metrics page I did not receive any metrics anymore.

I figured out now that the name is not what I expected the name looks more like
```
report_success|server:<<computer_name>>,app:Api,env:development,application:<<app name>>
```

Unfortunatly it does not help if I set the filter for example to
```
                    .Report.OverTcp(o =>
                    {
                        o.Filter = new App.Metrics.Filtering.MetricsFilter().WhereNameStartsWith("report_success");
                        o.SocketSettings.Address = configuration.TelegrafHost;
                        o.SocketSettings.Port = int.Parse(configuration.TelegrafPort);
                        o.MetricsOutputFormatter = new MetricsInfluxDbLineProtocolOutputFormatter();
                    });
```
I just do not receive any data. Any suggestions?

**Comment by alhardy** [comment]
You could tag health check results and filter by tag https://www.app-metrics.io/getting-started/filtering-metrics/#metric-tags.
