### ISSUE TITLE
Add 3.2.0-dev0022 versions to NuGet

### ISSUE THREAD

**Issue by NickWel** [AppMetrics/AppMetrics#480]
When using the most recent version on NuGet (3.2.0-dev0002) I get a`System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler'` exception when calling any endpoint on our API. This is currently preventing us from using AppMetrics on some of our services.

I have noticed that the version "3.2.0-dev0022" on MyGet has fixed this issue. Are there any plans to add this version to the NuGet repository?

**Comment by neyromant** [comment]
Seems this fix does not resolve the issue. See [last comment](https://github.com/AppMetrics/AppMetrics/issues/422#issuecomment-534835315)

**Comment by NickWel** [comment]
From personal testing I can confirm that upgrading all AppMetrics packages to 3.2.0-dev0022 did fix the issue. Downgrading to 3.2.0-dev0002 introduces the error again, and upgrading to 3.2.0-dev0022 fixes the error every time

**Comment by neyromant** [comment]
I checked too, indeed, the 3.2.0-dev0022 version fixes the problem

**Comment by pwlsjk** [comment]
I'm confirming, 3.2.0-dev0022 from myget fixes problem.

**Comment by AndyKoopa** [comment]
Any updates on when 3.2.0-dev0022 qill be available in Nuget? I am not seeing that version and I would like to use the latest version with HTTP Auth Token implementation for use in pushing metric data to Splunk.

**Comment by AndyKoopa** [comment]
> I checked too, indeed, the 3.2.0-dev0022 version fixes the problem

> I'm confirming, 3.2.0-dev0022 from myget fixes problem.


Could you tell me the url for the myget repo?

Sorry, haven't used myget before so I am a little confused.

**Comment by NickWel** [comment]
> > I checked too, indeed, the 3.2.0-dev0022 version fixes the problem
> 
> > I'm confirming, 3.2.0-dev0022 from myget fixes problem.
> 
> Could you tell me the url for the myget repo?
> 
> Sorry, haven't used myget before so I am a little confused.

The MyGet repo url is "https://www.myget.org/F/appmetrics"

**Comment by alhardy** [comment]
Done
