### ISSUE TITLE
Failed requests lost or retried?

### ISSUE THREAD

**Issue by pieter-venter** [AppMetrics/AppMetrics#482]
I'm using the InfluxDB reporter. 

If InfluxDB is not reachable for a period of time - do we expect the metrics collected during this period to be lost or retried again when InfluxDB becomes available?

In my testing - it seems the values are lost, creating gaps in the data. Is this by design?
I've configured a FailuresBeforeBackoff and BackoffPeriod.

Is there a built in way to specify that I'd like AppMetrics to keep the Snapshot data until it can be delivered?

**Comment by alhardy** [comment]
There is not built in way to keep metrics in case of the underlying timeseries database is down, I don't plan to support such a feature
