### ISSUE TITLE
Question: Histogram.Count what does this mean and how does it behave?

### ISSUE THREAD

**Issue by impactmrj** [AppMetrics/AppMetrics#483]
I was expecting that everytime one calls update, the count would be incremented.  And by default, the value wouldn't be reset back to zero during the lifetime.  I am seeing that at some point, the count is being reset.  It seems to be related to the reservoir.

**Comment by alhardy** [comment]
Use a [counter](https://www.app-metrics.io/getting-started/metric-types/counters/) instead if you're interested in counting occurances
