### ISSUE TITLE
App.Metrics file locks on redeployment

### ISSUE THREAD

**Issue by nullpainter** [AppMetrics/AppMetrics#487]
I'm using App.Metrics 3.1.0 in an ASP.NET Core application, hosted in IIS (in-process hosting model, if that's relevant), and using out-of-the-box DI.

When re-deploying the application via Octopus, I am consistently getting an access denied error either deleting or replacing `App.Metrics.Abstractions.dll`. Explicitly stopping the site in IIS before deployment resolves the issue.

I am using the Octopus IIS deployment task so I am _assuming_ it's attempting to stop the site gracefully before deleting the directory. Almost all of our applications are using App.Metrics and deployed via Octopus, however this is the first API which is using ASP.NET Core in a .NET Core project. Other APIs are using ASP.NET Core packages in full framework.

I am _guessing_ this error is related to reporting. Is there some sort of shutdown hook I need to register?

FWIW, this is my App.Metrics integration code:

```c#
builder.ConfigureMetricsWithDefaults(metrics =>
{
    var influxOptions = serviceProvider.GetSettings<InfluxDbOptions>();

    metrics.Report.ToInfluxDb(options =>
    {
        options.InfluxDb = influxOptions;
        options.FlushInterval = TimeSpan.FromSeconds(20);
    });
    metrics.Configuration.Configure(options =>
    {
        options.GlobalTags.Add(MetricsTags.Global.MachineName, Environment.MachineName);
        options.GlobalTags.Add(MetricsTags.Global.AppVersion, AppVersionHelper.GetAppVersion());
    });
});
```

**Comment by nullpainter** [comment]
FYI, I have worked around this by adding a step in Octopus to stop the IIS application pool before deployment. Just stopping the site itself wasn't effective, for whatever reason.

**Comment by EriksonGM** [comment]
Where is the solucion???? 

I am having the same error doing CI/CD from GitLab Comunity Edition to IIS, using GitLab Runners.

![imagem](https://user-images.githubusercontent.com/11561779/88197318-30f8c280-cc3a-11ea-9267-ab04afae6002.png)

Everything was ok, untill deployment.

![imagem](https://user-images.githubusercontent.com/11561779/88197423-61d8f780-cc3a-11ea-8cc9-bad13ae861dd.png)

Only when AppMetrics is enabled, if you comment the init process, all run good.

**Comment by No0Vad** [comment]
Currently trying out App-Metrics, and I have the same issue. Found this issue through Google.
I also have a .NET Core site, hosted on IIS, I use the app_offline.htm file to stop the process.

Has worked great so far, until I added App.Metrics and the files remain locked and the process is still running.
