### ISSUE TITLE
Question: How to configure AppMetrics with IHostBuilder?

### ISSUE THREAD

**Issue by delepster** [AppMetrics/AppMetrics#488]
I successfully configured AppMetrics when creating a IWebHostBuilder. How can I do it with a IHostBuilder? The only way I could do it for now is to reverse engineer the current extension methods available for the IWebHostBuilder and manually implement the steps.

**Comment by alhardy** [comment]
Duplicate https://github.com/AppMetrics/AppMetrics/issues/449
