### ISSUE TITLE
Allow custom port mapping

### ISSUE THREAD

**Issue by alhardy** [AppMetrics/AppMetrics#497]
https://github.com/AppMetrics/AppMetrics/commit/d04c25388fece1b99c174e368836eb9b2022cd4a#diff-9589be23977fbf4b05b1d94aa6ba8c13R165

**Comment by dnperfors** [comment]
This issue is currently blocking us from upgrading to version 4.0.0. 
We don't want to expose the metrics outside our cluster, so we need to have it on a different port.
Is it something to consider for the next release?

**Comment by alhardy** [comment]
Happy to take a PR for this if possible? Otherwise not sure when I'll get to this one

**Comment by dnperfors** [comment]
Hi, I have been looking into this and was wondering why AppMetrics would modify the serverurls. This is the part that currently isn't working, however, Microsoft already described very well how to get this working for their [healthcheck endpoints](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1#filter-by-port). 
My suggestion would be to just remove the part where AppMetrics does this and just rely on the developer to sort this out for them selves.
