### ISSUE TITLE
Concurrent health check registration

### ISSUE THREAD

**Issue by embarrassedmilk** [AppMetrics/AppMetrics#504]
Hi,

Not sure if I'm using the tool in a wrong way (v3.2.0), but it doesn't seem to support concurrent health check registration. Here's a sample code that will surface the bug:

```
var healthBuilder = AppMetricsHealth.CreateDefaultBuilder();
Parallel.ForEach(Enumerable.Range(0, 100), (i) => {
    healthBuilder.HealthChecks.AddCheck($"check-{i}",
        () => new ValueTask<HealthCheckResult>(HealthCheckResult.Healthy()));
});
```

If you attempt to run it several times, you will likely get different exceptions, with NRE at `Dictionary` class being thrown most often.

Thanks in advance for any help!

**Comment by alhardy** [comment]
Unfortunately I no longer plan to support the health check implementation which has be removed from the latest preview release. Microsoft have an equivalent that can be used.
