### ISSUE TITLE
Invalid dependency version in the latest preview

### ISSUE THREAD

**Issue by vhatsura** [AppMetrics/AppMetrics#505]
In the latest preview (`4.0.0-preview.0.2`) some of packages has invalid dependency version, e.g. `App.Metrics.AspNetCore` depends on the following packages:

![image](https://user-images.githubusercontent.com/10338692/68019118-f7e38100-fcab-11e9-8899-1abf8c36ffe1.png)

As you can see, `App.Metrics` and `App.Metrics.Extensions.Hosting` have invalid version `4.0.0-preview.0.14` which is missed on nuget and didn't build. I've checked nuspec files from https://dev.azure.com/appmetrics/AppMetrics/_build/results?buildId=145 build and got the following:
```xml
<dependency id="App.Metrics.AspNetCore.Endpoints" version="4.0.0-preview.0.2" exclude="Build,Analyzers" />
<dependency id="App.Metrics.AspNetCore.Tracking" version="4.0.0-preview.0.2" exclude="Build,Analyzers" />
<dependency id="App.Metrics" version="4.0.0-preview.0.14" exclude="Build,Analyzers" />
<dependency id="App.Metrics.Extensions.Hosting" version="4.0.0-preview.0.14" exclude="Build,Analyzers" />
```

**Comment by alhardy** [comment]
@vhatsura fix published
