### ISSUE TITLE
The "OwinMetricsAppBuilderExtensions" is missing from App.Metrics 3.0 version

### ISSUE THREAD

**Issue by ManteshJangond** [AppMetrics/AppMetrics#506]
What is an alternative solution for `OwinMetricsAppBuilderExtensions` in the App.Metrics v3.0? Because this class exists in the App.Metrics v1.0 but not there with the latest version of App.Metrics.

I am using the App.Metrics v3.0 NuGet package for Web Api .Net Framework 4.7.2 project.

**Comment by alhardy** [comment]
You'll have to write that yourself, unfortunately I don't plan to support OWIN

**Comment by ManteshJangond** [comment]
> You'll have to write that yourself, unfortunately I don't plan to support OWIN

Thank you for your reply, could you please suggest me, how to use the AppMetrics in the .Net Framework 4.7.2 Web API project.
