### ISSUE TITLE
.NET core 3 healthchecks

### ISSUE THREAD

**Issue by cyberhck** [AppMetrics/AppMetrics#510]
Hello there,

Thanks for the library, I'm using it often now a days, I wanted to know if there are plans to integrate the .NET core 3 healthchecks on app-metrics, I like the app-metrics one, but I've a requirement to use other as well. Would be nice if we could have some neat integration with those and deprecate the app-metrics one

**Comment by alhardy** [comment]
I've decommissioned my health check implementation due to MS having their own, there is integration to publish health check results as metrics if that's what you're after?

**Comment by cyberhck** [comment]
not sure if that's what I'm after, I kinda wanted to have similar to what appmetrics has, and include some pre-defined healthchecks like pinging, and reporting automatically.

**Comment by alhardy** [comment]
Have you looked at the microsoft implementation?

**Comment by cyberhck** [comment]
Not sure if I missed something,

microsoft has basic healthcheck, right? where I extend a class and implement everything myself?

but AppMetrics includes more than just that, one I liked was ping healthcheck, there was also sql check which I didn't have to implement myself. :) I'll check microsoft's again :)

**Comment by alhardy** [comment]
MS have extensions for different types of health checks like SQL. Doesn't make any real sense to maintain my own when MS have an equivalent now.
