### ISSUE TITLE
Configure AppMetrics in Startup class only

### ISSUE THREAD

**Issue by msschl** [AppMetrics/AppMetrics#512]
I think it would be nice to be able to configure AppMetrics only from the `Startup.cs` class.

Instead of...
```cs
public static void Main(string[] args)
    => CreateHostBuilder(args).Build().Run();

public static IHostBuilder CreateHostBuilder(string[] args)
    => Host.CreateDefaultBuilder(args)
           .ConfigureMetricsWithDefaults((ctx, builder) => {
               builder.Configuration.Configure(config => {
                   config.AddAppTag(ApplicationConstants.APPLICATION_NAME);
                   config.AddEnvTag(ctx.HostingEnvironment.EnvironmentName);
               });
               builder.OutputMetrics.AsPrometheusPlainText();
           })
           .UseMetricsEndpoints()
           .UseMetricsWebTracking()
           .ConfigureWebHostDefaults(webBuilder =>
           {
               webBuilder.UseStartup<Startup>();
           });
```

Something like this:
```cs
public class Program
{
    public static void Main(string[] args)
        => CreateHostBuilder(args).Build().Run();

    public static IHostBuilder CreateHostBuilder(string[] args)
        => Host.CreateDefaultBuilder(args)
               .ConfigureWebHostDefaults(webBuilder =>
               {
                   webBuilder.UseStartup<Startup>();
               });
}

public class Startup
{

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMetrics(config => {
            config.AddAppTag(ApplicationConstants.APPLICATION_NAME);
            config.AddEnvTag(ctx.HostingEnvironment.EnvironmentName);
        });
        services.AddMetricsEndpoints();
        services.AddMetricsTrackingMiddleware();
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment environment, ILogger<Startup> logger)
    {
        app.UseMetricsAllMiddleware();

        app.UseRouting();

        app.UseAuthentication();
        app.UseAuthorization();

        app.UseEndpoints(endpoints =>
        {
            // endpoints.MapMetricsEndpoints();
            endpoints.MapMetricsEndpoints().RequireHost("*:10240");
            endpoints.MapControllers();
        });
    }
}
```

I think this approche is much cleaner than adding AppMetrics to the hostBuilder. I generally don't like modifying the `Program.cs` because I'd like to have all my configuration at one place in one file.

**Comment by Laverlin** [comment]
`    public class Startup
    {
         //...

        public void ConfigureServices(IServiceCollection services)
        {          
            var influxOptions = _configuration.GetSection(nameof(MetricsReportingInfluxDbOptions)).Get<MetricsReportingInfluxDbOptions>();

            var metrics = AppMetrics.CreateDefaultBuilder()
                .OutputMetrics.AsPrometheusPlainText()
                .Report.ToInfluxDb(influxOptions)
                .Build();

            services.AddMetrics(metrics);
        
            services.AddMetricsTrackingMiddleware();
            services.AddMetricsReportingHostedService();
            services.AddMetricsEndpoints(options =>
                options.MetricsEndpointOutputFormatter = metrics.OutputMetricsFormatters.OfType<MetricsPrometheusTextOutputFormatter>().First());
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseMetricsAllMiddleware();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseSerilogRequestLogging();
            
            app.UseRouting();

            app.UseAppMetricsEndpointRoutesResolver();

            app.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllers();
                   
                });
            app.UseMetricsAllEndpoints();
        }
`
Works for me, for both influx and prometheus.

**Comment by msschl** [comment]
Yes you are right. I found that solution a few days ago as well. But wouldn’t it be nice to just have an `services.AddMetrics()` method. This method could also return an IMetricsBuilder and you could chain your setup Method together like this:

```cs
services.AddMetrics(options => {})
    .AddInfluxDb(options);
```

Or something like this. @Laverlin your way works totally fine. I would also be fine using this way. This are just some design thoughts. :-)
