### ISSUE TITLE
.net 4.5.2 sample 404

### ISSUE THREAD

**Issue by mlapaglia** [AppMetrics/AppMetrics#515]
The sample link [here](https://www.app-metrics.io/samples/metrics-code/#net452-metrics-console-sln) points to a non existent url. https://github.com/AppMetrics/Samples.V2/tree/master/Net452.Metrics.Console.QuickStart

I'm also looking for an example of using v3 with a .net 4.5.2 console application, I can get the reporter to send `appmetrics.internal__report_success` just fine, but none of my metrics.

**Comment by thiagoloureiro** [comment]
Same here, looks like they discontinued the .NET Framework version. I can't find anything

**Comment by dzemaitis** [comment]
hey, @mlapaglia did you find something to monitor 4.5.2 apps?

**Comment by mlapaglia** [comment]
After troubleshooting I got it to send metrics. I was accustomed to the .net core library that populates a required set of tags for you. Since I was not sending those with the 4.5.2 library I wasn't seeing any stats.

```
return AppMetrics.CreateDefaultBuilder()
                .Configuration.Configure(options =>
                {
                    options.GlobalTags["app"] = CurrentServiceName;
                    options.GlobalTags["env"] = EnvironmentName;
                })
                .Report.ToInfluxDb(options =>
                {
                    options.InfluxDb.BaseUri = new Uri(influxDbEndpoint);
                    options.InfluxDb.Database = influxDbName;
                    options.InfluxDb.UserName = influxUsername;
                    options.InfluxDb.Password = influxPassword;
                })
                .Build();
```

Got it working for me. The key parts are the `GlobalTags`.

**Comment by nick-kompas-cko** [comment]
How do you expose the metrics with prometheus, if you are in a forms application? Do I need to build a custom metrics server?

**Comment by mlapaglia** [comment]
I use influxdb, can't help you there.

**Comment by alhardy** [comment]
net 4.5.2 no longer supported
