### ISSUE TITLE
3xx HTTP status codes are counted as errors

### ISSUE THREAD

**Issue by otto-gebb** [AppMetrics/AppMetrics#516]
The success of an HTTP response is defined incorrectly right now:

```cs
public static bool IsSuccessfulResponse(this HttpResponse httpResponse)
{
    return httpResponse.StatusCode >= StatusCodes.Status200OK && httpResponse.StatusCode < StatusCodes.Status300MultipleChoices;
}
```

3xx status codes are considered "unsuccessful", but they should not be.
E.g. there is nothing unsuccessful about a `304 Not Modified` response.

Maybe this was implemented to be consistent with [HttpResponseMessage.IsSuccessStatusCode](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs#L143), but I think it does not have to be. On the client we may want to have a stricter check of the status code (200..299), e.g. to make sure we are safe to read the body, but on the server the notion of success should be less strict, otherwise the metric `OneMinErrorPercentageRate` and the like give false alarms.

I propose to change the above method to
```cs
public static bool IsSuccessfulResponse(this HttpResponse httpResponse)
{
      return httpResponse.StatusCode < StatusCodes.Status400BadRequest;
}
```

**Comment by franjom** [comment]
Or you could just configure it...

`.UseMetricsWebTracking(o =>
                {
                    o.IgnoredHttpStatusCodes = new List<int>
                    {
                        101, 304
                    };
                })`

**Comment by otto-gebb** [comment]
@franjom this is the workaround I'm currently using, but unfortunately it has a side effect of excluding the responses from the `application_httprequests_transactions_per_endpoint` metric, so the fix is still necessary, as I see it.

**Comment by GnktYnk** [comment]
I agree with @otto-gebb for example on IdentityServer when token is issued it returns 302 redirect status code. So in that case either accept false positives or ignore related path at all by ignoring via options. 

I don't know what you think but maybe it would be nice to provide a function delegate to let client set up what is successful or not.
