### ISSUE TITLE
[Feature Request] Add support to post metrics to CloudWatch Metrics

### ISSUE THREAD

**Issue by Downright-Development** [AppMetrics/AppMetrics#517]
Currently my team uses CloudWatch Metrics. This is a feature request to add native support to CloudWatch Metrics. This should keep in mind the CW limitations:

PutMetricData request | 40 KB for HTTP POST requests. PutMetricData can handle 150 transactions per second (TPS), which is the maximum number of operation requests you can make per second without being throttled.You can request a quota increase.

Apparently the request *should* support a Gzipped payload, but the .NET SDK does not. I've created github issue https://github.com/aws/aws-sdk-net/issues/1464 for this reason.

**Comment by alhardy** [comment]
Hi @Downright-Development, I don't plan to add support for additional reporters in the core library, it's just too much to maintain. Although I'd be happy to reference a community devloped reporter in documentation etc.
