### ISSUE TITLE
App.Metrics.AspNetCore.Mvc.Core performance issues on netcore 3.0 due to missing type MvcAttributeRouteHandler

### ISSUE THREAD

**Issue by AlexHorlenko** [AppMetrics/AppMetrics#519]
During our microservice performance test after migrating all stuff to netcore 3.0 we saw not observed  before issue with low CPU saturation. After searching we concluded that the actual problem was inside one of your components, that was misbehaving.

https://github.com/AppMetrics/AppMetrics/blob/dev/src/AspNetCore/src/App.Metrics.AspNetCore.Mvc.Core/MvcRouteTemplateResolver.cs

    try {
    // *IMPORTANT* this hack is throwing exception for every request.
    // It's hack to catch TypeLoadException
        Func<IList<IRouter>, ActionDescriptor[]> func = routersList =>
        {
            var attributeRouteHandler = routersList.FirstOrDefault(r => r.GetType().Name == nameof(MvcAttributeRouteHandler))
                as MvcAttributeRouteHandler;
                
            return attributeRouteHandler?.Actions;
        };
                
        return func(routers);
    }
    catch (TypeLoadException)
    {
        return null;
    }

`

As described in comment, we always get TypeLoadException due to MvcAttributeRouteHandler changed location in netcore packages. And when exception is thrown on every request it has a negative effect.

Either way I suggest to do either of things:
1) port this lib to netcoreapp3.0
2) not use this code at all (we used this approach to have our own IRouteNameResolver for netcoreapp3_0 which did nothing, as route was built by different part of code as before, but without exceptions)
3) as everything inside this class has dependency on routeData.Routers - you can just check for routeData.Routers.Any() in the beginning. It is bad, but still better that what you currently have

To check that this was not done due to our incorrect usage of libraries, I tried the same on your MetricsSandboxMvc project with same results.

I have some investigation data if you need any.

**Comment by alhardy** [comment]
Any chance you could provide a PR with the fix?

**Comment by AlexHorlenko** [comment]
yup, no problem

**Comment by stukselbax** [comment]
@AlexHorlenko any news?

Looks like @alhardy busy enough to continue support this awesome library.

**Comment by AlexHorlenko** [comment]
@stukselbax sorry, forgot about it. Will open a PR today or tomorrow

**Comment by alhardy** [comment]
Fixed
