### ISSUE TITLE
No Timer average in Prometheus formatter output

### ISSUE THREAD

**Issue by ssttgg** [AppMetrics/AppMetrics#524]
We are migrating to Prometheus and have noticed the current formatter does not output the average for timers, just the quantiles, sum and count (these can't be used to calculate the window average).

Sadly, a lot of our existing monitoring, which we are trying to not break by moving collection over to Prometheus, relies on this value. 

I looked into the history of the formatter and couldn't see any hard reason why it's not there - merely that the original developer didn't need it. And, as the existence of #464 shows, I don't believe you can compute this value using Prometheus itself.

Do you think this could be added? I am happy to put together a PR if you think this is reasonable?

**Comment by konstantinsuslov** [comment]
I faced the same problem too, and my solution was to use such prometheus request
`avg(irate(some_metrics_sum[1m]) / irate(some_metrics_count[1m]))`
it should be very close to average, i suppose. But nevertheless it would be useful to have average as separate metric, or may be even somehow allow user to customise what metrics (quantiles, average and others) to collect
