### ISSUE TITLE
Sliding Window Reservoir ignores a majority of data points for high throughput reporting ?

### ISSUE THREAD

**Issue by hiteshmadan** [AppMetrics/AppMetrics#526]
The default Sliding Window Reservoir's Snapshot uses the captured values to calculate all the aggregate metrics such as mean/min/max.
Lets say I'm reporting 10k latency measurements a second, and only want to report out the metrics once a minute while not losing insight into the "true" mean/min/max aggregates, I need a sample size of 600k entries which'll be pretty expensive due to the Array Sort / LOH allocations every minute.

For now I've created a custom reservoir and snapshot class that only keeps sum/count/min/max stored, and reports a zero for all the other measures (median/stddev/percentiles).

What is the best way to address this scenario without spiking CPU/LOH allocations every minute ?

**Comment by alhardy** [comment]
If that's an issue given the load of your system, consider using something like statd instead of having your app performan sampling/aggregations using something like AppMetrics
