### ISSUE TITLE
Getting Started docs for console app not working?

### ISSUE THREAD

**Issue by chuck-frazier** [AppMetrics/AppMetrics#527]
ReportRunner is an unknown identifier.  I cannot find it anywhere in the documentation.

https://www.app-metrics.io/getting-started/

public static class Program
{
    public static async Task Main()
    {
        var metrics = new MetricsBuilder()
            .Report.ToConsole()
            .Build();
        var counter = new CounterOptions { Name = "my_counter" };
        metrics.Measure.Counter.Increment(counter);

        await Task.WhenAll(metrics.**ReportRunner**.RunAllAsync());
        System.Console.ReadKey();
    }
}

**Comment by alhardy** [comment]
It exists, you can find an example app [here](https://github.com/AppMetrics/AppMetrics/blob/dev/src/Core/sandbox/MetricsSandbox/RecordAndReportHostedService.cs#L74)
