### ISSUE TITLE
The invoked member is not supported in a dynamic module

### ISSUE THREAD

**Issue by jonmiller1** [AppMetrics/AppMetrics#542]
I love the app-metrics library.  I'm trying to get it going in a Blazor webassembly application using the current preview 3.2 preview 4.  I realize I'm asking a lot since blazor webassembly is still in preview.

When I create a new metrics class, it immediately explodes with the error "The invoked member is not supported in a dynamics module".   I don't know where to go from here.

Here's my code that explodes.  Any help or ideas would be appreciated.

var metrics = AppMetrics.CreateDefaultBuilder().Build();

**Comment by alhardy** [comment]
Glad you like it. Unfortunately I don't have any experience with Blazor and don't have time at the moment to investigate this
