### ISSUE TITLE
Add tags after timer has started

### ISSUE THREAD

**Issue by mlapaglia** [AppMetrics/AppMetrics#544]
Is there a way to add additional `MetricTags` after a time using statement has started?

Something like:
```
using (var timer = _metrics.Measure.Timer.Time(_queryDupesOptions))
{
	var results = await context.blah
		.Where(whatever)
		.ToListAsync();

	timer.Tags.Add("key", results.First().Id);
}
```

Since the field I want to record is in the result of what is being timed I can't add it afterwards.

**Comment by alhardy** [comment]
No there is not, you start a stopwatch and and set the value on the timer with tacks after the action
