### ISSUE TITLE
ASP.NET Core web sockets get reported as very long transactions using the built in middleware

### ISSUE THREAD

**Issue by lscpike** [AppMetrics/AppMetrics#545]
If using web sockets the aspnet core pipeline is invoked on the initial upgrade connection request and lasts until the socket disconnects. To the middleware this appears as a very long transaction. This also appears as an active request for the lifetime of the web socket.

I have a solution for this that filters web socket requests from the request, per request, and active request middleware. It also adds a separate "Active Web Sockets" metric in the active request middleware.

Does that sound like a good change? If so I'll raise a PR. 

One downside is it depends on the AppMetrics middleware sitting after the WebSocketsMiddleware (UseWebSockets) in the pipeline. It's a very unobvious requirement that many people are going to miss.

**Comment by alhardy** [comment]
Yes this sounds like a good update :+1:
