### ISSUE TITLE
How to delete a custom metric?

### ISSUE THREAD

**Issue by linjmeyer** [AppMetrics/AppMetrics#547]
I am using the library in an ASP Core 3.1 app, in that app I scrape some APIs that don't have metrics and create metrics based on the values in the APIs being scraped.

When the API no longer outputs a particular value, the corresponding metric should be removed.  I can't seem to find a way to delete a metric, only set the value to 0.  Is that possible?

Here is a simple example of what my code looks like so far:

```csharp
private readonly IMetrics _metrics;
// ...
public void DoThing()
{
   _metrics.Measure.Gauge.SetValue(_myGauge, _myTags, _myValue);
}
```

I looked at the docs and the filter option seems close but not exactly what I'm looking for.  Are there any other options?  Thanks!

**Comment by alhardy** [comment]
There is no option to "delete" a metric, typically metrics just change value and have no need to be deleted.
