### ISSUE TITLE
Metric is not resetting with scheduler 

### ISSUE THREAD

**Issue by wywy1024** [AppMetrics/AppMetrics#554]
I am using a scheduler and outputFormatter to write metrics. However each time after send when WriteAsync is called the metric snapshot is not reset.

MetricsEmitter
```
                    var scheduler = new AppMetricsTaskScheduler(
                    TimeSpan.FromSeconds(this.metricsEmitterSettings.TaskSchedularInSecond),
                    async () =>
                    {
                        await Task.WhenAll(this.metrics.ReportRunner.RunAllAsync());
                    });

                scheduler.Start();
```

MetricsOutputFormatter
```
        public Task WriteAsync(
            Stream output,
            MetricsDataValueSource snapshot,
            CancellationToken cancellationToken = default)
        {
            using (var streamWriter = new StreamWriter(output))
            {
                serializer.Serialize(streamWriter, snapshot);
            }
            return Task.CompletedTask;
        }
```

MetricsEmitter is only called once, so the counter should be reset after first WriteAsync
```
metricsEmitter.Send(CommonMetricsEmittingList.HeartBeat);
```

**Comment by alhardy** [comment]
Have you checked that `ResetOnReporting` is set on the metric options of the metric which you are reporting?

**Comment by wywy1024** [comment]
Yes the CommonMetricsEmittingList.heartbeat has that property set. 

Do I need to add this line in my scheduler?

_metrics.Provider.Counter.Instance(sentEmailsCounter).Reset();

**Comment by wywy1024** [comment]
```
        public static CounterOptions HeartBeat => new CounterOptions
        {
            Name = "HeartBeat",
            MeasurementUnit = Unit.Events,
            ResetOnReporting = true
        };
```

**Comment by wywy1024** [comment]
Ping, any suggestions?

**Comment by alhardy** [comment]
@wywy1024 I've tested [here](https://github.com/AppMetrics/AppMetrics/blob/features/4.2.0/src/Core/sandbox/MetricsSandbox/ApplicationsMetricsRegistry.cs#L25) by setting `ResetOnReporting` to true and false, it appears to be working correctly
