### ISSUE TITLE
NET Standard 2.0 support for Formatters and Reporting packages

### ISSUE THREAD

**Issue by JoJo2406** [AppMetrics/AppMetrics#558]
Would it be possible to allow the Formatters and Reporting packages to target `netstandard2.0`. As with the IAsyncDisposable usage even though the main AppMetrics package targets netstandard2.0 your limited to where you can actually report to (Console, HTTP, Socket and TextFile).

**Comment by JoJo2406** [comment]
I think if you add the reference to [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/1.1.0-preview1.19504.10) you will able to use IAsyncDisposable while only targeting `netstandard2.0`

**Comment by mlapaglia** [comment]
I need the new timer functionality from https://github.com/AppMetrics/AppMetrics/pull/546 but that means 4.0.0, but using this library in a .net 4.7.2 project means it's not compatible. Please consider targeting .net standard 2.0 :)

**Comment by alhardy** [comment]
Are one of you guys able to create a PR for this?

**Comment by mlapaglia** [comment]
I tried cloning the repo and making changes but I had a lot of trouble getting it to build. Errors about nuget feeds missing. Do you have a guide on how to start developing? I can make a pr.

**Comment by mlapaglia** [comment]
Got it working, just needed to read the manual. PR here https://github.com/AppMetrics/AppMetrics/pull/577
