### ISSUE TITLE
Add meta-packages

### ISSUE THREAD

**Issue by Aaronontheweb** [AppMetrics/AppMetrics#574]
I'd be fantastic if we could have some [NuGet meta packages](https://docs.microsoft.com/en-us/dotnet/core/packages#metapackages) for installing commonly used components that are all used in conjunction with each other.

Some examples:

**App.Metrics.AspNetCore.All** - contains:

* App.Metrics.AspNetCore.Mvc
* App.Metrics.AspNetCore.Reporting
* App.Metrics.AspNetCore.Endpoints 
* App.Metrics.AspNetCore.Hosting
* App.Metrics.AspNetCore.Routing
* App.Metrics.AspNetCore.Tracking

**App.Metrics.InfluxDb** - contains:

* App.Metrics.Formatters.InfluxDB
* App.Metrics.Reporting.InfluxDB

**App.Metrics.Elasticsearch** - contains:

*  App.Metrics.Reporting.Elasticsearch 
*  App.Metrics.Formatters.ElasticSearch 

And so on.

**Comment by alhardy** [comment]
Yes sounds good. The Hosting package is sort of that but also includes some started related boilerplate
