### ISSUE TITLE
Prometheus exporter allows illegal labels on metrics

### ISSUE THREAD

**Issue by Aaronontheweb** [AppMetrics/AppMetrics#575]
Working with my App.Metrics integration in my application with Prometheus, I noticed that while the metric names get rewritten to satisfy the [Prometheus data model](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) but labels do not - resulting in a scraping error when Prometheus tries to gather my metrics.

For instance, using the following context and operation name:

```
context = "akka.net"
operation name = "akka.messages.recv"
```

A counter with those values will be rewritten to

```
akka_net_akka_messages_recv_total 1
```
However, if I add labels:

```
context = "akka.net"
operation name = "akka.messages.recv"
labels=("akka.actor.message.type", "Prune")
```

Then we get this, which is illegal according to the Prometheus data model, which specifies that all labels and names must match the Regex `[a-zA-Z_][a-zA-Z0-9_]*`

```
akka_net_akka_messages_recv_total{akka.actor.type="Topic"}
```

I'd propose that similarly to how we rewrite the metric names, we should also rewrite the metric labels when using the Prometheus formatter.

**Comment by alhardy** [comment]
Makes sense. Is this something you can create a PR for?

**Comment by Aaronontheweb** [comment]
Yep - I was looking through the code and I think I can do this next week

**Comment by Aaronontheweb** [comment]
Looks like @suslovk took care of it!

**Comment by ertant** [comment]
Hi, looks like tag values also needed to be formatted like tag names. Protobuf format is now obsolete and only text format accepted, but in text format when a tag value contains " or new line chars scrapper configuration is failing.

According to https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details page, 

> label_value can be any sequence of UTF-8 characters, but the backslash (\), double-quote ("), and line feed (\n) characters have to be escaped as \\, \", and \n, respectively.
