### ISSUE TITLE
App.Metrics Nuget Doesn't Support .Net Frame 4.5.2

### ISSUE THREAD

**Issue by craig-plutoflume** [AppMetrics/AppMetrics#580]
According to the first line on the [home page](https://github.com/AppMetrics/AppMetrics/issues), App Metrics supports .NET 4.5.2.  But when I look at the nuget requirements, I see that only .Net 4.6.1 is supported as of 3.1.0.  Could we get .Net 4.5.2 supported as this was a main driver for my team to incorporate App Metrics in our .NetCore projects (with the knowledge that we could get them into our one 4.5.2 project)?

![image](https://user-images.githubusercontent.com/60099846/84673292-6b778d00-af21-11ea-8bd2-dc2fad63a732.png)

**Comment by mlapaglia** [comment]
Doesn't look like it is supported anymore https://github.com/AppMetrics/AppMetrics/issues/515

**Comment by craig-plutoflume** [comment]
Any knowledge on why?  I'm thinking about forking this and adding support for it, so it would be helpful if there's an idea of hardship I might run into?  Or even if the authors think it's possible. :)

**Comment by alhardy** [comment]
Looks like the readme needs updating. I don't plan on supporting net 4.5.2, I don't have the time to support and maintain such backwards compat on very older versions of the framework.

**Comment by mlapaglia** [comment]
This is mentioned in other places: https://www.app-metrics.io/samples/metrics-code/#net452-metrics-console-sln

Can I help make an example for a 4.8.2?
