### ISSUE TITLE
When can we expect the release of version 4.1.0?

### ISSUE THREAD

**Issue by lavkeshdwivedi** [AppMetrics/AppMetrics#584]
@alhardy, please let us know the release schedule for 4.1.1 version? We're currently upgrading the packages to use dotnetcore3.1 but using the pre-release versions of appmetrics 4.1. If we know the stable release date, it will really help.
Thank you very much!

**Comment by alhardy** [comment]
Probably in a couple of weeks

**Comment by alhardy** [comment]
@lavkeshdwivedi actually,  expect it over the next day ;)
