### ISSUE TITLE
how to metric (counter, timing etc) every actions (method level call) of all asp.net core WebApi Controllers? in custom middleware/filter(may be use  Microsoft.AspNetCore.Mvc.ApiExplorer) AOP?

### ISSUE THREAD

**Issue by Microshaoft** [AppMetrics/AppMetrics#587]
attention

**Comment by Microshaoft** [comment]
attention

**Comment by alhardy** [comment]
There are some default metrics capture by the asp.net core extension packages see https://www.app-metrics.io/web-monitoring/aspnet-core/tracking-middleware/

**Comment by Microshaoft** [comment]
@alhardy I want one metric for
 one method/webapi
 action/route

**Comment by alhardy** [comment]
If you need something else to what's provided in the middleware registered by app metrics, you can build your own using app metrics middleware as a reference
