### ISSUE TITLE
Additional health page

### ISSUE THREAD

**Issue by VadymIan** [AppMetrics/AppMetrics#589]
Hello team!
Actually this is probably not an issue but a request for clarification.
We inherited the project where AppMetrict 2.1v is used and got a requirement to expand health checks.
I mean by default there is already existed page https://.../health, is there any way to add another one alongside and fill it out with new custom health checks (for example https://.../deepHealth)?
Regarding this, I have not found any useful documentation.
Thank you!

**Comment by alhardy** [comment]
Health has been deprecated since Microsoft have an equivalent implementation, I would suggest migrating to that.

You can then still use app metrics to report health checks implemented with Microsoft's implementation. https://www.app-metrics.io/reporting/reporters/microsoft-health-checks/
