### ISSUE TITLE
AddAppMetricsSystemMetricsCollector extension not found in App.Metrics.AspNetCore.All package

### ISSUE THREAD

**Issue by StellaSleptsova** [AppMetrics/AppMetrics#592]
Hello.

I am trying to use AddAppMetricsSystemMetricsCollector  extension in ConfigureServices method according by https://www.app-metrics.io/reporting/collectors/ but I can' use it 
![image](https://user-images.githubusercontent.com/15127745/87432351-8a387480-c5f0-11ea-8784-df756e6dbd48.png)

Version of nuget package is 4.1.0.

**Comment by alhardy** [comment]
You'll need to use the latest preview, this is new
