### ISSUE TITLE
Prometheus Dashboard broken

### ISSUE THREAD

**Issue by Syzuna** [AppMetrics/AppMetrics#593]
The provided Prometheus Dashboard queries all fail.
Are there plans to update them?

**Comment by alhardy** [comment]
Works for me using the [sample app](https://github.com/AppMetrics/AppMetrics/tree/features/4.2.0/src/Reporting/sandbox/MetricsPrometheusSandboxMvc).

Note the default /metrics endpoint is set to proto format, you'll have to change that to text [here](https://github.com/AppMetrics/AppMetrics/blob/features/4.2.0/src/Reporting/sandbox/MetricsPrometheusSandboxMvc/Program.cs#L38) Mabye this is your issue?

I've uploaded a new revision fixing a fiew things: apdex, errors and removing health checks. [see here](https://grafana.com/grafana/dashboards/2204/revisions).

![image](https://user-images.githubusercontent.com/729185/87765790-996f2a80-c85b-11ea-8b10-0deed708c99c.png)

**Comment by dehghanfar** [comment]
@alhardy thanks for all the great content. can you remove the influx DB from this dashboard?
