### ISSUE TITLE
How to disable all logs from App.Mertics

### ISSUE THREAD

**Issue by krabobobr** [AppMetrics/AppMetrics#601]
I'm trying to add metrics to my web application (.net core 3.1). everything work fine, but I faced with the fact that metrics spam into my logger some trace information:
![image](https://user-images.githubusercontent.com/61837522/90374964-fa696880-e07c-11ea-9545-a97a223161ee.png)
App-Metrics spam into logs so often that I get ~100 megabytes of useless logs every 2-3 hours. Unfortunate, I didnt find anything about internal logs at https://www.app-metrics.io/web-monitoring/aspnet-core/reporting/ The only thing than I got: I disabled reporting. It reduced count of logs, but there are still a lot of them (and all of them, as for me, dont contains any useful information).
program.cs:

```
    public static void Main(string[] args)
    {
        Metrics = AppMetrics.CreateDefaultBuilder().Configuration
            .Configure(options => options.ReportingEnabled = false)
            .OutputMetrics.AsPrometheusPlainText()
            .Build();

        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args)
    {
        var builder = Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>());

        builder = builder.ConfigureMetrics(Metrics)
            .ConfigureAppMetricsHostingConfiguration(options => options.MetricsTextEndpoint = "/metrics")
            .UseMetrics(options =>
            {
                options.EndpointOptions = endpointsOptions =>
                {
                    endpointsOptions.MetricsTextEndpointOutputFormatter = Metrics.OutputMetricsFormatters
                        .OfType<MetricsPrometheusTextOutputFormatter>().First();
                };
            })
            .UseMetricsEndpoints(options => options.MetricsEndpointEnabled = false);

        return builder;
    }
```
Can I somehow disable all logs from App-Metrics(or at least disable all trace information)?

**Comment by EugeneKrapivin** [comment]
if you are using the `Microsoft.Extensions.Logging` you can probably set a filter in `appsettings.json`, or add it programatically by configuring the logger your self rather than using the default configuration set in `CreateDefaultBuilder`

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#configure-logging

**Comment by alhardy** [comment]
Yeah that works ^

**Comment by marcinjahn** [comment]
I have a similar problems. My console output has lots of traces from AppMetrics. I have the following config in `appsettings.json`:

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Error"
    }
  }
}
```

Shouldn't that work? It does work for other libraries I use and my own code as well.
