### ISSUE TITLE
Why application_httprequests_transactions_per_endpoint is always zero?

### ISSUE THREAD

**Issue by albertobelardi** [AppMetrics/AppMetrics#603]
Hello, congratulations for the library, versatile and simple. I have a problem, as you can see from the title of the post, I could not understand why these values ​​are always 0, can you help me? Thank you.

# HELP application_httprequests_transactions_per_endpoint 
# TYPE application_httprequests_transactions_per_endpoint summary
application_httprequests_transactions_per_endpoint_sum{route="GET",server="MAX",app="SampleMetricsApp",env="development"} 0
application_httprequests_transactions_per_endpoint_count{route="GET",server="MAX",app="SampleMetricsApp",env="development"} 0
application_httprequests_transactions_per_endpoint{route="GET",server="MAX",app="SampleMetricsApp",env="development",quantile="0.5"} 0
application_httprequests_transactions_per_endpoint{route="GET",server="MAX",app="SampleMetricsApp",env="development",quantile="0.75"} 0
application_httprequests_transactions_per_endpoint{route="GET",server="MAX",app="SampleMetricsApp",env="development",quantile="0.95"} 0
application_httprequests_transactions_per_endpoint{route="GET",server="MAX",app="SampleMetricsApp",env="development",quantile="0.99"} 0

![immagine](https://user-images.githubusercontent.com/25862755/91560567-54e6ac80-e93a-11ea-94d0-1cd91f3ae4c4.png)

**Comment by alhardy** [comment]
I don't see this happening in the [influxdb sample app](https://github.com/AppMetrics/AppMetrics/blob/7474c6552f/src/Reporting/sandbox/MetricsInfluxDBSandbox/Host.cs). Could you try updating the appmetrics influxdb databaord listed on grafana.

**Comment by gsferreira** [comment]
In case anyone is facing this, I was facing the same problem and I fixed the problem by ensuring that I call `app.UseMetricsEndpoints()` before calling `app.UseEndpoints()`.
