### ISSUE TITLE
How to use AppMetrics' Prometheus reporter to track metrics on services without http endpoints

### ISSUE THREAD

**Issue by matthewkrieger** [AppMetrics/AppMetrics#606]
What is the recommendation for using AppMetrics' Prometheus reporter with services that do not have http endpoints, since App.Metrics.Prometheus creates a `/metrics-text` endpoint which Prometheus scrapes?  For example can the non-http service write to an external endpoint?

**Comment by alhardy** [comment]
Are you referring to a push based approach with Promoetheus rather than a pull?

I believe the recommended approach with Prom is to pull rather than push.

**Comment by matthewkrieger** [comment]
Here’s a scenario - let’s say I want to use app metrics to track data on my .net azure webjob. Web jobs of course have no http server. So I don’t see how I can create the /metrics page so the prom server can pull. What are my options? I assumed I could use app metrics for more than just web apps.

**Comment by matthewkrieger** [comment]
...or in a queue triggered azure function.

**Comment by alhardy** [comment]
@matthewkrieger you could implement an HTTP listener for the metrics to be scaped if you really don't want to add asp.net core to a deamon. There's no implementation on this which AppMetrics provides, it could be worth adding, but should be straight forward to implement yourself.

**Comment by justinmchase** [comment]
The recommendation with prom is pull when possible but then prometheus supports a push gateway for other sceanrios, so pushing should be supported by this library.

For example I have some cron jobs which may only run for a few seconds, I need to be able to submit some metrics about it running at all and it doesn't live long enough for the pull to ever happen.
