### ISSUE TITLE
Can't install on a netcoreapp2.1

### ISSUE THREAD

**Issue by seif** [AppMetrics/AppMetrics#611]
Hello,

I am trying to update an existing app from AppMetrics 3.1 to 4.1 but when I do that I get an error because App.Metrics.Extesnsions.Hosting depends on Microsoft.Extensions.Hosting.Abstractions >= 3.1 and the project has a reference to 2.1.

netcoreapp2.1 is still supported until next year, is appmetrics not supporting it intentional?

I can reproduce with

    dotnet new web -f netcoreapp2.1
    dotnet add package App.Metrics.Extensions.Hosting

Which gives the error:
error: Version conflict detected for Microsoft.Extensions.Configuration.Abstractions. Install/reference Microsoft.Extensions.Configuration.Abstractions 3.1.0 directly to project test2 to resolve this issue.
error:  test2 -> App.Metrics.Extensions.Hosting 4.1.0 -> Microsoft.Extensions.Hosting.Abstractions 3.1.0 -> Microsoft.Extensions.Configuration.Abstractions (>= 3.1.0)
error:  test2 -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Configuration.Abstractions (>= 2.1.1 && < 2.2.0).
info : Package 'App.Metrics.Extensions.Hosting' is compatible with all the specified frameworks in project '/home/seif/projects/test2/test2.csproj'.
info : PackageReference for package 'App.Metrics.Extensions.Hosting' version '4.1.0' updated in file '/home/seif/projects/test2/test2.csproj'.
info : Committing restore...
info : Generating MSBuild file /home/seif/projects/test2/obj/test2.csproj.nuget.g.props.
info : Writing assets file to disk. Path: /home/seif/projects/test2/obj/project.assets.json
log  : Failed to restore /home/seif/projects/test2/test2.csproj (in 800 ms).

I thought things have become better and easier with netcore and assembly reference but seems every major version they break something and code gets littered with conditionals.

**Comment by alhardy** [comment]
Argh, yeah versioning is a pain. Is this something you'd be able to sort out via a PR. I probably won't get to it for a few weeks

**Comment by seif** [comment]
Sure, I'll have a look sometime this week.

**Comment by seif** [comment]
hehe, as it turns out, I couldn't get to it for a few weeks either :D

**Comment by seif** [comment]
My change doesn't fix this still :s tested with 4.2 previoew26.

It is still trying to install version 3.1 of the hosting.abstractions package I had tested this locally and it worked, maybe I tested back when FrameworkVersion was still 2.1 or something.

As far as I can tell, the issue is that the microsoft packages all use version 3.1 https://github.com/AppMetrics/AppMetrics/blob/features/4.2.0/src/Directory.Build.targets#L59-L64 

I am pretty sure we can keep FrameworkVersion at 2.1 but need to look into this some more :s

**Comment by seif** [comment]
@alhardy doesn't look like I can reopen issues, shall I create a new issue?
