### ISSUE TITLE
Question: Accessing metrics

### ISSUE THREAD

**Issue by erinloy** [AppMetrics/AppMetrics#616]
Is there a straightforward way to access metrics in process?  I want to display some metrics relating to frame/data rate, etc. in a desktop app, and also have the benefit of having those metrics exportable to other systems.

Alternatively, has anyone implemented anything like an in memory reporter class?

**Comment by alhardy** [comment]
@erinloy yes it's possible to access metrics in process, see [these](https://github.com/AppMetrics/AppMetrics/blob/features/4.2.0/src/Core/test/App.Metrics.Facts/Filtering/MetricsContextFilteringTests.cs#L23) test for example. Keep in mind that for metrics that are set to "ResetOnReporting", once they are read the values will be reset.
