### ISSUE TITLE
Formatters name inconsistency

### ISSUE THREAD

**Issue by Alessar** [AppMetrics/AppMetrics#620]
It is not a bug but looks like naming inconsistency.

App.Metrics.`Formatters`.GrafanaCloudHostedMetrics
App.Metrics.`Formatters`.Graphite
App.Metrics.`Formatters`.InfluxDB
App.Metrics.`Formatters`.Prometheus
but
App.Metrics.`Formatting`.Datadog

**Comment by alhardy** [comment]
Yep a bit annoying, problem is I wasn't able to push my package following the convention due to someone writing publishing this https://www.nuget.org/packages/App.Metrics.Formatters.Custom.Datadog/2.0.0-alpha2

**Comment by Alessar** [comment]
Very strange that it causes such an issue.
Especially that `App.Metrics.Formatters.Datadog` and `App.Metrics.Formatters.Custom.Datadog` are different strings.
