### ISSUE TITLE
How to disbale default metrics

### ISSUE THREAD

**Issue by lsahub** [AppMetrics/AppMetrics#623]
How to disbale default metrics e.g. application_httprequests_transactions_per_endpoint summary

![metrics-text](https://user-images.githubusercontent.com/45483236/98827494-ffee0900-2447-11eb-89ba-97190aaa228c.png)

**Comment by henrysmith** [comment]
You can remove the middleware components by not adding it in the configuration. 


You can refer to the documentation [(WEB METRICS)](https://www.app-metrics.io/web-monitoring/aspnet-core/tracking-middleware/)


       // To add all available tracking middleware
        app.UseMetricsAllMiddleware();

        // Or to cherry-pick the tracking of interest
        // app.UseMetricsActiveRequestMiddleware();
        // app.UseMetricsErrorTrackingMiddleware();
        // app.UseMetricsPostAndPutSizeTrackingMiddleware();
        // app.UseMetricsRequestTrackingMiddleware();
        // app.UseMetricsOAuth2TrackingMiddleware();
        // app.UseMetricsApdexTrackingMiddleware();`
