### ISSUE TITLE
Add StatsDFormatter for socket reporter

### ISSUE THREAD

**Issue by Aaronontheweb** [AppMetrics/AppMetrics#624]
Can use the "socket reporter" https://www.app-metrics.io/reporting/reporters/socket/ and provide a simply formatter package for statsd

_Originally posted by @alhardy in https://github.com/AppMetrics/AppMetrics/issues/229#issuecomment-443503373_

**Comment by Aaronontheweb** [comment]
We should have a StatsD formatter for the StatsD UDP and TCP interfaces here https://github.com/statsd/statsd

Along with documentation on how to actually use StatsD (i.e. separate from the Socket reporting interface, even though that's what gets used underneath the covers)

**Comment by alhardy** [comment]
4.2.0-preview.0.25 published
