### ISSUE TITLE
Request Entity Too Large Erro

### ISSUE THREAD

**Issue by tedlee87** [AppMetrics/AppMetrics#633]
Hi,

I have set up my AppMetrics with InfluxDB and i am sending a lot of Counts and i get the following issue.

|App.Metrics.Reporting.InfluxDB.Client.DefaultLineProtocolClient|Failed to write to InfluxDB - StatusCode: RequestEntityTooLarge Reason: Request Entity Too Large 

My question is, 

Do the request get bigger? 
How do I prevent this error?

Thanks

**Comment by alhardy** [comment]
Requests payload obviously increases with the more metrics you add. What's the size of the payload?

The reporter doesn't do any type of batching to handle this, I've never had enough metrics recording in a single app for this to be an issue
