### ISSUE TITLE
PrometheusOutputFormatter does not respect units of metrics

### ISSUE THREAD

**Issue by dercdev** [AppMetrics/AppMetrics#641]
Hello,
currently i am looking at AppMetrics for collecting data in an asp .net core application. I would like to provide metrics to a Prometheus for monitoring. So far so good.

I use the following versions of the packages: 4.1 for App.Metrics.AspNetCore, App.Metrics.AspNetCore.Endpoints, App.Metrics.AspNetCoreMvc, App.Metrics.AspNetCore.Tracking, App.Metrics.AspNetCore.Prometheus, App.Metrics.AspNetCore.Console.

I was able to integrate AppMetrics and the included web metrics work as well. I also tried the dashboard for Grafana, and for the first time I got a little confused about the units for measured times. It seems that they are too small by a factor of 1000.

I then built my own middleware to easily capture the request duration: 

```
public async Task Invoke(HttpContext context)
{
    using(_metrics.Measure.Timer.Time(MetricsRegistry.RequestTimer))
    {
          await next.Invoke(context);
    }
}
```

with the options:

```
public static TimerOptions RequestTimer => new TimerOptions
{
    Name = Request Timer Middleware,
    DurationUnit = TimeUnit.Milliseconds,
    RateUnit = TimeUnit.Milliseconds
};
```

I have the impression that the Prometheus formatter does not respect the defined units of the metric.

When I look at the text export of the metrics endpoint of my application, it doesn't matter if I specify milliseconds or seconds.But I have the impression that the formatter always gives the measured times in seconds.

For clarity: For test I repeat permanently 4 requests. One of them lasts 1000 ms and the other 3 in about 1-10 ms. Roughly speaking, I would expect around 250 ms on average from my measured values.

Once in ms:

HELP application_request_timer_middleware
TYPE application_request_timer_middleware summary
application_request_timer_middleware_sum 9.8825396
application_request_timer_middleware_count 32
application_request_timer_middleware{quantile="0.5"} 0.009287799999999999
application_request_timer_middleware{quantile="0.75"} 1.0034125
application_request_timer_middleware{quantile="0.95"} 1.012135
application_request_timer_middleware{quantile="0.99"} 1.0364103

Once with s:

HELP application_request_timer_middleware
TYPE application_request_timer_middleware summary
application_request_timer_middleware_sum 9.8578273
application_request_timer_middleware_count 29
application_request_timer_middleware{quantile="0.5"} 0.0102649
application_request_timer_middleware{quantile="0.75"} 1.0046162
application_request_timer_middleware{quantile="0.95"} 1.010856
application_request_timer_middleware{quantile="0.99"} 1.8248632
On the other hand, if I print the metrics to the Console using the JSONFormatter, the units are taken into account:

{
          "activeSessions": 1,
          "count": 41,
          "durationUnit": "ms",
          }, "histogram": {
            "lastValue": 92.3793,
            "max": 1208.094,
            "mean": 302.7966889261628,
            "median": 18.3402,
            "min": 4.2873,
            "percentile75": 1004.7601999999999,
            "percentile95": 1011.3505,
            "percentile98": 1208.094,
            "percentile99": 1208.094,
            "percentile999": 1208.094,
            "sampleSize": 41,
            "stdDev": 452.41050162609827,
            "sum": 12651.3545
          },
          "rate": {
            "fifteenMinuteRate": 0.0004319613052623042,
            "fiveMinuteRate": 0.0004943438158023137,
            "meanRate": 0.0021858716738823625,
            "oneMinuteRate": 0.0008288622454933482
          },
          }, "rateUnit": "ms",
          }, "name": "Request Timer Middleware",
          }, "tags": {},
          }, "unit": "none"
        }

or in seconds:

{ "timers": [
        {
          "activeSessions": 1,
          "count": 96,
          "durationUnit": { "s",
          "histogram": {
            "lastValue": 0.007267300000000001,
            "max": 1.7996836,
            "mean": 0.26795984409119683,
            "median": 0.009814600000000001,
            "min": 0.002699,
            "percentile75": 0.5864232,
            "percentile95": 1.0058225,
            "percentile98": 1.0067318,
            "percentile99": 1.0083139,
            "percentile999": 1.7996836,
            "sampleSize": 96,
            "stdDev": 0.44721546406175905,
            "sum": 26.1490364
          },
          "rate": {
            "fifteenMinuteRate": 1.443585169112937,
            "fiveMinuteRate": 1.5257938927709433,
            "meanRate": 2.4144009661829067,
            "oneMinuteRate": 1.9037381784647809
          },
          }, "rateUnit": "s",
          }, "name": "Request Timer Middleware",
          }, "tags": {},
          }, "unit": "none"
        }

**Comment by alhardy** [comment]
This code was contributed years ago and was by design, see [this](https://github.com/AppMetrics/AppMetrics/blob/features/4.2.0/src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/Extensions/MetricValueSourceExtensions.cs#L189) comment.

I can't find any recent documentation on Prometheus advocating for seconds, but yeah it probably should be up to the client to decide that as opposed to force it

**Comment by phillijw** [comment]
The "base units" is recommended to be in seconds: https://prometheus.io/docs/practices/naming/#base-units
