### ISSUE TITLE
StatsD and DogStatsD does not understand the meter metrics

### ISSUE THREAD

**Issue by Arkatufus** [AppMetrics/AppMetrics#668]
This is related to https://github.com/petabridge/phobos-issues/issues/15
It seems like StatsD removed their support for Meter and DogStatsD doesn't support it either.
Instead, DogStatsD converts Meter into their own Rate metric, which is similar in function to the AppMetrics and StatsD Count metric.

**Comment by alhardy** [comment]
4.2.0-preview.0.33 pushed
