### ISSUE TITLE
Prometheus Exporter: Histograms have incorrect type in output generated by Prometheus plain text exporter

### ISSUE THREAD

**Issue by maciejbanach** [AppMetrics/AppMetrics#680]
## Description
AppMetrics Histograms are equivalent to Prometheus summary. Unfortunately, AppMetrics plain text Prometheus Exporter incorrectly assigns metric type as histogram. Only type is assigned incorrectly, as data is correctly exported in summary format. 

## Details

Mismatch occurs somewhere where MetricFamily used [here (AsciiFormatter - L49)](https://github.com/AppMetrics/AppMetrics/blob/4.1.0/src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/AsciiFormatter.cs#L49) is generated. Type is assigned to histogram. However when Metric is read to write metric - [AsciiFormatter - L68](https://github.com/AppMetrics/AppMetrics/blob/4.1.0/src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/AsciiFormatter.cs#L68) histogram is correctly converted to summary.

Here is snapshot from debugger. In this metric family:
- metric.Summary exist
- metric.Histogram is null
- type is 4 (HISTOGRAM)
![image](https://user-images.githubusercontent.com/21343474/114190303-73d70380-994b-11eb-90bd-f979f11e4032.png)

Therefore if MetricType would be assigned correctly, then this should fix this bug.

### AppMetrics Version
4.1.0

### Example
Bug can be observed on default PUT/POST size histograms. Data is correctly converted into Prometheus summary, however TYPE is histogram.
```
# HELP application_httprequests_post_size 
# TYPE application_httprequests_post_size histogram
application_httprequests_post_size_sum{server="server",app="application",env="production",deployment="regular"} 2
application_httprequests_post_size_count{server="server",app="application",env="production",deployment="regular"} 1
application_httprequests_post_size{server="server",app="application",env="production",deployment="regular",quantile="0.5"} 2
application_httprequests_post_size{server="server",app="application",env="production",deployment="regular",quantile="0.75"} 2
application_httprequests_post_size{server="server",app="application",env="production",deployment="regular",quantile="0.95"} 2
application_httprequests_post_size{server="server",app="application",env="production",deployment="regular",quantile="0.99"} 2
```
Correctly this metric should look like this:
```
# HELP application_httprequests_post_size 
# TYPE application_httprequests_post_size summary
application_httprequests_post_size_sum{server="server",app="application",env="production",deployment="regular"} 2
application_httprequests_post_size_count{server="server",app="application",env="production",deployment="regular"} 1
application_httprequests_post_size{server="server",app="application",env="production",deployment="regular",quantile="0.5"} 2
application_httprequests_post_size{server="server",app="application",env="production",deployment="regular",quantile="0.75"} 2
application_httprequests_post_size{server="server",app="application",env="production",deployment="regular",quantile="0.95"} 2
application_httprequests_post_size{server="server",app="application",env="production",deployment="regular",quantile="0.99"} 2
```

### Impact
In our case this bug prevents gathering metrics in our cloud deployment. Open Telemetry Collector is used to gather metrics and it rejects all of the metrics when it is unable to parse incorrect histograms. In our case we currently disable histograms in output to workaround this issue.

### Fix
Unfortunately I had no time to dig deeper into this issue to propose fix.  Is there chance that this issue could be fixed in 4.1.0?

~bug

**Comment by alhardy** [comment]
Thanks for posting a detailed investigation.

This has been fixed in 4.2.0, see [here](https://github.com/AppMetrics/AppMetrics/commit/2bec099161460bab015953e7c739c73cdcc52bbe#)

A stable 4.2.0 release will be pushed next week some time.

**Comment by maciejbanach** [comment]
Great!

Thanks for the hard work done on this library. 

Looking forward to test release 4.2.0.

**Comment by alhardy** [comment]
@maciejbanach appreciate the thanks. 4.2.0 has been published to nuget
