### ISSUE TITLE
Registered multiple MetricsReporterBackgroundService

### ISSUE THREAD

**Issue by czd890** [AppMetrics/AppMetrics#693]
Code like:
```C#
IHostBuilder
    .ConfigureMetricsWithDefaults(.....)
    .ConfigureWebHostDefaults((IWebHostBuilder webBuilder)=>{
            webBuilder.UseMetrics(.....)
    });
```
Have two `MetricsReporterBackgroundService` register to `ServiceCollection`,  the metrics data will be reported as 2 copies.

We can modify it to:

Case 1: only be registered once(I like it)
```C#
services.AddHostedService<MetricsReporterBackgroundService>(); // internal used TryAddEnumerable
```
Case 2: last one is valid
```C#
var exists = services.FirstOrDefault(desc => desc.ServiceType == typeof(IHostedService) && GetImplementationType(desc) == typeof(MetricsReporterBackgroundService)) 

if(exists !=null) services.Remove(exists);
services.AddSingleton(.....);
```
//GetImplementationType() like [Microsoft.Extensions.DependencyInjection.ServiceDescriptor.GetImplementationType()](
https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs#L125)

**Comment by anr-variant** [comment]
Locally I've copied and modified the code to use the `AddHostedService` version since that's the standard way of registering hosted service implementations. Would be good to see this fixed.
