### ISSUE TITLE
Reporting appmetrics to InfluxDb v2 fails on authentication

### ISSUE THREAD

**Issue by VeldMuijz** [AppMetrics/AppMetrics#706]
Hi,
I wanted to use AppMetrics with influxdb v2. The docs describe authenting with a username and password, but my influxdb instance only accepts the tokens that are generated.
When I try to authenticate with username and password it throws an 'Failed to authenticate' error.

[22:38:48 ERR] Failed to write to InfluxDB - StatusCode: Unauthorized Reason: Unauthorized
[22:38:48 ERR] Failed to write to InfluxDB - StatusCode: Unauthorized Reason: Unauthorized
[22:39:08 ERR] Too many failures in writing to InfluxDB, Circuit Opened
[22:39:08 WRN] Reporter App.Metrics.Reporting.InfluxDB.InfluxDbMetricsReporter FlushAsync failed
[22:39:18 ERR] InfluxDB write backoff for 30 secs
[22:39:18 ERR] Too many failures in writing to InfluxDB, Circuit Opened

```
public static IServiceCollection AddInfluxDbMetrics(this IServiceCollection services,
            IConfiguration configuration)
        {
            var influxDbOptions = configuration.GetSection("InfluxDb").Get<InfluxDbOptions>();
            var metrics = new MetricsBuilder()
                .Report.ToInfluxDb(options =>
                {
                    options.InfluxDb.BaseUri = new Uri(influxDbOptions.Host);
                    options.InfluxDb.UserName = "administrator";
                    options.InfluxDb.Password = "administrator";
                    options.InfluxDb.Database = "metrics";
                    options.InfluxDb.CreateDataBaseIfNotExists = true;
                })
                .Build();
            
            services.AddMetrics(metrics);
            services.AddMetricsReportingHostedService();
            
            return services;
        }
```

The username and password are correct, I can easily login to the web portal. 
All the documentation on influx in this project is pre-v2.
Does this project support influxdb v2 or is it still only compatible with 1.8?
When using InfluxDB.Client nuget package I was able to successfully communicate to influx with a token.

**Comment by alex-kabin** [comment]
I managed to write metrics with username-password using compatibility features of InfluxDB v2.
See https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/v1/
Here is my examples of Influx cli commands:

-- create v1 user with binding to new organization-user with permissions:
influx v1 auth create --username user -o org -t "GolbYm3cFxbDxHFCn72rX-qFRp5498Y_1lUSz6K_2Au1uT13pl8VytBbGQZIqhONJ4uD_xijsQRh-lzefiQE1A==" --write-bucket 89408df11e946138 --read-bucket 89408df11e946138

-- create v1 database with binding to new bucket
influx v1 dbrp create -o org -t "GolbYm3cFxbDxHFCn72rX-qFRp5498Y_1lUSz6K_2Au1uT13pl8VytBbGQZIqhONJ4uD_xijsQRh-lzefiQE1A==" --bucket-id 89408df11e946138 --db app_metrics --rp autogen

where:
-o <org> is your organization name in InfluxV2
-t <token> is token of your user in InfluxV2

**Comment by alex-kabin** [comment]
consider using my implementation: [App.Metrics.Reporting.InfluxDB2](https://www.nuget.org/packages/App.Metrics.Reporting.InfluxDB2/)

**Comment by VeldMuijz** [comment]
Seems to be fixed in: https://github.com/AppMetrics/AppMetrics/pull/701
