### ISSUE TITLE
AppMetrics Maintenance Plan

### ISSUE THREAD

**Issue by kiru1283** [AppMetrics/AppMetrics#747]
There seem to have been no releases in this repo since 2021, are there any plans to maintain this repo in the future .
We want to implement this nuget for many of our project and wondering on the roadmap for this project in the future.

**Comment by kiru1283** [comment]
@alhardy may be you can guide us on this?

**Comment by alhardy** [comment]
I've stopped maintaining the project given projects like open telemetry, open telemetry I think is the way forward for observability for now.

If AppMetrics is still useful, happy to add those that wish to contribute as owners to the repo.

**Comment by kiru1283** [comment]
Thanks for the quick response. Closing the issue as its answered.
